### ISSUE TITLE
Push command

### ISSUE THREAD

**Issue by rejeep** [cask/cask#108]
Add push command that can be used to push package to various sources
### spec
- Usage: `cask push [version] [mirror]`
- DSL to match mirrors

``` lisp
(require 'git)
(require 'url)

(mirror melpa
 (git-push "origin" "master"))

(mirror marmalade
 (url-post "http://marmalade-repo.org/packages" (read-file "my-package.el")))
```
### questions
- Should there be any magic in Cask or should it simply provide a hook. The package developer would then have to write the push code.

**Comment by lxsameer** [comment]
I implemented a prototype of `cask push` which works with our repository service (**Medusa**). We did not released it yet but it provides an ELPA compatible API along side with a Json one. We had rubygems (Medusa) and bundler (Cask) in mind to create it. I like to know you opinion on this too.

This way we can implement **search** and **show** functionality for cask in the future.

**Comment by lunaryorn** [comment]
@lxsameer What is Medusa?

**Comment by lxsameer** [comment]
It's a repository service we built which is completely ELPA compatible. Rubygems + bundler combination inspired us to do this. We think cask as our bundler and  Medusa as rubygems.

**Comment by lunaryorn** [comment]
@lxsameer Do you have a link?

**Comment by lxsameer** [comment]
@lunaryorn As i mentioned we didn't released it yet. but here is the url to the git repo.
https://github.com/KusoIDE/Medusa

We working on it very hard

**Comment by lunaryorn** [comment]
@lxsameer It looks interesting, but as long as it's not released and has some success, I'm afraid it's not something that we would like to support in Cask.  And meanwhile, since MELPA has become more or less the standard extension repository for Emacs, I see less and less need to add a `push` command to Cask.

**Comment by lxsameer** [comment]
@lunaryorn completely logical. I don't have plan do implement this on `Cask` right now. We have long way to go. But adding a generic `push` command won't hurt any one.

I'll add the `push` command in as abstract as I can and provide a PR. I you guys find handy and useful we can merge it. But if you doesn't found it good or necessary I have to fork `Cask` and continue working on the fork untill **Medusa** gains some fame and usage.

**Comment by rejeep** [comment]
@lxsameer Sounds interesting. What do you mean when you say "we"?

**Comment by lxsameer** [comment]
@rejeep by "we" I mean the team working on **Medusa**

**Comment by Fuco1** [comment]
Sadly marmalade is dead as far as most people are concerned and I think we are now living in a MELPA hegemony, which is not necessarily a bad thing (at least we know what problems to focus on).

I think we can close this issue as it will likely never happen.
