### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by rejeep** [cask/cask#12]
Add Travis CI support. I'm thinking something like this:

```
carton travis [options]
```

**Comment by Fuco1** [comment]
What's the feature here? Should that command generate the travis yaml config?

**Comment by rejeep** [comment]
I guess so, don't really remember

**Comment by Fuco1** [comment]
That should be fairly simple with things like this we have now https://gist.githubusercontent.com/rejeep/ebcd57c3af83b049833b/raw

I think I would like a feature like this, I am always annoyed copying the setup from another project and then changing some minor details.  I think we can cover 95% use-cases with a very simlple default setup.

**Comment by rejeep** [comment]
Yes, I agree

**Comment by conao3** [comment]
Now, here is travis.yml and travis test every push/p-r. This issue solved I think, close.
