### ISSUE TITLE
Bootstrap versions

### ISSUE THREAD

**Issue by rejeep** [cask/cask#171]
Too often do we git issue reports that upgrading Cask broke it. This is usually because people do not use the built in `cask upgrade` command, but does a `git pull` instead.

As a suggestion, how about adding Melpa version in the bootstrap file to make sure we have the required version. If not, Cask will automatically update.

**Comment by dickmao** [comment]
`cask upgrade` I think is a tad overwrought.  In the age of git ubiquity, I feel people, especially those skilled enough to use cask, can capably git pull to upgrade.  In any case, the current state makes enforcing up-to-dated'ness in `cask-bootstrap.el` a vestigial notion.
