### ISSUE TITLE
Idea: Using Python setup.py based packaging to solve cross-platform issues, bootstrapping problem and network issue.

### ISSUE THREAD

**Issue by tkf** [cask/cask#202]
(Branching off from https://github.com/cask/cask/pull/199#issuecomment-38382815 to avoid mixing discussion about BAT-based solution in Windows.)

The idea is to use Python's setup.py for packaging Cask.  You can even bundle bootstrap Emacs Lisp libraries into the package so that you can avoid extra http connection to fetch these libraries.  This helps you:
1. Providing CLI everywhere including Windows without writing any hack.
2. Reducing network connections and avoid using unreliable connections such as raw.github.com.  This gives more robust Travis CI for Emacs plugins.
3. Good control over bootstrap packages.  Fixes #171.

Of course, the choice of packaging system is a trivial issue. For example, using Ruby based system could be a good option as long as it provides cross-platform installation of CLI.

**Comment by Fuco1** [comment]
Windows support was added in #239
