### ISSUE TITLE
local git dependencies for development

### ISSUE THREAD

**Issue by ksjogo** [cask/cask#205]
Hi, I am developing some emacs modes and would like to use cask to have compiled versions/autoloads of them as well. Adding a dependency via :git "file://" works fine so far, but cask is cloning from there and I have to edit the original and run cask again to get updated versions. It is possible to have a some flag to keep the package in place and not clone to the cask directory?

**Comment by Fuco1** [comment]
There is a duplicate issue for autoloading, the rest of the functionality is provided by linking.  Dependencies are now also automatically pulled once #443 is merged.
