### ISSUE TITLE
Install fetcher dependency even if package is installed

### ISSUE THREAD

**Issue by rejeep** [cask/cask#206]
Currently, we do not install a package if it is already installed. This causes issues for packages such as `org` and `gnus`, which are built in, hence already installed.

I wanted to hear what people think about this case when the dependency is a fetcher dependency, for example:

``` lisp
(depends-on "gnus" :git "/path/to/gnus")
```

Should we install it then or can this lead to any issues?

**Comment by Fuco1** [comment]
This makes sense to me, I'll look into it.

**Comment by dickmao** [comment]
Consolidating with #203
