### ISSUE TITLE
Install from specific source

### ISSUE THREAD

**Issue by rejeep** [cask/cask#212]
Emacs 24.4 supports installing packages from specific sources using `package-pinned-archives` (see http://www.reddit.com/r/emacs/comments/264dz0/getting_stable_packages_from_melpa/choadpr).

Cask could support this using a syntax like this:

``` lisp
(depends-on "foo" :source melpa)
(depends-on "bar" :source melpa-stable)
```

**Comment by Fuco1** [comment]
Duplicate of #252
