### ISSUE TITLE
Homebrew install location

### ISSUE THREAD

**Issue by noahfrederick** [cask/cask#233]
Hi,

I use Cask for my personal Emacs configuration.

The Python installer installs `cask.el` into `$HOME/.cask/`, and [the docs](http://cask.readthedocs.org/en/latest/guide/usage.html#quickstart) advise including the following snippet in one's `init.el`:

``` elisp
(require 'cask "~/.cask/cask.el")
(cask-initialize)
```

However, when installed via Homebrew, `cask.el` gets symlinked into `$(brew --prefix)/share/emacs/site-lisp/` instead, which is not mentioned. I share an `init.el` across multiple machines and would rather not worry about what method was used to install Cask (let alone what `brew --prefix` happens to be).

While I can always create extra symlinks myself, I propose that the location of the elisp files should be made consistent between installation methods, or at least be documented. On the other hand, I suppose that Homebrew is installing the package system-wide, and that linking files into the current user's home directory is inappropriate. Feel free to comment.

Thanks for your consideration.

**Comment by dickmao** [comment]
Please reopen if this remains an issue.  Things will improve when macos gets added to CI.
