### ISSUE TITLE
DSL `files` does not work as document describes.

### ISSUE THREAD

**Issue by kenoss** [cask/cask#242]
The current document tells us `files` regards S-exp as directory structure.  However it does not actually because `package-build-expand-file-specs` used in `cask-files` doesn't.  If one want to add `.el` files in `lisp` directory, he have to write `(files "lisp/*.el")`, not `(files ("lisp" ("*.el"))`.

So description of `files` in document needs change.

**Comment by Fuco1** [comment]
I just got burned on this also and the docs still are a bit unclear to me. 

@rejeep I suspect the `./doc` directory is built automatically and published on readthedocs, correct? I'll try to update it to make it a bit more clear.

**Comment by rejeep** [comment]
@Fuco1 IIRC yes
