### ISSUE TITLE
DSL `files` in remote git repository does not work.

### ISSUE THREAD

**Issue by kenoss** [cask/cask#243]
AIU, `files` directive in Cask file in remote git repository can be used to indicate, like MELPA recipe, where `.el` files exist that we need.  However, cask seems not to see that.  For example, with Cask file

```
...
(depends-on "erfi" :git "https://github.com/kenoss/erfi" :branch "integration-with-cask")
....
```

`cask` exit with errror:

```
$  cask
Wrote /usr/home/keno/git.keno/emacs-config/dot.emacs.d/.cask/24.2.1/elpa/archives/gnu/archive-contents
Wrote /usr/home/keno/git.keno/emacs-config/dot.emacs.d/.cask/24.2.1/elpa/archives/melpa/archive-contents
Dependency erfi failed to install: No matching file(s) found in /usr/home/keno/.cask/tmp/checkout/erfi/: (*.el *.el.in dir *.info *.texi *.texinfo doc/dir doc/*.info doc/*.texi doc/*.texinfo (:exclude .dir-locals.el tests.el *-test.el *-tests.el))
Output:
```

Under the git directory, `cask files` can find files:

```
$  cask files
lisp/erfi-macros.el
lisp/erfi-srfi-1.el
```

Can't we solve dependencies of packages that are not registered MELPA or something yet?

**Comment by dickmao** [comment]
Aside from the fact that so-called "fetcher dependencies", e.g., `depends-on :git`, are not quite working, counterfeiting third-party package manifests (`foo-pkg.el` or Package-Requires headers) with one's own `:files` specification is fraught.
