### ISSUE TITLE
Install dependencies fails

### ISSUE THREAD

**Issue by nlamirault** [cask/cask#247]
hi,
i try to install Scame dependencies using Cask , and i've got an error with w3m-cookie [1].
Same error on my computer using Emacs 24.3. Any idea ?

Do you know how can i use this with Cask : 

``` lisp
(remove-hook 'kill-emacs-hook 'w3m-cookie-shutdown)
```

[1] : https://travis-ci.org/nlamirault/scame/jobs/37581655

**Comment by kprav33n** [comment]
Is there any workaround for this issue? I still see this with latest Emacs (24.5.1), Cask (0.7.2), and w3m (20150902.240).

**Comment by nlamirault** [comment]
@kprav33n remove w3m :) and use eww
