### ISSUE TITLE
`EMACS="emacs-24.3" cask` does not work

### ISSUE THREAD

**Issue by abo-abo** [cask/cask#260]
Hi,

I'd like to use Cask to run tests for different Emacs versions.
I'm using currently `25.0.50.1`, but I want to run the tests also for `24.3`.

After calling `cask`, all dependencies are properly installed in
`./.cask/25.0.50.1` and test running works.

Now I want to install the dependencies for `24.3`:

```
EMACS="emacs-24.3" cask
```

I would expect it to create `./.cask/24.3` and install the
dependencies there.  However nothing happens.

**Comment by phillord** [comment]
I've just hit a related problem. Running cask from a command line with "emacs-24.5" works, but running it from Make fails (it just uses the default emacs, which is 24.3 on my ubuntu which is incompatible with my package anyway). The same is true running M-x compile (I've found that EMACS=t strangeness also). Or inside M-x shell.

I am wondering whether there needs to be a way of running Emacs either by name (emacs-24.5) or full path which is not dependent on an env var? Why not 

    cask --emacs=emacs-24.5 exec ert-runner

**Comment by lunaryorn** [comment]
@phillord You need to export `EMACS` to Cask commands in a Makefile, either with `export EMACS` at top-level, or with `EMACS=$(EMACS) cask …` inside rules.

But an option like this would be a good idea, for sure.

**Comment by phillord** [comment]
I tried `EMACS=$(EMACS) cask` in my makefile, with 
`EMACS?= emacs-24.5`. But, I was running this inside M-x compile, so I ended up running `EMACS=t  cask`.

All pretty frustrating. In the end I tried uninstalling my system installed emacs (24.3) but now cask is complaining that it can't find emacs.

I've had related problems with running emacs from git -- I get a different Emacs at commit, from that at the command line.

Anyway, I will leave it there as we seem to be in agreement! Fantastic tool.

**Comment by abo-abo** [comment]
@phillord This works for me:

```
emacs ?= emacs

cask:
	$(shell EMACS=$(emacs) $(CASK) --verbose --debug)
```

**Comment by phillord** [comment]
Hmmm, not sure how "shell" is supposed to help here. Still I tried.

From the command line I get:


    [phillord@hydron:...rd/emacs/lentic]$ make just-test
    .........................  Ran 25 tests in 0.537 seconds
    make: .........................: Command not found
    make: *** [just-test] Error 127

From M-x compile I get:

    -*- mode: compilation; default-directory: "~/emacs/lentic/" -*-
    Compilation started at Sun May 17 13:28:03

    make just-test
    cask load-path: error: Emacs does not exist at emacs.  Did you install Emacs?
    cask path: error: Emacs does not exist at emacs.  Did you install Emacs?
    cask exec: error: [Errno 2] No such file or directory
    make: `just-test' is up to date.

    Compilation finished at Sun May 17 13:28:03

I am not sure I understand the `Command not found` from the command line. But, same make file, same command, different result inside Emacs and outside.

The environment is just not very stable as far as I can see!

**Comment by abo-abo** [comment]
@phillord It should work in emacs-snapshot, that code was updated recently.

See my [Makefile](https://github.com/abo-abo/lispy/blob/master/Makefile) for a different approach that uses `cask` only to install packages, not for `cask exec`.

**Comment by phillord** [comment]
Will try snapshot, but unfortunately I wanted to test in a release version! I may try your lispy makefile, though, as a workaround. Thanks!

**Comment by rejeep** [comment]
I agree that adding a `--emacs` or `--emacs-bin`, etc... would be a good idea. If any of you guys are interested in making a pull request, I would be happy to merge it!

**Comment by phillord** [comment]
Sent my first version of this in.
 
https://github.com/cask/cask/pull/295

Let me know if you want anything adding.
