### ISSUE TITLE
Remove unwanted dependencies

### ISSUE THREAD

**Issue by ffevotte** [cask/cask#264]
I'm using `cask` to manage my `.emacs.d` dependencies, and I often find myself adding a dependency for some time, then removing it (because I don't use it any more). In such cases, `cask update` won't try to update the packages, but they are still left in `.emacs.d/.cask/...`, which clutters the filesystem and slows startup down.

Would it be possible to add a `cask remove` command to clean unwanted packages (recursively with their own dependencies)? Optionally the user would have to confirm the list of packages to be uninstalled to avoid removing packages installed directly using `package-install` outside `cask`'s scope.

Does it make sense in you opinion?

**Comment by anquegi** [comment]
For now it is enough to delete the dependency in the Cask file and the folder inside the .cask folder. isn't it?

**Comment by dickmao** [comment]
As you can see, https://github.com/cask/cask/blob/7ae2d54004b26ebb891f7a011c86cff706acbf1a/cask.el#L743 removals is hardcoded to zero.

I'm afraid there are no plans to make package removal a first-class function.  Generally, I would not recommend cask as a package maintenance tool (i.e., running `cask-initialize` in your .emacs).  It is better as a package development tool.
