### ISSUE TITLE
W3m installation failed

### ISSUE THREAD

**Issue by nlamirault** [cask/cask#270]
hi,
i try to install w3m using Cask : 

```bash
$ cat Cask
(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
;;(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "w3m")
```

I've got this error:

```lisp
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "w3m-cookie")
  w3m-cookie-shutdown()
  kill-emacs(t)
  command-line()
  normal-top-level()
```

The output logs : 
```bash
$ cask install --debug
Making backup-inhibited local to w3m-autoloads.el while let-bound!
Making version-control local to w3m-autoloads.el while let-bound!
Wrote /tmp/foo/.cask/25.0.50.1/elpa/w3m-20141125.1729/w3m-autoloads.el
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "w3m-cookie")
  w3m-cookie-shutdown()
  kill-emacs(t)
  command-line()
  normal-top-level()

Cannot open load file: no such file or directory, w3m-cookie
^CCannot open load file: no such file or directory, w3m-cookie
emacs: Cannot open load file: no such file or directory, w3m-cookie
```

**Comment by nlamirault** [comment]
any idea ?

**Comment by rejeep** [comment]
Hi, sorry about not responding to this, it must have got lost in all noise.

This is an issue with `w3m`, not Cask. You can try it out for yourself. Change the `Cask`-file to:

```lisp
(depends-on "w3m" :git "git@github.com:rejeep/w3m.git" :branch "cask")
```

And then run `cask`. That should work because I did [this change](https://github.com/rejeep/w3m/commit/1dd5308392cd36322783d0307b74f5ebda93db97) in my branch.

Not sure what would happen if we in Cask removed all `kill-emacs-hook`'s.

**Comment by nlamirault** [comment]
Thanks

**Comment by realloc** [comment]
@rejeep, what did you fix in w3m code to make it work with Cask install? I got the same issue, but it seems you have deleted your w3m fork.

**Comment by DarwinAwardWinner** [comment]
I'm seeing the same issue. It's annoying because it causes `cask --install` to hang forever instead of exiting.

**Comment by rejeep** [comment]
This line is the issue: https://github.com/emacsmirror/w3m/blob/master/w3m.el#L3036
