### ISSUE TITLE
generate skeleton for emacs packages

### ISSUE THREAD

**Issue by tonini** [cask/cask#271]
Hi

As already mentioned to @rejeep I really would like to generate emacs package skeleton with cask. For example like bundler does it with [`bundle gem`](http://bundler.io/v1.7/bundle_gem.html) 

There is no standard in the emacs ecosystem about how a emacs package structure should looks like, but there are several things which always mostly the same. 

I just made an example repository https://github.com/tonini/emacs-package-tmpl

![emacs package skeleton example](http://i.imgur.com/pX42Tgt.png)

So what you guys think about it?

**Comment by rejeep** [comment]
I'm not against adding such a command to Cask. But if we do, it should be as minimal as possible. If we add a bootstrap command, it would not be an "Emacs Lisp standard layout", it would be a "Cask standard layout". I think a "convention over configuration" is a good idea here. IMO Emacs needs a bit more structure and standards.

Regarding the test directory, I think that should be a bootstrapper in Ert runner, not Cask.

**Comment by joelmccracken** [comment]
What about adding a test/README file that /suggests/ looking at ert-runner?

It would be amazing if the elisp community started writing more tests.

**Comment by Fuco1** [comment]
I would dump the Makefile and README, but I'd like `.gitignore` with `.cask/*` pre-filled, Cask file can also be created (but there's also `cask init` which does that), the tests... I use buttercup these days as I find it easier to maintain than writing ert tests.  

I use ert-runner though which is excellent for "legacy" packages (smartparens for example).

I also don't like it when I get generated files with content like "<put your package name here>"... it always adds so much noise I keep deleting.

So essentially for me this would just add the `.gitignore` which is probably not worth a feature :D
