### ISSUE TITLE
cask build and load-path 

### ISSUE THREAD

**Issue by politza** [cask/cask#275]
I'd like to compile all lisp files and check for compiler warnings.
But invoking

```
cask build
```

gives lots of `Cannot open load file` warnings, apparently because the
`load-path` does not contain the compiled directory itself.

Is this supposed to be that way ?

**Comment by rejeep** [comment]
Do you have any project where this happens so we can try it out?

**Comment by politza** [comment]
#!/bin/bash

    mkdir -p cask-test/lisp
    cd cask-test

    cat > Cask << EOF
    (package-file "lisp/foo.el")
    (files ("*.el" "lisp/*.el"))
    EOF

    cat > lisp/foo.el <<EOF
    ;;; foo.el --- foo
    ;; Package: foo
    ;; Version: 0.1

    (eval-when-compile
      (message "%s" ">>>")
      (dolist (d load-path)
        (message "%s" d))
      (message "%s" "<<<"))

    (provide 'foo)
    ;;; foo.el ends here
    EOF

    cask build

This lists `$PWD/cask-test` but not `$PWD/lisp/cask-test`.

**Comment by rejeep** [comment]
This is not possible ATM. There is an old issue for this, see https://github.com/cask/cask/issues/129. I fixed it in: https://github.com/cask/cask/pull/276

Can you try out that branch please!?

**Comment by politza** [comment]
Yes, it works. But I think it should be automatically added for this command.

**Comment by rejeep** [comment]
How would Cask know that this should be added? Because of `files`?

**Comment by politza** [comment]
I guess so. Is that not feasible ?

**Comment by rejeep** [comment]
Perhaps it is. Was just thinking out loud on how to solve it.

**Comment by politza** [comment]
Ah. I took it more like a rethorical question.

I think if I tell cask about the files of my project *and* it has a
compile (=build) command, this compilation should just work properly.
But I don't know if it needs such a command in the first place.  What
is the purpose of it ? When does one ever want to compile all lisp
files in the project ? (In my case I wanted to check the compiler
output.)

Maybe It would be more appropriate to view the building of the package
as the build-step and have a command which installs the package in a
batched and possibly sandboxed Emacs in the context of it's
dependencies.  This would also diplay compiler output, but also run
the installation code (if the package needs this).

**Comment by rejeep** [comment]
> I think if I tell cask about the files of my project and it has a compile (=build) command, this compilation should just work properly.

Sounds reasonable.

> What is the purpose of it?

For example run tests on compiled files.

**Comment by Fuco1** [comment]
Fixed in #435
