### ISSUE TITLE
Please make the location of ~/.emacs.d/.cask/ customizable

### ISSUE THREAD

**Issue by tarsius** [cask/cask#278]
I would like to keep `emacs-user-directory` from becoming as messy as `$HOME` where everything just dumps a few files and/or directories at the top-level. I was quite successful at achieving that by teaching every package I use to instead save persistent data in a subdirectory of `~/.emacs.d/var/`.

It seems that this is not possible with Cask. I could not find a way to use a directory different from `~/.emacs.d/.cask/`. Could you please add an option to make this customizable. Thanks.

**Comment by lunaryorn** [comment]
@tarsius How are we supposed to make it “customizable”?  `cask` is a non-interactive tool, so an option in `init.el` will have no effect.

**Comment by rejeep** [comment]
@tarsius If I understand you correctly, you should be able to solve this using [cask-initialize](http://cask.readthedocs.org/en/latest/dev/api.html?highlight=cask-initialize#el.function.cask-initialize) with an argument and use that [--path](http://cask.readthedocs.org/en/latest/guide/usage.html#cmdoption-cask--path) option when "casking".

**Comment by lunaryorn** [comment]
@rejeep Cask will still write to `~/.emacs.d/.cask` for its bootstrapping, though.

**Comment by tarsius** [comment]
A config file just for this non-interactive tool might work, then again someone's not gonna like the location of that... I don't always invoke cask directly, e.g. I might run `make test` in the projectile repository, and then I don't have any control over how it is invoked, so using `--path` isn't really an option either.

Guess I'm just gonna patch it locally.

**Comment by lunaryorn** [comment]
@tarsius Well, we'd have to load that configuration file from somewhere, too, wouldn't we?  So it'd be `~/.emacs.d/.cask` in either way, because that's just about the most suitable place we can possibly find.

**Comment by rejeep** [comment]
@lunaryorn Yeah, true!

**Comment by tarsius** [comment]
> Well, we'd have to load that configuration file from somewhere, too, wouldn't we?

Yes, I came to that conclusion too:

> A config file just for this non-interactive tool might work, then again someone's not gonna like the location of that...

It's really not a big deal, I probably just gonna live with that directory being their.

But in case you are considering providing some "option*: Putting the config file at `$XDG_DATA_HOME/cask` might be an option. Or adding a variable `$CASK_DATADIR` which could be set in the shell's init file.

**Comment by lunaryorn** [comment]
@tarsius I remember that we actually talked about XDG a while back, but we didn't use it, because it's essentially a Linux and a desktop thing, and Cask is neither a Linux program nor a desktop application.  Our OS and desktop is Emacs ;)  

Seriously, though, XDG isn't common on OS X, and `user-emacs-directory` is just much more appropriate for what is essentially just a `emacs -Q --batch` frontend.
