### ISSUE TITLE
Make it possible to easily install bundled packages

### ISSUE THREAD

**Issue by moonlite** [cask/cask#279]
In my .emacs.d/ I have some self-made and some imported packages (none of which are available on MELPA) in `.emacs.d/packages/{pkg-name}/`. 

Now I'd like to use these packages in a package.el integrated way with as little hassle as possible. That means I'd like to get compilation, auto-load-magic and all the other cask/package.el goodies with just a:
```bash
$ cask install && cask update
```

My suggestion is an extension to the (depends-on) function so that I can do something like this:
```el
(depends-on "align-string" :path "packages/align-string/")
```
This would then use the cask-enabled package inside the `packages/align-string` directory.

What do you think?

**Comment by lunaryorn** [comment]
I'm against it. I'd be a lot of code on our side, for a somewhat small use case, that's entirely outside of our core scope, which is installing packages, not building packages—which is what you effectively want.

**Comment by moonlite** [comment]
In the end I managed to hack around it by refering back to my own repo. See [here](https://github.com/moonlite/.emacs.d/blob/003badc072aae0287674d1423e0e65bb9d296d09/Cask#L7).

**Comment by rejeep** [comment]
@moonlite Using `:git` as you did would be my suggestion!

**Comment by moonlite** [comment]
:+1:
