### ISSUE TITLE
cask-source-position-line accessing a non-cask-source-position

### ISSUE THREAD

**Issue by expez** [cask/cask#280]
```
expez on baran in ~/git/evil-smartparens (git)[master|✚1]
$ cask install                                                                                                                         (255)
cask-source-position-line accessing a non-cask-source-position
```

What does this error message mean?  Grepping the source for `accessing` gives no results.  I'm trying to instrument the cask code to figure out what's wrong, but I figure I might as well open an issue in case someone else runs into this.

```elisp
(source melpa)
(source gnu)

(package-file "evil-smartparens.el")

(depends-on "evil")
(depends-on "diminish")
(depends-on "smartparens")
```

From [this](https://github.com/expez/evil-smartparens) github repository.

**Comment by syohex** [comment]
This is caused by https://github.com/expez/evil-smartparens/pull/2
Please check latest version.

**Comment by rejeep** [comment]
@syohex :+1:

**Comment by yyr** [comment]
Offtopic:
Funny that a package to help balance parens has a missing parenthesis.

**Comment by expez** [comment]
Yeah I snickered at that myself :)

**Comment by rejeep** [comment]
Hilarious! :)
