### ISSUE TITLE
Melpa stable packages

### ISSUE THREAD

**Issue by nlamirault** [cask/cask#281]
hi,
my Emacs setup use Cask. I've got this Cask file : 

```lisp
;; Packages repositories
(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa_stable" "http://melpa-stable.milkbox.net/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
;;(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "company" "0.8.10")
```

I install all packages and check outdated packages 

```bash
$ cask install
$ cask outdated
```
I've got no outdated packages. But last stable release for *company* package is 0.8.11. 
Which version of company cask installed ?

**Comment by rejeep** [comment]
Did it work out for you as you closed it?

**Comment by nlamirault** [comment]
Yes. I remove melpa and add only melpa-stable repository. All versions of installed packages are correct
