### ISSUE TITLE
package-build dependency

### ISSUE THREAD

**Issue by nlamirault** [cask/cask#282]
I've got an error installing Pallet [1] using Cask : 

```bash
Dependency pallet failed to install: Package `package-build-0.1' is unavailable
```

According to Melpa, *package-build* is used by Cask [2], but it is not available in Melpa stable [3].

[1] : https://github.com/rdallasgray/pallet
[2] : http://melpa.org/#/package-build
[3] : https://github.com/milkypostman/melpa/issues/2557

**Comment by rejeep** [comment]
`package-build` is not a part of Melpa stable. See https://github.com/cask/cask/issues/272 for more information.
