### ISSUE TITLE
Cannot open cask.el

### ISSUE THREAD

**Issue by nayefc** [cask/cask#283]
Hi,

I installed Cask, created a Cask file and added the following lines to my Emacs:
```emacs
(add-to-list 'load-path "~/.cask/cask.el")
(require 'cask)
(cask-initialize)
```

I then ran cask install but when I start Emacs now, I get:

`File error: Cannot open load file, no such file or directory, cask`.

Is it supposed to write a `cask.el` file to `~/.cask/cask.el`? If not, how is this going to work without an error? Cask has created a `.cask` directory in my `.emacs.d`.

Any ideas what I'm missing? I read the docs and these are the only steps that it mentions.

Thanks

**Comment by syohex** [comment]
> (add-to-list 'load-path "~/.cask/cask.el")

This is wrong because `load-path` is list of directories. So this must be

```lisp
(add-to-list 'load-path "~/.cask/")
```

**Comment by nayefc** [comment]
I tried that, I also get the same error.

**Comment by rejeep** [comment]
Try this (from my config): https://github.com/rejeep/emacs/blob/master/init.el#L9-L10

**Comment by nayefc** [comment]
I did, same error. Tried with and without `cask.el`.

The error makes sense. I do not have a `cask.el` or even a `~/.cask` directory. When does that get created?

**Comment by xuchunyang** [comment]
> I do not have a cask.el or even a ~/.cask directory. When does that get created?

when you installed Cask via https://github.com/cask/cask/blob/master/go

**Comment by nayefc** [comment]
So I do have `~/.cask` apparently. Just no `cask.el`, so the error still makes sense. When is `cask.el` supposed to be created? That's the error for me, my `.cask` directory is empty and Emacs complains of not finding `cask.el` or any Emacs file in there.

**Comment by rejeep** [comment]
If you install via Hombrew, the `cask.el` is someplace else (I suppose, I don't install via Homebrew). Try looking for it in `/usr/local/share/emacs/site-lisp`.

**Comment by nayefc** [comment]
Yup, that was it. This should be added to the instructions perhaps.

**Comment by rejeep** [comment]
@nayefc See https://github.com/cask/cask/commit/90d2657d4452907ee7518cb74a291b37349282e2

**Comment by Jay-Jie** [comment]
@rejeep Thanks.

**Comment by NobbZ** [comment]
Wouldn't the following solution work with `curl | python` and packaged system installations (brew, apt, pacman, etc)?

```el
(add-to-list 'load-path "~/.emacs.d/.cask")
(require 'cask)
(cask-initialize)
```

Its quite verbose, but should work.

Or can't we just throw in a `.cask/cask.el` on `cask install` or `cask update` and keep it up to date through the CLI?
