### ISSUE TITLE
Unhelpful error message with malformed package-requires

### ISSUE THREAD

**Issue by phillord** [cask/cask#284]
Cask produces a very strange error when there is a malformed package-require statement. The
error is as follows: 

     [phillord@hydron:.../src/large/cask]$ cask install
     cask-source-position-line accessing a non-cask-source-position

This is pretty incomprehensible anyway, and is very hard to track down to the source cause -- in this case, I have reproduced it by deleting the last paren from the Package-Requires header in the cask source itself.

It has previously been noted in #280. While in this case, it was caused by evil-smartparens, I have raised a new issue because the error message is so hard to decipher. It's taken me about an hour with a debugger to find a missing paren in the comments of my package!

**Comment by rejeep** [comment]
Can you try out this branch: https://github.com/cask/cask/tree/invalid-package-requires

**Comment by phillord** [comment]
Yes, that is much better and picks up the error in a much cleaner way.

This patch is specific to Package-Requires if I am not wrong? I ask because my natural impulse on getting "Invalidly balanced parens" is to do M-x check-paren, but this will not pick up the error because it is in the comments. 

Would "Unbalanced parens in package headers" or "Unbalanced parens in Package-Requires" not be clearer still?

**Comment by rejeep** [comment]
You are right, this is only a package requires issue. Updated the error message.

I'm thinking, maybe EPL should handle this error instead? What do you think @lunaryorn?

**Comment by lunaryorn** [comment]
@rejeep I didn't follow this issue, so please forgive me if I'm wrong or saying anything that was already said, or is just plain stupid.

The real issue in this case was a malformed package, wasn't it?  E.g. invalid package headers or something like that?  In this case, yes, EPL should catch the error and transform it into a proper message, i.e. `epl-invalid-package` or something, that wraps the original error.

**Comment by rejeep** [comment]
@lunaryorn You are correct! I opened up this issue: https://github.com/cask/epl/issues/28

**Comment by rejeep** [comment]
Merged, thanks for the help on EPL @lunaryorn and on reporting this issue @phillord!
