### ISSUE TITLE
Overriding cask-elpa-path (or help me fix my setup)

### ISSUE THREAD

**Issue by fjl** [cask/cask#287]
I use Cask to manage my emacs configuration, although maybe in a slightly unusual way. My config (which I cannot link to right now) lives inside a Git repository which contains the source code of all dependency packages committed alongside the initialization files. Basically most of `.cask` is version controlled. This setup provides several advantages for me and I'd like to keep it in some form. Cask supports this use case very well, except for a tiny wrinkle:

When using the setup on multiple machines, I do not have the same version of emacs installed on all of them. Unfortunately, Cask puts package files under `.cask/<version>/elpa`. In order to get around this limitation, my initialization overrides the `cask-elpa-path` function like this:

```elisp
(let* ((casks   (directory-files (concat +fjl-init+ "/.cask/elpa") t "^cask-"))
       (cask.el (concat (car casks) "/cask.el")))
  (require 'cask cask.el)
  ;; override cask internals to get rid of versioned elpa directories.
  (fset 'cask-elpa-path (lambda (bundle) (concat (cask-bundle-path bundle) "/.cask/elpa"))))
```

There are two issues with this setup:
- It makes the `cask` command line tool useless, because that still uses the versioned directory.
- When loading Cask for the first time, it seems to reinstall its dependencies even though they are already there.

A possible solution would be to allow disabling the directory version in the `Cask` file. 
Do you like this idea? I can submit a PR for it but wanted to discuss first.

**Comment by rejeep** [comment]
Hi,

I don't see the reason for your approach? Byte compiled files are not guaranteed to be working across different versions of Emacs, hence one directory per version.

Can you please explain why you want this setup?

**Comment by fjl** [comment]
I do not commit the byte-compiled files into the repo and compile the files on each machine with the version of emacs that is installed there.

This way of keeping the config is useful because it allows me to hot-patch packages temporarily if they don't work the way I want. It's also easier to get started in a new (virtual) machine because I can just clone the config and lanch emacs without waiting for dependency installation.

I usually upgrade everything once per month and commit the entire upgrade. If there are problems (and this happens because I use the bleeding-edge version of everything) I fix them and commit the temporary fixes. With all packages checked into the repo, I can pull the upgrade (and the fixes) on other machines and they just work.

Are you conviced yet?

**Comment by lunaryorn** [comment]
I'm not.  I don't think that it's a workflow that cask should support, and
I don't think that cask is the right tool for this workflow.

 For instance if you commit your packages the Cask file serves no real use
anymore at all.  I don't think that Cask simplifies your workflow, on the
contrary, it makes it more complicated.

Since your workflow us so different from what Cask does currently, I think
you are better off with a custom Emacs Lisp script that handles package
updates for you.

>

**Comment by fjl** [comment]
> For instance if you commit your packages the Cask file serves no real use
> anymore at all.  I don't think that Cask simplifies your workflow, on the
> contrary, it makes it more complicated.

It simplifies my workflow a lot! I have a Cask file with a bunch of packages in it and it downloads the packages from their Git repos and from Melpa, including dependencies. I don't want to build that myself.

The solution I proposed is to support something like the following stanza in the Cask file:
```elisp
(elpa-path ".cask/elpa")

(source gnu)
(source melpa)
(depends-on "ace-jump-mode")
```

**Comment by lunaryorn** [comment]
> For instance if you commit your packages the Cask file serves no real use
> anymore at all. I don't think that Cask simplifies your workflow, on the
> contrary, it makes it more complicated.
>
> It simplifies my workflow a lot! I have a Cask file with a bunch of
> packages in it and it downloads the packages from their Git repos and from
> Melpa, including dependencies. I don't want to build that myself.
>
Well, it's about ten lines of code if at all, but you don't even have to.

Since you commit the packages you can just use the standard package menu to
install and update packages, and track them in Git across all your
installations.  If you install and commit a package on another system,
package.el will automatically pick it up on all other system after the next
pull.

I see no reason why you'd need to use Cask for this purpose.

> The solution I proposed is to support something like the following stanza
> in the Cask file:
>
> (elpa-path ".cask/elpa")
>
> (source gnu)
> (source melpa)
> (depends-on "ace-jump-mode")
>
> What you propose is what we'd have to implement and maintain.  Personally
I don't consider this feature sufficiently important to spend my time on it.

>

**Comment by fjl** [comment]
Alright then. I'll do it myself. Thank you for taking the time to consider my feature request.�

**Comment by rejeep** [comment]
You might also want to take a look at Cask's [fetcher functionality](http://cask.readthedocs.org/en/latest/guide/dsl.html?highlight=fetcher#el.function.depends-on):

```lisp
(depends-on "foo" :git "git@git.com/foo.git" :ref "abcd")
...
```

That way you will always get a version of each package you know is working. Emacsmirror should have all packages you want.
