### ISSUE TITLE
Generate pkg-file before packaging

### ISSUE THREAD

**Issue by lunaryorn** [cask/cask#289]
Cask needs to run `cask pkg-file` before `cask package`, to make sure that the generated tarball includes all dependencies from the Cask file.  See #288 

/cc @rejeep

**Comment by lxsameer** [comment]
Also your `cask pkg-file` generate the pkg file with wrong dependencies format.

**Comment by lunaryorn** [comment]
@lxsameer In how far is the package descriptor generated by `cask pkg-file` invalid?

**Comment by lxsameer** [comment]
`pkg-file` generate `nil` as the version for dependencies without any version specified which according to `Emacs` docs are wrong. I fixed it in the provided pull request.

**Comment by lunaryorn** [comment]
@lxsameer I see the bug, but I doubt that your fix is the right one.  I'd like to see documentation which states that we should fall back to 0.  As far as I can see, the minimum version is mandatory in `Package-Requires:`.

**Comment by lxsameer** [comment]
I'm sure about it but If you think it's not correct please refer to `define-package` definition in `package.el`. If you don't define the version ( which should be string as said in Emacs define-package docs ) the `version-to-list` can not parse it. 

Later in that function you can see the it simply check the package versions. "0" is the smallest value.

**Comment by lunaryorn** [comment]
@lxsameer Indeed, you are right.  package.el really falls back to `0` for unspecified versions.

**Comment by lxsameer** [comment]
@lunaryorn also `cask` does not include dependencies on single packages too.

**Comment by lxsameer** [comment]
It seems that this issue comes from `package-build` because appereantly they do not check `-pkg.el` file for single package ( because they assume that developer will manually enter the dependencies in single package ) and by convention there is no need for `pkg` files for a single package.

And `package-build` does not provide a way to override this.

**Comment by lunaryorn** [comment]
I'm sorry but I can't follow you.  There's no package descriptor for single
file packages, so what exactly is the issue here?

Am Sonntag, 5. April 2015 schrieb Sameer Rahmani :

**Comment by lxsameer** [comment]
@lunaryorn forget about it. I forgot about `package-file` DSL and how it extract meta data from another file rather than `Cask`.

**Comment by rejeep** [comment]
@lunaryorn Sorry, missed this somehow. It seems that the simplest way to do this would be to simply call `cask-cli/pkg-file` first in `cask-cli/package`. I think testing this would be a bit overkill as we would have to unzip the file and inspect the directory.
