### ISSUE TITLE
bootstrapping cask failed

### ISSUE THREAD

**Issue by expez** [cask/cask#293]
For some reason the builds for `evils-smartparens` started failing with: 
```
The command "curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh" failed and exited with 1 during .
```

Here's the offending [.travis.yml](https://github.com/expez/evil-smartparens/blob/master/.travis.yml)

**Comment by rejeep** [comment]
Hmm, I see this output in your Travis run: `sudo: must be setuid root`. No idea what that's all about.

**Comment by rejeep** [comment]
Check this out: http://stackoverflow.com/questions/26299552/travis-sudo-is-disabled

**Comment by rejeep** [comment]
Not sure why it would stop working now though?

**Comment by lunaryorn** [comment]
@expez You need to update your Travis CI configuration, because Travis CI moved their default build setup to a new infrastructure.  See http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/ for more information.

Closing, because it's not really an issue in Cask.

**Comment by lunaryorn** [comment]
@expez I'm not sure, actually, why you opened this issue here.  It doesn't seem to be related to Cask at all…

**Comment by expez** [comment]
I opened the issue here because the travis console displayed this:

```
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
```

The travis failure gives absolutely no indication as to what was wrong so I didn't really know where to start.  

Sorry for the noise.

**Comment by lunaryorn** [comment]
@expez I see.  I think the actual failure is that Cask couldn't find any Emacs, because EVM bootstrapping failed.  We should improve the error message here.
