### ISSUE TITLE
local package fetcher

### ISSUE THREAD

**Issue by lxsameer** [cask/cask#294]
What do you think about adding a new package fetcher called `:path` or `:local` which allows to specify packages via FS path. Just like how `path` argument of `gem` method in **Ruby Bundler** works ?

This way developers can develop their package easily.

//cc @rejeep

**Comment by lunaryorn** [comment]
Are you aware of cask link?

Am Freitag, 15. Mai 2015 schrieb Sameer Rahmani :

**Comment by lxsameer** [comment]
@lunaryorn yeah 
But this solution would be easier to use and understand, isn't it

**Comment by lunaryorn** [comment]
@rejeep I don't think so, but I have no preferences either.  But we should have only one such option in Cask.

**Comment by lxsameer** [comment]
@lunaryorn hmm dude `path` as parameter for gem method in **ruby bundler** is a case which shows us this feature is a lot easier to use and maintain. 

For example if you want to develop a library which has dependency to two or more library that you're developing, using links can be a pain. But this you just add a path param to your `depends-on`. also you can do it only in development and the runtime dependency fetch the package from non-local location.

**Comment by rejeep** [comment]
Using a `path` param, you would have to modify the `Cask`-file, which is a part of your project with a local path, specific to only your computer. Links does not affect anything in the repository.

> For example if you want to develop a library which has dependency to two or more library that you're developing, using links can be a pain.

How? I have tons of these and links works great for me.

**Comment by lxsameer** [comment]
ok then. thanks
