### ISSUE TITLE
Travis builds are failing and are missing Python 3 support

### ISSUE THREAD

**Issue by Ecno92** [cask/cask#298]
As you can see at https://travis-ci.org/cask/cask/ nearly all builds are failing. Including the master. 
I saw this in my PR and it would be nice to have this fixed.

It's also a good idea to add a testing environment with Python 3. This makes it easier to maintain Cask for both Python versions.

**Comment by rejeep** [comment]
I know, it's awful, just haven't gotten around to fixing it. I will, someday, but recently I've had no time to work with my open source projects. You are welcome to fix it yourself. Otherwise wait until I get some time. We can leave this issue open as a reminder.

**Comment by conao3** [comment]
Now we moved Python3. This issue seems outdated. Closing for now, but please feel free to reopen this issue.
