### ISSUE TITLE
Please make `cask` a Python package

### ISSUE THREAD

**Issue by egarrulo** [cask/cask#301]
Installation and upgrading would be easier if `cask` where a Python package, as everything would be handled by `pip`.

Thanks for your attention.

**Comment by lunaryorn** [comment]
How is `pip` easier than cloning a Git repository?

**Comment by rejeep** [comment]
It's available via Homebrew if you are on a Mac. The problem with adding Cask to package managers is that for each version, all package managers must be updated with the new version.

**Comment by egarrulo** [comment]
OK.  More than a wish, this was a suggestion really.  I saw that `go` made some checks and asked the user to modify her `PATH`.  These things would be handled by `pip`. But if using `pip` is not worthwhile, never mind.

**Comment by lunaryorn** [comment]
@egarrulo `pip` itself normally needs to be installed explicitly first, which is a larger obstacle than `git` given that almost all developers nowadays use `git` in one way or another, but probably only a small part of all Emacs package developers also writes Python and has the corresponding toolchain including `pip` available on their systems.

Closing as `wontfix`.

**Comment by egarrulo** [comment]
Therefore you can install Cask by just downloading it with Git?  The README doesn't mention this, therefore I didn't think that it was possible.

**Comment by lunaryorn** [comment]
@egarrulo I'm not sure what you're referring to… the README tells you to use our `go` script, which—as you can easily see in its source code—does little more than `git clone … ~/.cask; ~/.cask/bin/cask upgrade-cask`.  

But yes, aside of `emacs`, `git` is the only non-standard dependency of Cask.
