### ISSUE TITLE
cask version returns nothing

### ISSUE THREAD

**Issue by tejasbubane** [cask/cask#302]
Here is a series of commands I used:
```
⇒  cask version

⇒  which cask
/home/tejas/.cask/bin/cask
⇒  emacs --version
emacsclient 24.5
⇒  cask upgrade-cask
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:80
Contacting host: melpa.org:80
Contacting host: elpa.gnu.org:80
Contacting host: elpa.gnu.org:80
⇒  cask version

⇒  
```

Am I missing something here?
`cask update` seems to work fine, updates all packages. `cask upgrade-cask` as shown above doesn't seem to do any upgrade.

**Comment by rejeep** [comment]
The command `cask version` is for printing the version of the current package. Is that what you want? If you want to print the Cask version, use `cask --version`.

**Comment by tejasbubane** [comment]
Ahh, sorry. My bad. Was reading through [these docs](http://cask.readthedocs.org/en/latest/guide/usage.html#cask-version) which led to the misunderstanding. Closing the issue.

**Comment by rejeep** [comment]
No worries, not the best docs for that command.
