### ISSUE TITLE
Customize relative location of lisp files

### ISSUE THREAD

**Issue by dunn** [cask/cask#305]
Over at Homebrew I'm trying to standardize how it installs emacs packages: https://github.com/Homebrew/homebrew/issues/41388  The idea is to have package-specific directories for lisp files instead of dumping them all into a shared `site-lisp` like we do currently.

Right now Cask requires that `cask.el` etc. be in the parent directory of `bin/cask`.  The [current workaround](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cask.rb) for that is installing the lisp files into the formula prefix then symlinking them into `site-lisp`, but is is possible to make `CASK_DIRECTORY` customizable?  Right now `make all` just runs tests; maybe it could be used instead for customizing some variables.

**Comment by rejeep** [comment]
Sorry, but I'm not sure what you are asking here? Can you please explain in more detail what kind of changes you want in Cask!?

**Comment by dunn** [comment]
I guess I'm wondering if it would be possible to make [line 45 of `bin/cask`](https://github.com/cask/cask/blob/master/bin/cask#L45) a variable that can be set at build-time, instead of being hard-coded as the parent directory: `CASK_DIRECTORY = os.path.dirname(CASK_BIN_DIRECTORY)`

**Comment by lunaryorn** [comment]
Well, we have no build step which makes this kind of difficult you know 😉

**Comment by dunn** [comment]
Yeah, I figured this was a pretty demanding request :grimacing:. If it's not worth the effort I understand!

**Comment by lunaryorn** [comment]
@dunn Well, I'm wary to add a real build step just to support a single package manager, albeit a popular one.  And in the end, there's no difference whether we patch the file in a build step or whether homebrew patches it in its formula, from my point of view.   YMMV, of course, but the less work for us, the better 😜

**Comment by lunaryorn** [comment]
@dunn But of course, if it's altogether impossible to handle this situation in the Homebrew formula, we're open to a build step, I guess, but even in this case I'd prefer to have a PR over doing it myself 😀

**Comment by dunn** [comment]
It would be possible to patch it in Homebrew, but they don't like floating patches so if I whip something up I'll open a PR here.  Thanks again!

**Comment by rejeep** [comment]
Closing this!
