### ISSUE TITLE
Lisp error: (file-error "Cannot open load file" "no such file or directory" "cask-cli") for Mathematica, DLang files

### ISSUE THREAD

**Issue by mcandre** [cask/cask#308]
When I try to open Mathematica .ma or DLang .d files in Emacs, I get an error:

```
Debugger entered—Lisp error: (file-error "Cannot open load file" "no such file or directory" "cask-cli")
```

Config:

https://github.com/mcandre/dotfiles/blob/6e669baf064803339f434e30e61ef97f8d1d315d/.emacs

https://github.com/mcandre/dotfiles/blob/6e669baf064803339f434e30e61ef97f8d1d315d/Cask

Emacs is able to open other filetypes without issue. I wonder if Emacs Cask is somehow incompatible with these specific modes?
- Emacs v24
- Mac OS X 10.10.3

**Comment by rejeep** [comment]
Should work fine. I would recommend you to remove Cask in `~/.emacs.d/.cask/...` and run `cask` again.
