### ISSUE TITLE
Wrong error message: "Unbalanced parens in Package-Requires"

### ISSUE THREAD

**Issue by malthe** [cask/cask#311]
If a Cask-file does not end in ``;;; <filename>.el ends here`` then the error message "Unbalanced parens in Package-Requires" is shown – even if this header is not present in the file.

**Comment by rejeep** [comment]
What do you mean with a Cask-file? A [Cask-file](http://cask.readthedocs.org/en/latest/guide/dsl.html) should never include that line. Can you please clarify the issue.

**Comment by malthe** [comment]
Sorry, I meant the `.el` file.

**Comment by rejeep** [comment]
What command are you running to see the error? I removed that line on one of my projects and ran `cask` and it works fine.

**Comment by malthe** [comment]
I run simply:
```bash
$ cask
```
If I remove the final ``;;; <name>.el ends here`` then it fails with:
```
Unbalanced parens in Package-Requires in file <name>.el
```

**Comment by lunaryorn** [comment]
@malthe Your Cask file?

**Comment by malthe** [comment]
```
(source gnu)
(source melpa)

(package-file "<name>.el")

(files "*.el")

(development
 (depends-on "ert-runner"))
```

**Comment by syohex** [comment]
This issue can be reproduced by following steps.

```
% git clone https://github.com/cask/cask
% cd cask
% emacs Cask # remove final line
% cask
Unbalanced parens in Package-Requires in file cask.el
```

`cask.el` always show `Unbalanced parens in Package-Requires in file` even if unrelated error is raised at following line.

https://github.com/cask/cask/blob/70d73d8d3f6ca3fc42d58ecd0e1eb87df3a07fff/cask.el#L384

I suppose `cask` should change error message by error type.

**Comment by rejeep** [comment]
@syohex  Just noticed that as well. EPL includes the actual error message. @malthe Can you modify the line linked above in your local Cask installation and print the `err` variable.

**Comment by malthe** [comment]
``epl-invalid-package-file <path>/<name>.el ;;; <name>.el ends here)``

**Comment by rejeep** [comment]
@syohex Is your way of reproducing this really the same as @malthe describes? I can still not reproduce this. @malthe one way of describing the behaviour is to write a failing [feature](https://github.com/cask/cask/tree/master/features).

**Comment by malthe** [comment]
okay I'll try if I get the time ... already digged myself deep into a hole trying to write a new editing mode :-)

**Comment by rejeep** [comment]
Ok, talk to you later then, good luck with your mode! :smile:

**Comment by cowboyd** [comment]
I ran into this when I was trying to create a new package. You have a package file that is invalid in *any* way, and you get "Unbalanced parens in Package-Requires in file <name>.el". In my case, the `Author` field was malformed, and it correctly reported the error, but incorrectly reported the message which was very confusing.

**Comment by rejeep** [comment]
Closing this in favour of https://github.com/cask/cask/pull/315
