### ISSUE TITLE
Source file newer than byte-compiled file when updating packages

### ISSUE THREAD

**Issue by nayefc** [cask/cask#314]
When I updated my packages, some of my `.elc` files did not recompile and throw a `Source file newer than byte-compiled file when updating packages`. 

I ran `cask clean-elc`, and then ran `cask build` but the `build` throws the same error. Same thing for `update`. The only way I got it to work is delete the `.elc` files from `.cask/` manually, and byte compile them manually in Emacs.

Any idea why this happens? I also ran the update from Emacs `packages-list-packages` initially, but shouldn't Cask sync those automatically? Doesn't Emacs use `.cask` in either case?

**Comment by rejeep** [comment]
> some of my .elc files did not recompile

Do you mean your project `.elc` files or the ones in `.cask`?

The commands `clean-elc` and `build` only affects the projects `.elc` files. And the command `update` only affects the ones in `.cask`. So those commands are not really related.

> Shouldn't Cask sync those automatically? Doesn't Emacs use .cask in either case?

You must include `cask` in your Emacs configuration in such case. Check the variable `package-user-dir`, which decides were the packages will end up.
