### ISSUE TITLE
cask install error: Emacs does not exist at ...

### ISSUE THREAD

**Issue by sshaw** [cask/cask#316]
```
cask install --path ~/.emacs.d
cask install: error: Emacs does not exist at /Applications/Emacs.app/Contents/MacOS/Emacs.  Did you install Emacs?
~/elisp/emacs.d >ll /Applications/Emacs.app/Contents/MacOS/Emacs
-rwxr-xr-x@ 1 sshaw  admin   709B Feb 10  2013 /Applications/Emacs.app/Contents/MacOS/Emacs*
```

**Comment by syohex** [comment]
Could you show me output of `/Applications/Emacs.app/Contents/MacOS/Emacs --version` ?

**Comment by sshaw** [comment]
`Emacs` us a ruby script that requires `/usr/bin/ruby`. That was missing. 

Obviously a rare edge case so maybe the bug is to check the return value of the `exec` call for `127`; or something...

**Comment by joelmccracken** [comment]
so you don't have ruby?

**Comment by syohex** [comment]
Cask expects `/Applications/Emacs.app/Contents/MacOS/Emacs --version` success and it returns version number If the command is failed and errno is ENOENT, Cask raises error and display `Emacs does not exist at /Applications/Emacs.app/Contents/MacOS/Emacs`.

**Comment by sshaw** [comment]
> so you don't have ruby?

I do, it just wasn't there.

> ... If the command is failed and errno is ENOENT...

Looking at the docs I see that `subprocess.Popen` is more or less like `EXECVE(2)`, which does not takes the extra steps that say Bash would to determine why command execution failed (e.g., exit code `127` vs `126). 

Closing.

**Comment by sshaw** [comment]
Though maybe change the error message to `Emacs cannot be excuted ...`  as it covers all cases.

**Comment by lunaryorn** [comment]
@sshaw I don't think that we'll try to work around a corner case issue caused by a missing part of the core system.  You _definitely_ should have `/usr/bin/ruby`.
