### ISSUE TITLE
cannot install cask - error with emacs version 

### ISSUE THREAD

**Issue by sariya** [cask/cask#317]
Hi There,
Thanks for cask repository. I need cask to install auto-complete in emacs.
I follow instructions, and hit:

`curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python`

After few seconds, I get an error for emacs version:
`cask upgrade-cask: error: Emacs 24 required, yours is Emacs 23.1.1.`

I'm on a cluster, and have no idea how can I upgrade my emacs. Is there any cask repository which supports older emacs?
Until this is being solved, no auto-complete installation would proceed.

Thanks,
Sariya

**Comment by lunaryorn** [comment]
@sariya Probably v0.5 or earlier, I don't know exactly when we dropped Emacs 23 support.

Closing as `wontfix`.  We'll not add Emacs 23 support back.  This version is over three years old and lacks the entire infrastructure and libraries needed to support Cask.  With a version as old as this, you're own your own, I'm afraid.  I'm sorry.

**Comment by rejeep** [comment]
@sariya Do you use 23 for any particular reason? I mean, why don't you just upgrade?

**Comment by sariya** [comment]
@rejeep  It's there because the admins have set up HPC cluster that way. :( 
@lunaryorn  - Alright. 
Thanks for your replies.
