### ISSUE TITLE
Feature Discussion: Plugin System

### ISSUE THREAD

**Issue by AdrieanKhisbe** [cask/cask#321]
Few months ago in order to automate my emacs-packages I end up building [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el).

It's a tool to help setup continous integration for an emacs project, relying on cask, evm, ert, ecukes, undercover, travis and some other cool stuff.

So far, it has to be added as a development dependancy to `Cask`, installed and be invoked with `cask exec package-toolset status`. 
_As this is not the best developper experience, I was considering it could be a good idea to integrate as a *plugin to cask_, and so to build **an extensible plugin system** for Cask so it becomes easy to  to add arbitrary commands to bundler itself (like your bundle license command)*
(similar way that the heroku or [bundler allow plugins](https://github.com/bundler/bundler/issues/1945))

I suggested the idea to @rejeep, that said it was a rather food idea that should be discussed on the repo.

_So what you think about this? =)_
Any suggestion about the feature, and it's possible implementation is very much welcome!!

**Comment by lunaryorn** [comment]
@AdrieanKhisbe I like the idea, but it's a major task to implement that, and I for my part have no time for this.

**Comment by rejeep** [comment]
Yes, this is a good idea, but like @lunaryorn says, quite a major change and my time is very limited as well.

I would suggest as a first step to write a spec for exactly what should be possible to extend. Write a list of use cases; how it works now and how a plugin system would solve it.

**Comment by AdrieanKhisbe** [comment]
Indeed that's a major change, I won't deny :)

I'll try to draft something in the days to come.

**Comment by conao3** [comment]
Sorry, `cask` is now shrinking state and this kind of feature request is heavy.
Closing for now, but any contribution on it is welcome anytime.
