### ISSUE TITLE
new release for brew

### ISSUE THREAD

**Issue by dpsutton** [cask/cask#325]
It looks like homebrew has an old version of cask. 
`dan@bigmac resize-window$ ls -l $(which cask)
lrwxr-xr-x  1 dan  admin    29B Nov 22 11:57 /usr/local/bin/cask@ -> ../Cellar/cask/0.7.3/bin/cask`

From the releases you have, 0.7.3 is from March 27, and this does not include the nice error messages, but instead always reports 
`Unbalanced parens in Package-Requires in file <filename>.el`

Is there a way to update the homebrew version easily?

**Comment by rejeep** [comment]
The Cask formula in Brew is not officially supported by the maintainers of Cask. I would suggest that you ping the people that have done commits on that formula and ask them. I actually have no idea how that works as I'm always using master from Git.

**Comment by lunaryorn** [comment]
@rejeep I think the OP asked whether _we_ could make a new release, e.g. 0.7.4

**Comment by rejeep** [comment]
@lunaryorn Maybe... not quite clear. Pushed the `v0.7.4` tag.
