### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#327]
Hi there,

I'm trying to use Cask with company-coq; I used to have a company-coq-pkg.el, but it looks like Cask will generate it for me. Neat :)

When trying to set Cask up, however, I ran into a number of issues:

``` bash
$ cask install
Unbalanced parens in Package-Requires in file company-coq.el
```

Turned out this was due to 

``` elisp
                  (condition-case err
                      (epl-package-from-file
                       (f-expand filename (cask-bundle-path bundle)))
                    (epl-invalid-package
                     (error "Unbalanced parens in Package-Requires in file %s" filename)))))
```

But the real issue was that I didn't have a `version` header. I found out by running `epl-package-from-buffer` in the right buffer.

The I ran into this:

``` elisp
$ cask install
Wrong type argument: stringp, cl-lib
```

I tried to understand what was going on, but edebug doesn't like `cask--eval` :/ I tried with debug, but the expansion of the various macros made things hard to read. After a while I diffed my Cask file against the default and realized I was missing quotes around package names in `depends-on` formas. I was surprised by this, because the Package-Requires header in Emacs doesn't require quotes. Maybe Cask could accept both syntaxes?

Everything is running smoothly now, so these are just minor suggestions! Thanks for Cask :)

**Comment by lunaryorn** [comment]
@cpitclaudel What Emacs version are you on?  The package.el error reporting is very version dependent due to changes in package.el during various Emacs 24 releases.

**Comment by cpitclaudel** [comment]
I'm on 25.0.90 (sorry for missing your reply!)

**Comment by Fuco1** [comment]
I think we could make a flycheck extension for the cask dsl to catch syntax errors like this, what do you think @cpitclaudel ?

We could also add some validation of the generated files for sure.  I'll try to split this into some actionable subtasks.
