### ISSUE TITLE
cask pkg-file shouldn't reorder dependencies

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#328]
`cask pkg-file` currently prints dependencies in reverse order (compared to the Package-Requires header). This can cause installation to fail on old emacsen (see https://github.com/milkypostman/melpa/issues/2744 for some context), so it would be great to respect the Package-Requires order :)

**Comment by rejeep** [comment]
Pull request?

**Comment by lunaryorn** [comment]
@cpitclaudel I guess there's an `nreverse` missing somewhere.  I for my part won't fix that any time soon though, because I'm not personally affected by it (I don't use older Emacsen), and there's more than enough work for me on the [Flycheck backlog](https://waffle.io/flycheck/flycheck) :blush:

**Comment by cpitclaudel** [comment]
Happy to provide a patch. Looking at the code indicates two possible approaches:

* `reverse`ing in `cask--runtime-dependencies` and `cask-development-dependencies`
* Using `-snoc` instead of `push` in `cask-add-dependency`.

Does anyone have a preference for either option?

**Comment by lunaryorn** [comment]
@cpitclaudel I would prefer the first one; it should be faster, because it only traverse `once`, whereas `-snoc` as to traverse for every single addition.

**Comment by cpitclaudel** [comment]
Ok, I have a rough draft of this :)
