### ISSUE TITLE
Can Cask run Emacs?

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#329]
I find the sandbox target of MELPA's makefile extremely useful. Does Cask provide something similar? The idea is to manually (interactively) test my package in an emacs -Q with just the right packages loaded. I tried the following make rule to no avail:

```bash
sandbox:
	cask exec $(EMACS) -Q \
		--eval '(setq user-emacs-directory "sandbox")' \
		-l package --eval '(progn (package-initialize) (package-install-file "dist/company-coq-$(shell cask version).tar"))'
```

**Comment by rejeep** [comment]
Why not just `cask exec emacs -Q -l your-package.el`?

**Comment by cpitclaudel** [comment]
@rejeep I'm interested in testing package installation, automatic byte-compilation, and autoloads; the way the package manager would do them if downloading the package from MELPA.

**Comment by lunaryorn** [comment]
I don't think that this kind of sandboxing is Cask's job.  In any case, I'm not sure what this target is supposed to do. 

If you want to test compilation then compile your files; if you want to test autoloads then generate them.  If you want to test whether your package installs from MELPA, then install it from MELPA (in an Emacs -Q session or with a custom init file if you want…).

But you shouldn't try and  test package.el itself imho.

**Comment by cpitclaudel** [comment]
Got it :) Thanks for the clarification!
