### ISSUE TITLE
Quick question about tests

### ISSUE THREAD

**Issue by seanirby** [cask/cask#331]
Sorry for posting this in the issue tracker but I couldn't find a more relevant place.

So I've just setup cask for the following package I'm building:
https://github.com/seanirby/evalator

To get the tests working I had to add a ```.ert-runner``` file that loads all the project files in the root directory before running the tests.  That seems a little odd to me because I already declared in the Cask file what my project files are so why should I have to tell the test runner to load these files?  I assumed they would be loaded by default.  Is this expected behavior?

**Comment by rejeep** [comment]
It is expected. The `cask exec` command will only set up the `load-path` for you and does not use what you specify in `files`, which currently is used for compiling files and building packages.

The `cask exec` command never gets that far, it's done completely in the Python script, so "Cask" has not really been loaded when running this command.

**Comment by seanirby** [comment]
OK just wanted to make sure.  Thanks for the response and for making such an great tool.
