### ISSUE TITLE
Install hangs on windows when contacting elpa.gnu.org

### ISSUE THREAD

**Issue by maacl** [cask/cask#332]
When running:

`curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python`

the process hangs at:

`Contacting host: elpa.gnu.org:80`

**Comment by rejeep** [comment]
Do you eventually get _"Failed to download `gnu' archive."_?

**Comment by maacl** [comment]
Depends what eventually means. I let it run for at least 10 min without a
result.

**Comment by rejeep** [comment]
I was referring to an error I've encountered with the gnu archive, but it's not this.

Cask should be cloned to `~/.cask`. Can you enter that directory and run `cask upgrade-cask --debug`. If that doesn't give any more information, please add some debug print statements to https://github.com/cask/cask/blob/master/cask-bootstrap.el

**Comment by maacl** [comment]
I will test next time I am unfortunate enough to have to use Windows :-)

**Comment by kostajh** [comment]
Here's the error I'm getting when I try to install, this is on Linux. Related?
```
[kosta@kafes]$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into '/home/kosta/.cask'...
remote: Counting objects: 3285, done.
remote: Total 3285 (delta 0), reused 0 (delta 0), pack-reused 3285
Receiving objects: 100% (3285/3285), 1.03 MiB | 858.00 KiB/s, done.
Resolving deltas: 100% (1845/1845), done.
Checking connectivity... done.
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
gnutls.c: [0] (Emacs) fatal error: Error in the pull function.
gnutls.el: (err=[-54] Error in the pull function.) boot: (:priority NORMAL :hostname elpa.gnu.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/pki/tls/certs/ca-bundle.crt
) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)                                                                                              
Failed to download `gnu' archive.
Contacting host: melpa.org:443
https://melpa.org/packages/s-20160115.58.el: Bad Request
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
```

**Comment by rejeep** [comment]
Don't think so. That's a weird error.

**Comment by dickmao** [comment]
> Depends what eventually means. I let it run for at least 10 min without a result.

^_^ good one.  Please reopen if this remains an issue.  GnuTLS (and security generally) can be inscrutable.
