### ISSUE TITLE
Cannot install packages via git.

### ISSUE THREAD

**Issue by tvaughan** [cask/cask#333]
This has been working for quite some time. All of the sudden it stopped working today. This is with cask 0.7.4 installed via homebrew. I do run `brew update` a lot, but I'm not aware of anything that may have changed that would be related.

A Cask file like:

    (depends-on "ido-at-point" :git "https://github.com/katspaugh/ido-at-point")

yields:

    Dependency ido-at-point failed to install: Command '(env LC_ALL=C /usr/local/opt/coreutils/libexec/gnubin/timeout -k 60 600 git remote show -n origin)' exited with non-zero status 128: fatal: Not a git repository (or any of the parent directories): .git

    Output:

I've tried other packages on github, and they all fail in the same way. Thanks.

**Comment by rejeep** [comment]
Hmm, works for me. Can you try and clone the repo manually and run the failing command:

```
$ env LC_ALL=C /usr/local/opt/coreutils/libexec/gnubin/timeout -k 60 600 git remote show -n origin
```

**Comment by tvaughan** [comment]
All good:

    [tvaughan:/tmp/cask] master ¬± 
    $ env LC_ALL=C /usr/local/opt/coreutils/libexec/gnubin/timeout -k 60 600 git remote show -n origin
    * remote origin
      Fetch URL: git@github.com:cask/cask.git
      Push  URL: git@github.com:cask/cask.git
      HEAD branch: (not queried)
      Remote branches: (status not queried)
        fix-failing-upgrade
        load-path-option
        master
      Local branch configured for 'git pull':
        master merges with remote master
      Local ref configured for 'git push' (status not queried):
        (matching) pushes to (matching)
    [tvaughan:/tmp/cask] master ¬± 
    $ git ll | head -1
    acd1928 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #324 from hrs/master

**Comment by rejeep** [comment]
That error is shown when you run a Git-command, such as `env LC_ALL=C /usr/local/opt/coreutils/libexec/gnubin/timeout -k 60 600 git remote show -n origin` when not in the directory. Try running that in a non Git-directory and you'll see the same error.

Cask is using [package-build.el](https://github.com/melpa/melpa/blob/master/package-build.el) to build those packages, so a bad update there can unfortunately break cask.

It's used [here](https://github.com/cask/cask/blob/master/cask.el#L323), so try to do some debugging around this and the function in package-build.

**Comment by tvaughan** [comment]
The temporary directory `cask/checkout/ido-at-point` existed but had no contents. I deleted it and everything works now. Thanks.

**Comment by rejeep** [comment]
Ahh, tricky. Always good to do a clean up when things start behaving weird. Glad it worked out for you! :+1:
