### ISSUE TITLE
Setting $EMACS environment variable does not work

### ISSUE THREAD

**Issue by paldepind** [cask/cask#339]
Thank you for maintaining and developing Cask.

I am not sure if this is a bug in Cask. But when I set the `$EMACS` environment variable and run `cask exec ecukes` I get the following error:

```
$ cask exec ecukes
cask exec: error: [Errno 2] No such file or directory
```

I've tried both

```
EMACS="$(evm bin emacs-24.4-travis)"
```

And

```
EMACS="path/to/compiled/emacs"
```

I am using Cask version 0.7.4. Running Cask without the environment variable set works just fine.

**Comment by rejeep** [comment]
Hey, we just merged some code related to the $EMACS env (see https://github.com/cask/cask/commit/9f101d91ad0a5a599dfbe3f64508acf70564c6f6). Does it work if you use $CASK_EMACS instead?

**Comment by paldepind** [comment]
Setting `$CASK_EMACS` seems to have no effect.

```
$ CASK_EMACS="$(evm bin emacs-24.4-travis)" cask exec ecukes
24.5.1
23 scenarios (0 failed, 23 passed)
134 steps (0 failed, 0 skipped, 134 passed)
```

The version number being printed is being printed in the setup part of my tests and it shows the version of my system wide Emacs installation.

Should I try the current master?

**Comment by phillord** [comment]
Are you running these command inside Emacs -- with M-x compile, or M-x shell? Or outside?

**Comment by paldepind** [comment]
Outside of Emacs in a virtual terminal.

**Comment by rejeep** [comment]
And you have installed the dependences for that version (they are scoped on version)? Take a look at `.cask`.

`EMACS="$(evm bin emacs-24.4-travis)" cask install`

**Comment by paldepind** [comment]
Sorry. I did not do that. I though that the dependencies I had already installed would be used.

I've created #340 if you think this should be added to the documentation.

**Comment by rejeep** [comment]
Thank you for those kind words! :smile: 

I figured it worked out for you? Can we close this?

**Comment by paldepind** [comment]
Yes. Installing the dependencies worked. The only reason to leave it open would be that maybe the error message should be improved. `No such file or directory` is not that helpful.

**Comment by rejeep** [comment]
I agree. I've seen others with this issue before. @lunaryorn would it be easy to put something like that in the bin-script?

**Comment by lunaryorn** [comment]
@rejeep A better error message, that is?  I guess so, yes. I gave it a try, see d0dbaf5

**Comment by rejeep** [comment]
> A better error message, that is?

Yes!

@paldepind can you try it out please?
