### ISSUE TITLE
Cask exits immediately, "Select coding system" message appears

### ISSUE THREAD

**Issue by sp3ctum** [cask/cask#341]
I'm on Windows 7, and running `cask install` in my project will seemingly exit immediately with no results. I can continue to type in my bash prompt (or `cmd.exe` prompt) for a few seconds, but then I see the message

`Select coding system (default utf-8):`

Could I have installed cask incorrectly? My installation consisted of
- install python 2.7, add to `PATH`
- add `~/.cask` to `PATH`
- add my emacs.exe to `PATH`

**Comment by sp3ctum** [comment]
Just to add: in a similar fashion, running any cask command, such as `cask path` in my project root, will exit cask immediately (can type a new command), and then after a second or so, print the result of the command.

**Comment by yitang** [comment]
I have the same problem and can't use cask to install packages.

**Comment by fleimgruber** [comment]
I am experiencing these issues as well.  This is also a blocker for AppVeyor CI.

Windows 7
GNU Emacs 25.1.1
Cask latest master https://github.com/cask/cask/commit/0a2e8436e02af6ca688b25ba90a19505a6113296
Python 2.7.13

**Comment by dickmao** [comment]
Please reopen if this remains an issue.  Also include a transcript of the session with `--debug` turned on, e.g., `cask --debug path`
