### ISSUE TITLE
Is it possible to load development dependencies of a project to a running Emacs?

### ISSUE THREAD

**Issue by sp3ctum** [cask/cask#342]
This is my use case:
- open emacs, hack away for a bit
- notice something is not right in one of my own packages
- start to fix the problem in the source code
- try to modify/run tests

Here I get an error: I don't have the `buttercup` package installed in my day-to-day Emacs config. Instead I have it in each project as a development time dependency.

Could Cask help me with my situation?

**Comment by sp3ctum** [comment]
By the way: normally I work around this by doing `cask exec emacs` in the project directory.

**Comment by lunaryorn** [comment]
@sp3ctum I'm not sure what the problem is.  If you want to use buttercup in your live Emacs session, why don't you just install it?

The Cask environment is entirely separate from your normal packages.

**Comment by sp3ctum** [comment]
Hi, thanks for your answer. Maybe my use case isn't idiomatic to Cask.
I'll have to think about my workflow a bit. :thought_balloon:
