### ISSUE TITLE
Can `cask build` command return non-zero exit code when build has errors?

### ISSUE THREAD

**Issue by yuutayamada** [cask/cask#350]
Thank you maintaining this convenient package, but I have a problem
to check byte compile errors for testing purpose.

I'm using `cask build` command for testing, but return 0 even byte compiling is failed by errors.

Is there way to change this behavior or other way to find byte compile errors?

EDIT:
I installed via
```sh
curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
```
and updated by `cask upgrade-cask` before I check `cask build` command.

**Comment by rejeep** [comment]
> Is there way to change this behavior or other way to find byte compile errors?

We could do this for compiler errors, but I don't know if there's any (easy) way of doing it for warnings. But perhaps this is what we want, not really sure.

**Comment by lunaryorn** [comment]
There's an option `byte-compile-error-on-warn` which we could expose as a flag for `cask build`, e.g. `-Werror` or so.

**Comment by rejeep** [comment]
Nice! 👍 I'll see if I can get something together.

**Comment by rejeep** [comment]
Closing in favour of https://github.com/cask/cask/pull/351

Can you guys please have a look!?
