### ISSUE TITLE
ignoring git directories? e.g. :files ("bin")

### ISSUE THREAD

**Issue by fommil** [cask/cask#353]
I'm experimenting with a new `exec` plugin to `Cask` to format source code based on `elisp-format`, here it is

```elisp
(depends-on "elisp-fmt" :git "https://gitlab.com/fommil/elisp-fmt.git" :files ("bin" "*.el"))
```

only when you do that, the `bin` directory never comes with it. Have I done something wrong or is this a bug? Did a `cask upgrade` right now.

**Comment by fommil** [comment]
ok, doing

```elisp
(depends-on "ert-runner" :git "https://github.com/rejeep/ert-runner.el.git" :files ("*.el" "bin" "reporters"))
```

seems to work, so now I'm totally confused.

**Comment by fommil** [comment]
@rejeep sorry to pull you in on this, but I'm basically copying how you packaged `ert-runner` and I can't figure out how to get the `bin` folder to come down in `Cask`. Any ideas? Did you do any extra magic?

**Comment by fommil** [comment]
I even added a `files` section to my dependency's `Cask` file but no difference. I also tried moving the hosting to github (instead of gitlab), and no difference.

**Comment by rejeep** [comment]
Just a thought, is the `bin` directory empty?

Cask actually doesn't do the work here. Cask simply uses [package-build.el](https://github.com/melpa/melpa/blob/master/package-build.el) for this, so I would suggest you look there instead.

**Comment by fommil** [comment]
nope, the `bin` directory has a script in it (which is pretty much copied and pasted from `ert-runner`)

**Comment by lunaryorn** [comment]
@fommil A wild guess, is your script executable?

**Comment by fommil** [comment]
@lunaryorn yes, it is

**Comment by fommil** [comment]
I think it's time to call in the big guns. @purcell could you please take a look at this ticket and see if anything jumps out at you?

**Comment by purcell** [comment]
That `:files` spec would work fine for `package-build.el` alone. I've never seen `:files` together with `depends-on`, though, and I'm not a Cask expert, so not sure what's going on here, sorry.

**Comment by rejeep** [comment]
@fommil Btw, what do you mean with _"basically copying how you packaged ert-runner"_?

**Comment by fommil** [comment]
@rejeep the recipe on MELPA, and also I literally copied your `ert-runner` shell script into my code as `elisp-fmt` then did a search replace inside. I also looked in your `Cask` and package files to see if you were doing anything magical.

**Comment by rejeep** [comment]
Hmm, then it should definitely work as both work the same...

**Comment by fommil** [comment]
yeah, it is driving me crazy.

**Comment by lunaryorn** [comment]
@fommil So, I've tried this in a simple package of mine, but failed to reproduce your problem:

```
$ cat Cask
(source gnu)
(source melpa)

(package-file "osx-trash.el")

(files "osx-trash.el" "trashfile.AppleScript")

(development
 (depends-on "elisp-fmt" :git "https://gitlab.com/fommil/elisp-fmt.git" :files ("bin" "*.el")))
$ ls -d .cask/
ls: .cask/: No such file or directory
$ cask install
$ ls -d .cask/
.cask/
$ find .cask/ -name 'elisp-fmt' -type f
.cask//25.0.94.1/elpa/elisp-fmt-20160516.2336/bin/elisp-fmt
$ cask exec elisp-fmt
Format osx-trash.el ...
Mark set
Format osx-trash.el completed (0s).
```

**Comment by fommil** [comment]
@lunaryorn thanks for looking into this, it's good news that it works for you! This maybe hints at some bad git cache, I'll try to find any caches and clean them out.

**Comment by lunaryorn** [comment]
@fommil I'm sorry that I didn't reply but I don't have any clues about this issue anyway.

I'm going to close it as it looks as if it's a random fluke.
