### ISSUE TITLE
Speeding up cask exec

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#361]
Are there known trick to speed up `cask exec`? I'm seeing the following on my machine:

``` batch
$ mkdir /tmp/cask-perf
$ cd !$
$ cask init
$ time emacs -Q --batch --eval '(kill-emacs)'
real    0m0.037s
user    0m0.028s
sys 0m0.004s
$ time cask exec emacs -Q --batch --eval '(kill-emacs)'
real    0m0.630s
user    0m0.564s
sys 0m0.044s
```

I'm using Emacs Lisp as a scripting language, and the .6 seconds delay is not ideal. Is there anything I can do to make things better?

**Comment by lunaryorn** [comment]
@cpitclaudel Apart from [not using Emacs Lisp for scripting](https://medium.com/@lunaryorn/emacs-script-pitfalls-2572c7e306dc) 😜 there's nothing that you can do.  `cask exec` has some involved internal processing to setup the proper load path etc. and there are no shortcuts you can take from the outside.

There may be possible optimizations to Cask's internal `exec` code, but I for my part never investigates these, for personally I always found Cask fast enough.

I'd invite you to profile and improve, but to me it's a very low priority issue, and I won't be able to spent a lot of time helping you.  Sorry 😌

**Comment by joelmccracken** [comment]
I wrote something that traversed .cask a little while ago and set up load
paths correctly; I did this because I didn't want to run my normal Emacs
through "cask exec". It wasn't very hard. I can't find it now, though =(

On Tue, Aug 2, 2016 at 10:53 AM, Sebastian Wiesner <notifications@github.com

**Comment by cpitclaudel** [comment]
@joelmccracken I did essentially the same with `find`, and indeed the speed problem went away. But I guess `cask` does more, right? Otherwise I'm not sure why it takes so much time.

@lunaryorn Of course :) Thanks for the pointers. I did try profiling, but I'm running into something weird: namely, python's cProfile doesn't print anything:

```shell
$ python -m cProfile `which cask` exec true
$
```

And if I give it a `-o`, it doesn't create the file. Any idea what might cause this?

**Comment by lunaryorn** [comment]
We use `os.execvp` to spawn the subprocess which bypasses normal Python cleanup, and thus probably prevents cprofile from printing its profile stats.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
Here's what I've found at this point:

* The issue isn't on the python side; instead, it's in the Emacs side. Cask calls itself twice to run `exec`: one to get the load-path, and once to get the path. Suppressing one of these calls, e.g. by introducing a path+load-path command, would divide Cask's `exec` startup time by two.

* In each of these calls, what takes time is reading the archive files:

  ```
  - ...                                                              53 100%
   - cask--use-environment                                           44  83%
    - if                                                             44  83%
     - progn                                                         44  83%
      - let                                                          44  83%
       - let                                                         44  83%
        - if                                                         44  83%
         - unwind-protect                                            44  83%
          - let*                                                     44  83%
           - unwind-protect                                          44  83%
            - progn                                                  44  83%
             - condition-case                                        44  83%
              - progn                                                44  83%
               - epl-initialize                                      44  83%
                - package-initialize                                 44  83%
                 - package-read-all-archive-contents                 36  67%
                  - package-read-archive-contents                    36  67%
                     package--read-archive-file                      16  30%
                     package--add-to-archive-contents                 16  30%
                 + package-load-all-descriptors                       4   7%
                 + package--build-compatibility-table                  4   7%
     Automatic GC                                                     5   9%
   + concat                                                           4   7%
  ```

  IIUC, however, there's no need to load these files to get the path and load-path. I'll see if that loading phase can be skipped.

**Comment by cpitclaudel** [comment]
Adding `(setf (cask-bundle-sources bundle) nil)` at the top of both `cask-load-path` and `cask-exec-path` reduced the profile of load-path to this and shaves about 20% of the running time.:

```
- ...                                                            3992 100%
 - progn                                                         3990  99%
  - let                                                          3990  99%
   - let                                                         3990  99%
    - if                                                         3990  99%
     - unwind-protect                                            3990  99%
      - let*                                                     3990  99%
       - unwind-protect                                          3990  99%
        - progn                                                  3990  99%
         - condition-case                                        3990  99%
          - progn                                                3990  99%
           - epl-initialize                                      3990  99%
            - package-initialize                                 3990  99%
             - package-load-all-descriptors                      3990  99%
              - package-load-descriptor                          3990  99%
               - package-process-define-package                  3990  99%
                  apply                                          3990  99%
   Automatic GC                                                     2   0%
```

**Comment by cpitclaudel** [comment]
Here's how to get a profile:

```
(defun cask-cli/load-path ()
  "Print `load-path' for all packages and dependencies.

The output is formatted as a colon path."
  (require 'profiler)
  (setq profiler-sampling-interval 1000)
  (profiler-start 'cpu)
  (princ (concat (s-join path-separator (cask-load-path (cask-cli--bundle))) "\n"))
  (profiler-write-profile (profiler-cpu-profile) "cask-cli.profile"))
```

I'll admit that I don't understand Cask well enough to dig deeper: do we really need to run package-initialize?

**Comment by lunaryorn** [comment]
@cpitclaudel I don't think that we'll get a proper load-path without initializing the package system.

**Comment by lunaryorn** [comment]
We could try and fold both Cask calls into one, though, which would export all required data over JSON for Python to parse.  We'd only call package-initialize once then.

That said, it's not for me to make that refactoring.  I just don't have the time, and to me the pain isn't big enough to try and find some time.

**Comment by cpitclaudel** [comment]
Of course of course :) I'll see whether I do have time ^^

**Comment by Fuco1** [comment]
> I don't think that we'll get a proper load-path without initializing the package system.

Why wouldn't it be enough to add all the directories from the elpa directory to the load path?  If a package is present multiple times we pick the highest version.

**Comment by Fuco1** [comment]
So, constructing the path manually I get 0.66s when I execute it like this:

```
time emacs --batch -L . -l cask.el --eval '(progn (princ (mapconcat \'identity (cask-load-path (cask-setup default-directory)) ":")) (princ "\n"))'
```

I get 0.85s when I run it through `cask load-path` (commander.el uses 0.2s to setup).  It takes 1.05s with the current code.

I'm quite surprised it's so slow considering `emcas -batch --eval '(kill-emacs)'` takes 0.03s.  So I guess working with file system in emacs is really slow.

**Comment by Fuco1** [comment]
Actually, it's not even that, it's `shell-command-to-string`. Emacs is nothing but traps...

**Comment by Fuco1** [comment]
Removing some eager requires and folding the exec+load path calls into one i got it down from 2.25s to 0.5 to execute `cask exec ert-runner`. I think i can get another 50 to 150 ms my lazily loading some of the bootsteap deps.

My computer cant for some reason connect to the network so ill push the branch from the office tomorrow

**Comment by dickmao** [comment]
This is the killer that adds 500ms.
https://github.com/cask/cask/blob/7ae2d54004b26ebb891f7a011c86cff706acbf1a/cask-bootstrap.el#L48

Alas, the whole point of cask is to evaluate s-expressions in a package "clean-room", one which obviously must be initialized by the above line!  So closing this in deference to reason.

**Comment by cpitclaudel** [comment]
Wait, wasn't the problem that package-initialize was called twice? (I lost track since this was a few years ago)

**Comment by dickmao** [comment]
`package-initialize` should not currently be called twice.  If it is, then I hope someone will castigate me sooner than later, and with extreme prejudice.

**Comment by cpitclaudel** [comment]
Thanks!
