### ISSUE TITLE
Why does Cask fail to install magit as a dependency?

### ISSUE THREAD

**Issue by vermiculus** [cask/cask#370]
Here's the caskfile we're using:

```lisp
(source gnu)
(source melpa)

(package-file "libgit2.el")

(files "libgit2.el"
       "libgit2-core.so")

(development
 (depends-on "ert")
 (depends-on "ert-runner")
 (depends-on "magit")
 (depends-on "undercover"))
```

`ert-runner` etc. seem to work fine – what's special about magit? [It doesn't seem to be available when required.](https://travis-ci.org/ksjogo/emacs-libgit2/builds/168601970#L1160) (Here is [the script it's running](https://github.com/ksjogo/emacs-libgit2/blob/91f3c404c0f73d1827462ecac57db3982a4d00a2/libgit2-demo.el).)

**Comment by lunaryorn** [comment]
`cask` installs dependencies in a local directory but your script runs outside of `cask` and thus doesn't see the Cask load-path; your `package-initialize` gets packages from `~/.emacs.d/elpa`.

Drop `package-initialize` and run the script through `cask exec`.

**Comment by lunaryorn** [comment]
By the way, a nice package you got there :clap: I love seeing modules being put to use; brb, studying your build setup now 😎

**Comment by vermiculus** [comment]
[I'm trying that out now](https://travis-ci.org/ksjogo/emacs-libgit2/builds/168605462); I'll keep you posted. And yeah, it's a very nice idea – my selfish goal is to make Magit faster on windows by avoiding so many process-spawns 👍

**Comment by lunaryorn** [comment]
You got me nerd-sniped now; gonna try and write a Hello World Emacs module in Rust tonight 😎

**Comment by vermiculus** [comment]
@lunaryorn I tried doing something similar with Go -- if you get it working with Rust, there's a great opportunity to write higher-level abstractions with Emacs modules 👍

**Comment by rejeep** [comment]
> my selfish goal is to make Magit faster on windows by avoiding so many process-spawns

Magit faster, I'm listening! What about other platforms?

**Comment by vermiculus** [comment]
The goal is to have it compile on Windows/OSX/Linux, but OSX+Linux is all that's been tested so far. There's already [a significant performance boost](https://travis-ci.org/ksjogo/emacs-libgit2/builds/168624930#L1168) with simple functions.

The next real hurdle is how to distribute. See melpa/mepla#4321.

**Comment by rejeep** [comment]
Great job! 👍

**Comment by lunaryorn** [comment]
Provide an Emacs Lisp shim that compiles on demand or downloads prebuilt binaries from Github releases?  Or distribute separately and just provide a shim library that tries to load the native module from some global place (e.g. `~/.cargo/` for Rust).

**Comment by lunaryorn** [comment]
@vermiculus By the way, I think that there are quite good libgit2 bindings for Rust, so if I succeed to build a Hello World module you could get rid of the C 😜

**Comment by vermiculus** [comment]
@ksjogo deserves a lot of the credit, too 😄

By the way, what do you think about that Johannes? If we can do it in Rust, would you be up to that adventure?

**Comment by vermiculus** [comment]
> Provide an Emacs Lisp shim that compiles on demand or downloads prebuilt binaries from Github releases?

That's probably the best plan. Once we actually have releases, I'll see what I can do about creating an automated build system for binaries based on tags.

Does Rust require any sort of runtime?

**Comment by joelmccracken** [comment]
@vermiculus nope! That's one of Rust's primary "features"

**Comment by lunaryorn** [comment]
@vermiculus Pure rust binaries are linked statically as far as I know.  It does require a C standard library, though, but that shouldn't be a show-stopper.

C libraries can be linked statically or dynamically but I think the standard for FFI bindings is to link statically, to make builds reproducible.

**Comment by lunaryorn** [comment]
Oh, looking at the build script if git2-rs it even appears to build libgit2 itself, so you won't even need libgit2 installed.

**Comment by lunaryorn** [comment]
@vermiculus There you go: https://github.com/lunaryorn/emacs-rust-module  I got so far as to `println!` from Emacs 😎  Was much much easier than I thought; Rust's FFI is quite convenient.

There's a couple of things left, take a look at the "Board" project to get any idea of what's left to do.

I plan to refine this to the point where it could build out of the box, and then write a good README and a blog post about it.

**Comment by vermiculus** [comment]
https://media.giphy.com/media/Ic97mPViHEG5O/giphy.gif

This is amazing.
