### ISSUE TITLE
Unable to activate package ‘git’

### ISSUE THREAD

**Issue by DamienCassou** [cask/cask#372]
I'm trying to install Cask but I can't

``` shell
$ cask
[...]
Unable to activate package ‘git’
Required package ‘s-1.7.0’ is unavailable
```

I debugger the problem and found out the problematic line is the `(package-initialize)` inside `cask-bootstrap.el`. Modifying this part of the code:

``` lisp
      (let (package-archives
            package-alist
            package-archive-contents
            (package-user-dir cask-bootstrap-dir))
        (message "BEFORE package-initialize: %s" package-load-list)
        (message "package-alist: %s" package-alist)
        (message "package-activate-list: %s" package-activated-list)
        (package-initialize)
        (message "BEFORE 1st mapc")
        (condition-case nil
            (mapc 'require cask-bootstrap-packages)
```

results in:

```
$ $EMACS -Q --script /home/cassou/.cask/cask-cli.el -- upgrade-cask
[...]
BEFORE package-initialize: (all)
package-alist: nil
package-activate-list: nil
Unable to activate package ‘git’.
Required package ‘s-1.7.0’ is unavailable
```

**Comment by DamienCassou** [comment]
I'm on NixOS:

```
$ $EMACS --version
GNU Emacs 25.1.1
```

**Comment by lunaryorn** [comment]
Please run `cask --debug install` and show us your `Cask` file.

**Comment by DamienCassou** [comment]
I don't have any Cask file yet, I'm just trying to install cask:

```
[cassou@luz4:~]$ mkdir /tmp/cask-test
[cassou@luz4:~]$ cd /tmp/cask-test/
[cassou@luz4:/tmp/cask-test]$ rm -rf ~/.cask/
[cassou@luz4:/tmp/cask-test]$ export EMACS=/nix/store/cr388ab8l3lxxdixxbiwg0cc4nixhw84-emacs-25.1/bin/emacs
[cassou@luz4:/tmp/cask-test]$ $EMACS --version
GNU Emacs 25.1.1
[...]
[cassou@luz4:/tmp/cask-test]$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go > cask.py
[cassou@luz4:/tmp/cask-test]$ python cask.py 
Cloning into '/home/cassou/.cask'...
remote: Counting objects: 3401, done.
remote: Total 3401 (delta 0), reused 0 (delta 0), pack-reused 3401
Receiving objects: 100% (3401/3401), 1.09 MiB | 780.00 KiB/s, done.
Resolving deltas: 100% (1917/1917), done.
Unable to activate package ‘git’.
Required package ‘s-1.7.0’ is unavailable
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
[cassou@luz4:/tmp/cask-test]$ ~/.cask/bin/cask --debug install
Unable to activate package ‘git’.
Required package ‘s-1.7.0’ is unavailable
```

**Comment by lunaryorn** [comment]
Can you install `s` in your normal Emacs?  I'm trying to rule out a temporary network/MELPA issue.

**Comment by lunaryorn** [comment]
@DamienCassou That said, I wonder why it should try to use version 1.7 of s?  That's a very old one and not current in MELPA Stable or MELPA.

Can you try and remove `~/.emacs.d/.cask` and try again?

**Comment by DamienCassou** [comment]
@lunaryorn it seems that removing my `~/.emacs.d/cask` fixed my problem. I'm a bit worried now though. Why does cask need to add stuff to `~/.emacs.d`? To me, the fact that cask is implemented in Emacs Lisp is an implementation detail and I don't see the reason to pollute my Emacs configuration directory.

**Comment by DamienCassou** [comment]
Thanks for the help!

**Comment by lunaryorn** [comment]
@DamienCassou Cask writes its own dependencies to `~/.emacs.d/`—which is not only your Emacs configuration directory but also a generic directory for data files of Emacs extensions.  Cask is one such extension—the implementation language may be a detail, but it surely targets the Emacs platform.

**Comment by DamienCassou** [comment]
Why don't you put that in `~/.cash` instead?

**Comment by lunaryorn** [comment]
That's a potential installation directory.

**Comment by lunaryorn** [comment]
And ~/.emacs.d *is* the right place for data files from Emacs libraries and programs, in my opinion, see e.g. locate-user-emacs-file.

**Comment by rejeep** [comment]
I *think* that decision is in here somewhere: https://github.com/cask/cask/issues/31
