### ISSUE TITLE
utorrent contains malware

### ISSUE THREAD

**Issue by pluskid** [cask/cask#377]
utorrent contains a lot of malwares that install browser extensions and change homepage, search engines, etc. Please warn the user in the post-installation instructions, when ask them to run the installer.

**Comment by joelmccracken** [comment]
Did you intend to open this issue on https://github.com/caskroom/homebrew-cask ?

**Comment by pluskid** [comment]
Sorry! Yes, that was what I meant to do. I was quite angry about lots of malware installed on my computer and completely lost my mind. Sorry again for the spam!

**Comment by joelmccracken** [comment]
These things happen :)
