### ISSUE TITLE
Cask could not be boostrapped. Windows install using command prompt

### ISSUE THREAD

**Issue by selection989** [cask/cask#382]
Attached is an image showing the output from command prompt. Any assistance with this problem would be much appreciated. 

I've also tried cygwin-64. 

![image](https://cloud.githubusercontent.com/assets/1596808/23690137/2ace0faa-0424-11e7-9d4e-da0003261265.png)

**Comment by syohex** [comment]
Because Windows Python does not support `os.environb`(`os.supports_bytes_environ` is `False`).

**Comment by Fuco1** [comment]
Could be probably solved by using python 2: #285

**Comment by tom-bowles** [comment]
Using python 2 isn't a solution, it's a workaround (and a horrible one at that)

**Comment by tom-bowles** [comment]
I don't see why it's using environb at all. The natural representation for environment variables in python is str, not bytes. Python takes care of converting to bytes as needed. From the python docs:

> In Python, file names, command line arguments, and environment variables are represented using the string type. On some systems, decoding these strings to and from bytes is necessary before passing them to the operating system. Python uses the file system encoding to perform this conversion (see sys.getfilesystemencoding()).

It should just use os.environ and get rid of the b prefixes from all the string literals.

**Comment by Fuco1** [comment]
If you know the solution and if you can ensure it won't break macos and linux users we can incorporate it.  Windows was not officially supported.

**Comment by tom-bowles** [comment]
I'm raising a PR now

**Comment by tom-bowles** [comment]
If Windows isn't supported, the list of reasons a project wouldn't benefit from using Cask at https://cask.readthedocs.io/en/latest/guide/introduction.html might need updating ;-)
