### ISSUE TITLE
Get a way to lint emacs files

### ISSUE THREAD

**Issue by DamienCassou** [cask/cask#387]
There are several linting tools that ensure emacs lisp files look reasonable (e.g., https://github.com/purcell/package-lint and `byte-compile-error-on-warn`). It would be nice to have a `cask lint` command.

**Comment by purcell** [comment]
This is probably tangential to the goal of `cask`, to be honest. It's already possible to use `package-lint` with `cask`, by adding `package-lint` to the development dependencies in your `Cask` file, and then using the appropriate invocation of `cask emacs` to run the package-lint batch command. (Note there's [an issue with that](https://github.com/purcell/package-lint/issues/55) which I haven't yet solved neatly.)

**Comment by DamienCassou** [comment]
I have the same opinion but I had to ask :-).
