### ISSUE TITLE
Install fails with 'Wrong type argument: epl--package-desc-p...'

### ISSUE THREAD

**Issue by marcowahl** [cask/cask#391]
Hi, 

Thanks for cask.

Unfortunately I can't install cask on Archlinux today.  See the issue below.

Can you please help?

Best regards,

+11:12% curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into '/home/b/.cask'...
remote: Counting objects: 3405, done.
remote: Total 3405 (delta 0), reused 0 (delta 0), pack-reused 3405
Receiving objects: 100% (3405/3405), 1.09 MiB | 633.00 KiB/s, done.
Resolving deltas: 100% (1917/1917), done.
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Contacting host: elpa.gnu.org:443
Package refresh done
Wrong type argument: epl--package-desc-p, #s(package-desc shut-up (20150423 522) "Shut up would you!" ((cl-lib (0 3)) (emacs (24))) nil nil "/home/b/.emacs.d/.cask/26.0/bootstrap/shut-up-20150423.522" ((:url . "http://github.com/rejeep/shut-up.el")) nil)
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
(1)+11:12%

**Comment by marcowahl** [comment]
The install goes through with emacs-25.2 (export CASK_EMACS=/usr/bin/emacs-25.2).

The above report holds for a current tip 26 Emacs.

**Comment by politza** [comment]
I get a different error with the current HEAD (0bddbbc).

        Dependency undercover failed to install: Variable binding depth exceeds max-specpdl-size
        Output:
        Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
        Contacting host: melpa.org:443
        Checking /home/politza/projects/pdf-tools/.cask/27.0/elpa/shut-up-20150423.522...
        Compiling /home/politza/projects/pdf-tools/.cask/27.0/elpa/shut-up-20150423.522/shut-up-autoloads.el...
        Compiling /home/politza/projects/pdf-tools/.cask/27.0/elpa/shut-up-20150423.522/shut-up-pkg.el...
        Compiling /home/politza/projects/pdf-tools/.cask/27.0/elpa/shut-up-20150423.522/shut-up.el...
        ~/.cask/cask-cli.el:Error: Variable binding depth exceeds max-specpdl-size
        Done (Total of 0 files compiled, 2 skipped)
        Error loading autoloads: (error Variable binding depth exceeds max-specpdl-size)
        Error in package--load-files-for-activation: (error Variable binding depth exceeds max-specpdl-size)

**Comment by sambrightman** [comment]
I believe Cask has been working on Emacs 26 for quite a while now - please file a new issue if there are new problems.

**Comment by kawabata** [comment]
I've got the similar error, too.   Emacs 27.0.50.

````
% cat Cask
(source melpa)
(depends-on "dash")
% cask install

Dependency dash failed to install: Wrong type argument:
epl--package-desc-p, #s(package-desc dash (20180206 2124) "A modern
list library for Emacs" nil single "melpa" nil ((:commit
. "48a5015dd1314a8bcad48f2ad8866dd911001b01") (:keywords "lists"))
nil)
````
