### ISSUE TITLE
Some dependencies were not available

### ISSUE THREAD

**Issue by raxod502** [cask/cask#393]
I am attempting to run the tests for [`clj-refactor`](https://github.com/clojure-emacs/clj-refactor.el), which uses Cask. The `Cask` file is:

```
(source melpa)
(source gnu)

(package-file "clj-refactor.el")

(development
  (depends-on "ecukes")
  (depends-on "espuds")
  (depends-on "cider")
  (depends-on "edn")
  (depends-on "clojure-mode"))
```

I have installed Cask from Homebrew using `brew install cask`. The version is `0.8.1`. Running `cask` in the project directory gives me:

```
% cask
Some dependencies were not available: inflections, edn, cider, clojure-mode, multiple-cursors, paredit, s, clojure-mode, edn, cider, espuds, ecukes
```

Note that I can install packages from both GNU ELPA and MELPA using `M-x package-install` from within Emacs. (But I do not usually do this, since I dislike `package.el` and use [`straight.el`](https://github.com/raxod502/straight.el) to manage my packages.)

System information:

```
                -/+:.           raxod502@[redacted]
               :++++.           ----------------------------
              /+++/.            OS: OS X El Capitan 10.11.6 15G1510 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,3
   .:/++++++/::::/++++++/:`     Kernel: 15.6.0
 .:///////////////////////:`    Uptime: 39 days, 17 hours, 45 minutes
 ////////////////////////`      Packages: 357
-+++++++++++++++++++++++`       Shell: zsh 5.3.1
/++++++++++++++++++++++/        Resolution: 1680x1050@2x
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal: iTerm2
  `ossssssssssssssssssssss/     Terminal Font: InputMono-Medium 14
    :ooooooooooooooooooo+.      CPU: Intel i7-4980HQ (8) @ 2.80GHz
     `:+oo+/:-..-:/+o+/-        GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
                                Memory: 4106MiB / 16384MiB
```

Can I provide any other information to help debug the problem? Running with `--verbose` and `--debug` produced no further insight (an additional message about `Importing package-keyring.gpg`).

**Comment by vspinu** [comment]
Same issue here with cider project this time. Occurs only with development Emacs 26, Emacs 25 and 24 are fine. 

```
cask install
Some dependencies were not available: pkg-info, clojure-mode, markdown-mode, buttercup
```

```el
(source gnu)
(source melpa)

(package-file "cider.el")

(files "*.el" (:exclude ".dir-locals.el"))

(development
 (depends-on "buttercup")
 (depends-on "markdown-mode"))
```

**Comment by raxod502** [comment]
That's interesting, since I'm running Emacs 25.2. I now realized that I neglected to include my Emacs version in the original report, silly me…

```
GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21
```

**Comment by vspinu** [comment]
Actually, it started working for me. Looks like a temporary glitch or network issue.

**Comment by raxod502** [comment]
I've just tested again, and I get the same error. I'm on a different network and computer this time, as well (same operating system, though on Sierra rather than El Capitan).

**Comment by raxod502** [comment]
The problem can no longer be reproduced. This is likely due to an update in one package or another. I will close this issue, and re-open if the problem comes back.

**Comment by jiacai2050** [comment]
Anyone with this issue can try `cask upgrade-cask`, this will refresh cask's package list
