### ISSUE TITLE
Incompatibility with package-build-package

### ISSUE THREAD

**Issue by volrath** [cask/cask#407]
I am not 100% sure if this is a Cask bug or a package-build bug:

When using the VCS version of `depends-on`, package-build.el throws a:

```
Dependency <package-name> failed to install: Wrong type argument: sequencep, <package-name>
```

I tracked the error to package-build.el's [`package-build--build-multi-file-package`](https://github.com/melpa/package-build/blob/master/package-build.el#L1075), where `package-name` arrives as a symbol, but apparently is expected as a string.

On cask's side of things, `depends-on` transform package names from strings to symbols [here](https://github.com/cask/cask/blob/master/cask.el#L400), but I think it has been this way since long time ago.

**Comment by volrath** [comment]
[I think this may be the root of the problem](https://github.com/melpa/package-build/commit/063e64ad55ac07a348af0373605fd90348a8bc11#diff-ac4dc19e4f6618a58fcf1c0980e31857L1026)

**Comment by billnote** [comment]
how to solve this problem?
