### ISSUE TITLE
Some packages can never been installed

### ISSUE THREAD

**Issue by YorkZ** [cask/cask#409]
Below is part of my Cask file:

    (source gnu)
    (source melpa)
    (source marmalade)
    
    (depends-on "cask-mode")
    ...
    (depends-on "register-list")
    (depends-on "adaptive-wrap")
    (depends-on "rainbow-mode")
    (depends-on "dos")
    ...

Running `cask` did install all the packages except a few of them, the following was the message:

    Some dependencies were not available: register-list, adaptive-wrap, rainbow-mode, dos

I used to be able to install these packages. However, since a few months ago I was no longer able to install them. I worked around this issue by copying these packages from my previously installed directory, hoping that the issue would get resolved soon. Having waited for several months, I decided that I should report it here.

**Comment by sambrightman** [comment]
Are you sure that this is a Cask issue? I'm my experience this likely comes down to either transient network or certificate verification problems. I notice that:

1. `dos` is not available in any of those repositories.
2. the other packages are all from `gnu`.

When Cask fails, are you able to install them manually (e.g. via `M-x package-install`)? If not, do you see any pertinent messages in the `*Messages*` buffer? I have just used Cask to install `register-list`, `adaptive-wrap`, `rainbow-mode` without issues.

**Comment by YorkZ** [comment]
@sambrightman Thanks for you reply.

> Are you sure that this is a Cask issue?

I was not sure whether this was a Cask issue, but I just wanted to get some help because I've been having this issue for over four months now. My apology if this turns out to be not a Cask issue.

>  this likely comes down to either transient network or certificate verification problems.

It's hard to believe so because I haven't been able to install these packages for over four months.

> dos is not available in any of those repositories.

It was available in Emacs 25.1.1, I still have `dos-20140808.1435` in `~/.emacs.d/.cask/25.1.1/elpa`.

>  I have just used Cask to install register-list, adaptive-wrap, rainbow-mode without issues

Which Emacs version did you use?

**Comment by sambrightman** [comment]
The availability of ELPA packages doesn't change according to your Emacs version. FWIW mine is 25.3.1. `dos` was presumably available at the point in time that you installed it but was subsequently removed (you can check at https://elpa.gnu.org/packages/ or via `M-x list-packages`.

If you have issues verifying certificates for the `gnu` repo then it would not work at any point until this is fixed, so this could persist for 4 months. It could be triggered by a change in behaviour when you upgrade Emacs (there have recently been several changes in certificate verification behaviour IIRC) or by other changes to your system.

Can you confirm if:

1. you are able to install the packages outside of Cask (e.g. `M-x package-install`) and if not, what warnings/errors you can see.
2. you have other packages from the `gnu` repo which install correctly?

**Comment by YorkZ** [comment]
@sambrightman Thank you very much again for your help.

> you are able to install the other 3 packages outside of Cask (e.g. M-x package-install)

I wasn't able to install these packages through `M-x package-install` because they were not in the list for me to choose from.

> you have other packages from the gnu repo which install correctly? do you see gnu packages listed by M-x list-packages

Looks like these packages are the only one I was trying to install from the gnu repo.

Also, when I type `M-x list-packages`, a `Network Security Manager` buffer showed up (see picture). I pressed `s` to proceed and was able to install `register-list`. See the picture.

Looks like this is a SSL certificate issue. I'm not familiar with SSL stuff, so how can I verify the certificate? Is there any configuration in cask to by pass certification verification?

![screenshot from 2017-12-29 06 50 31](https://user-images.githubusercontent.com/742238/34437249-af628866-ec6a-11e7-86ff-617ae9371709.png)

**Comment by sambrightman** [comment]
The best advice I can give is to look for information about getting the underlying problem solved - if it works via `M-x package-install` then it will work in Cask. The exact solution will depend on your Emacs configuration as well as your operating system and its configuration.

Some potential starting points:

1. Look at the `*Warnings*` and `*Messages*` buffers to see what Emacs was doing and what went wrong.
2. Look at the variable `system-configuration-features` (via `C-h v system-configuration-features`) to see if `GNUTLS` support is compiled-in to your Emacs.
3. Check your system certificates are up-to-date (system dependent - are all updates installed?).
4. Look at the variable `gnutls-trustfiles` and see if it points to the right file(s).
5. Try manually verifying the `gnu` certificate using `gnutls-cli` (Emacs is likely showing the exact command it is using in the `*Messages*` buffer).

**Comment by YorkZ** [comment]
Thanks again @sambrightman 

> Look at the *Warnings* and *Messages* buffers to see what Emacs was doing and what went wrong.

No *Warnings" buffer. The following info was found in *Messages* buffer:

    Importing package-keyring.gpg...done
    Failed to download ‘gnu’ archive.

> Look at the variable system-configuration-features (via C-h v system-configuration-features) to see if GNUTLS support is compiled-in to your Emacs.

The following is the value of `system-configuration-features`, apparently GTUTLS has been compiled in. 

    "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS"

> Check your system certificates are up-to-date (system dependent - are all updates installed?).

I've run `sudo update-ca-certificates`.

> Look at the variable gnutls-trustfiles and see if it points to the right file(s).

It's value is: `("/etc/ssl/certs/ca-certificates.crt" "/etc/pki/tls/certs/ca-bundle.crt" "/etc/ssl/ca-bundle.pem" "/usr/ssl/certs/ca-bundle.crt" "/usr/local/share/certs/ca-root-nss.crt")`. But only the file `/etc/ssl/certs/ca-certificates.crt` exists with the timestamp being this morning when I updated ca certificates.

Try manually verifying the gnu certificate using gnutls-cli (Emacs is likely showing the exact command it is using in the *Messages* buffer).

The following was the output from running `gnutls-cli`:

    $  gnutls-cli elpa.gnu.org
    Resolving 'elpa.gnu.org'...
    Connecting to '208.118.235.89:443'...
    - Ephemeral Diffie-Hellman parameters
     - Using prime: 2048 bits
     - Secret key: 2047 bits
     - Peer's public key: 2048 bits
    - Certificate type: X.509
     - Got a certificate list of 3 certificates.
     - Certificate[0] info:
      - subject `CN=elpa.gnu.org', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-12-02 10:00:36 UTC', expires `2018-03-02 10:00:36 UTC', SHA-1 fingerprint `dd8020dc5cdb1d4e9c331f9044ec57a0928e7b97'
     - Certificate[1] info:
      - subject `CN=elpa.gnu.org', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2017-12-02 10:00:36 UTC', expires `2018-03-02 10:00:36 UTC', SHA-1 fingerprint `dd8020dc5cdb1d4e9c331f9044ec57a0928e7b97'
     - Certificate[2] info:
      - subject `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', issuer `O=Digital Signature Trust Co.,CN=DST Root CA X3', RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', SHA-1 fingerprint `e6a3b45b062d509b3382282d196efe97d5956ccb'
    - The hostname in the certificate matches 'elpa.gnu.org'.
    - Peer's certificate issuer is unknown
    - Peer's certificate is NOT trusted
    - Version: TLS1.2
    - Key Exchange: DHE-RSA
    - Cipher: AES-128-CBC
    - MAC: SHA1
    - Compression: NULL
    - Handshake was completed
    
    - Simple Client Mode:
    
    - Peer has closed the GnuTLS connection

Hope you can spot something.

**Comment by sambrightman** [comment]
Yes, the lines:

```
- Peer's certificate issuer is unknown
- Peer's certificate is NOT trusted
```

If you look at the `\*Messages\*` buffer you should see the exact commands and files Emacs is trying. However, since you have TLS support compiled in, it is probably not calling out to external programs in the first place. Also: `update-ca-certificates` only updates the concatenated file in `/etc` from the individual files stored elsewhere. You need to ensure that the packages which install those individual files are up-to-date on your operating system. The package name/upgrade command varies by operating system.

I think you'd be better off using https://emacs.stackexchange.com, https://unix.stackexchange.com, or perhaps https://lists.gnu.org/mailman/listinfo/help-gnu-emacs to get support on this. This ticket will be closed since it's not a Cask issue.

**Comment by YorkZ** [comment]
Turns out that we may still not be able to exclude the possibility that the problem is still in cask. This is because `M-x list-package` works without an issue if I start emacs by `emacs -Q`. Further more, I found that if I start emacs as `emacs -Q`, and then evaluate the following:

    (require 'cask "~/.cask/cask.el")
    (eval-and-compile (cask-initialize))

the exact same problem showed up.

**Comment by sambrightman** [comment]
The default value of `package-archives` is `(("gnu" . "http://elpa.gnu.org/packages/"))` - i.e. without encryption. You need to fix your certificate verification, which based on the information so far is broken through no fault of Cask. It is likely (and good) that the default will change to include encryption soon - it has been changed in Emacs 26/master already.

If you need a temporary workaround you can specify the `source` using an insecure URL, per http://cask.readthedocs.io/en/latest/guide/dsl.html#el.function.source. I would not recommend this.

**Comment by YorkZ** [comment]
Thanks @sambrightman, overbidding URL  of  the `gnu` source by `(source gnu "http://elpa.gnu.org/packages/")` works. You should have told me this much earlier. :)

**Comment by sambrightman** [comment]
As discussed elsewhere, one potential issue is an Emacs that is not falling back to either GnuTLS >= 3 or (insecure, thus easily-succeeding) `openssl s_client` (due to various ways of configuring or running things). However, a root cause was that elpa.gnu.org was issuing duplicate certificates in its chain, which counts as out-of-order and &mdash; in some environments &mdash; this is not trusted. That certificate is now fixed, so several more setups will work without modification.
