### ISSUE TITLE
ReadTheDocs latest not updating

### ISSUE THREAD

**Issue by sambrightman** [cask/cask#411]
Is the hook installed properly?

**Comment by rejeep** [comment]
IIRC all I had to do was push to Github, but that was a while ago.

**Comment by sambrightman** [comment]
Actually, I can see the build errors through my ReadTheDocs account. This is due to rtfd/readthedocs.org#3296 - could you uncheck the installation checkbox in advanced settings?

**Comment by rejeep** [comment]
Done. I also added you as a maintainer

**Comment by sambrightman** [comment]
Great, thanks! The checkbox was still checked, so I unchecked it. Now the build fails because lunaryorn/sphinxcontrib-emacs needs a couple of small patches for newer Sphinx versions. For some reason the project is archived but I can build with local patches. @lunaryorn could you maybe unarchive to accept PRs?

**Comment by lunaryorn** [comment]
@sambrightman I'm sorry, but I deliberately archived the project. I would not like to maintain this project again, not even just to accept some pull requests. I won't restore the project, but please feel free to fork it and take over—in this case I'll gladly pass ownership of the PyPI package to you.

I unsubscribed from this thread, so please keep me mentioned if you need me.

**Comment by sambrightman** [comment]
@lunaryorn Yes, I will need to release a new version so that makes sense.

**Comment by lunaryorn** [comment]
Please tell me your PyPI user name and I’ll transfer the package to you.  

Meanwhile you can use a Git dependency in requirements.txt to point it to your patched fork.

**Comment by sambrightman** [comment]
My PyPI username is sambrightman.

**Comment by lunaryorn** [comment]
@sambrightman I transfered the PyPI package to you, and removed myself as owner.

**Comment by sambrightman** [comment]
Success! Thanks @lunaryorn.

**Comment by lunaryorn** [comment]
@sambrightman You're welcome 🙂
