### ISSUE TITLE
Can not depend on git packages

### ISSUE THREAD

**Issue by NobbZ** [cask/cask#413]
I have to dependencies on git packages in my cask file:

```el
(depends-on "dropboxer"
            :git "https://gitlab.com/NobbZ/emacs-dropboxer.git"
            :branch "master")
(depends-on "mix-format"
            :git "https://github.com/anildigital/mix-format.el.git"
            :branch "master")
```

Both fail with the following error:

```plain
Dependency mix-format failed to install: Wrong type argument: sequencep, mix-format
Output:

```

It works on another machine of mine, but I can't access it before monday to check cask version.

Version on this machine is:

```plain
$ cask --version
0.8.1
```

This is an archlinux box with cask installed from AUR: https://aur.archlinux.org/packages/cask/

**Comment by sambrightman** [comment]
I don't know much about Arch or their packaging but this is working for me on 0.8.1 and master (the version is probably overdue a bump, I thought perhaps they are building master and not appending any distribution suffix). There are also a couple of tests for Git-based installation IIRC. Do you notice anything with `--debug`? Have you tried cleaning out your `.cask` directory and starting fresh?

**Comment by NobbZ** [comment]
As far as I understand the script, it simply pulls the [0.8.1 tar](https://github.com/cask/cask/archive/v0.8.1.tar.gz) from github, extracts it and copies files as they are into the filesystem.

But I have to admit, the other systems where I used cask, even though they report 0.8.1 as well, were installed via `curl … | bash`-method.

But as I have moved only recently to arch (about last friday) after a lot of random installations without/besides the package managers broke my previous systems, I really want to try to be friendly to my system this time ;) And as far as I understand the script, `curl | bash` actually installs from master, doesn't it?

**Comment by NobbZ** [comment]
Addition: I deleted the `.cask`-folder, doesn't change anything. Also I've tried with `--verbose` and `--debug`:

```plain
$ cask install --debug --verbose
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Debugger entered--Lisp error: (error "Dependency mix-format failed to install: Wrong type argument: sequencep, mix-format
Output:
")
  signal(error ("Dependency mix-format failed to install: Wrong type argument: sequencep, mix-format\nOutput:\n"))
  error("Dependency %s failed to install: %s\nOutput:\n%s" mix-format "Wrong type argument: sequencep, mix-format" "")
  (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output))
  (let* ((data (cdr err)) (dependency (progn nil (or (progn nil (and (vectorp ...) (>= ... 8) (memq ... cl-struct-cask-dependency-tags) t)) (signal (quote wrong-type-argument) (list (quote cask-dependency) (nth 0 data)))) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))
  (condition-case err (progn (cask-install (cask-cli--bundle))) (cask-missing-dependencies (let ((missing-dependencies (cdr err))) (error "Some dependencies were not available: %s" (s-join ", " (-map (function symbol-name) (-map (function cask-dependency-name) missing-dependencies)))))) (cask-failed-initialization (let* ((data (cdr err)) (message (error-message-string (nth 0 data))) (output (nth 1 data))) (error "Package initialization failed: %s\nOutput:\n%s" message output))) (cask-failed-installation (let* ((data (cdr err)) (dependency (progn nil (or (progn nil ...) (signal ... ...)) (aref (nth 0 data) 1))) (message (error-message-string (nth 1 data))) (output (nth 2 data))) (if dependency (error "Dependency %s failed to install: %s\nOutput:\n%s" dependency message output) (error "Package installation failed: %s\nOutput:\n%s" message output)))))
  cask-cli/install()
  commander--handle-command(("install"))
  commander-parse(("install" "--debug" "--verbose"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/usr/share/cask/cask-cli.el" nil t)  ; Reading at buffer position 13463
  load-with-code-conversion("/usr/share/cask/cask-cli.el" "/usr/share/cask/cask-cli.el" nil t)
  load("/usr/share/cask/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/usr/share/cask/cask-cli.el" "--" "install" "--debug" "--verbose"))
  command-line()
  normal-top-level()
```

Exact `Cask`-file as I've used it is available online:

https://gitlab.com/NobbZ/emacs.d/blob/3d9da3057149a56ce2a63b21b13459d58b18e01a/Cask

**Comment by sambrightman** [comment]
Yes, that installation method is for master. I think this is likely #407 — `package-build` has been updated to a more recent version but Cask hasn't. Probably in some cases 0.8.1 was built/installed before melpa/package-build#12, whilst a fresh install will pull a fresh `package-build` during bootstrap. Using the master installation should workaround but I'll also tag 0.8.2 from after the fix was merged to Cask.

**Comment by sambrightman** [comment]
v0.8.2 is tagged via a branch. Please re-open if this doesn't fix it for you.

**Comment by NobbZ** [comment]
Yes, that release fixed it. Thank you! 🎉
