### ISSUE TITLE
Is casks dependency-handling only for non built-in packages?

### ISSUE THREAD

**Issue by lordnik22** [cask/cask#419]
I'm writing a package which requires/uses org and calc (both build-in packages).
I thought i could add them just as regular dependencies to my Cask-file with: `(depends-on "org")` and `(depends-on "calc")`

But when i now run my unit-test with: `cask exec ert-runner`
I get: `(void-variable org-heading-regexp)`.
As a "workaround" i added: `(require 'org)` to my package-file.

Should i even use variables/constants of other packages?
Can cask resolve the workaround in a better way?
Is cask here to replace all these "(require ')"-statements?

**Comment by Fuco1** [comment]
Cask is not a tool to replace the require calls, you still need them.  Cask only prepares the environment so that `require` can find the files, that's all.

**Comment by lordnik22** [comment]
Ah okay, thank you very much for that answer.

I will close this issue/question.
