### ISSUE TITLE
'cask package' is broken

### ISSUE THREAD

**Issue by dajva** [cask/cask#421]
A recent refactoring of [melpa/package-build](https://github.com/melpa/package-build/) broke `cask package`.

AFAICT the signature of `package-build-package` changed signature which is causing errors like these when running `cask package`:

```
Wrong number of arguments: #[(rcp version) "!�!�È	
\"�Ä\"�
ÊË$��(ÌÍ\"����4ÎÏ\"�[�GÐU�G���@@	$�[Ð�GW�X���	$�[ÎÓ!,�" [rcp source-dir file-specs files name package-build-default-files-spec package-recipe--working-tree package-build--config-file-list package-build-expand-file-specs eieio-oref ...] 6 ("/home/travis/.emacs.d/.cask/25.3/bootstrap/package-build-20180330.2032/package-build.elc" . 30212)], 5
make: *** [package-test] Error 255
```

I have seen similar errors for emacs versions between 24.5 to 25.3

**Comment by sambrightman** [comment]
Is your Cask up-to-date? There was a breaking change a few months back, which Cask has adapted to. I haven't seen all of those special characters before though.

**Comment by dajva** [comment]
I see this when doing `curl -fsSkL https://raw.github.com/cask/cask/master/go | python` on travis so should be up to date.
Here is an example of failing job: https://travis-ci.org/dajva/rg.el/jobs/360964311

I think the special characters are byte code. I guess the same issue should be present in interpreted code.

This looks like the offending commit: https://github.com/melpa/package-build/commit/f125214e47a63f8e1020ac31ddf62877c3c94ae7 which I think landed on `package-build` master on the 23rd of Mars where the signature of `package-build-package` defun changed.

I reported this in package-build first and they indicated there was some communication with cask team: https://github.com/melpa/package-build/issues/18#issuecomment-378006160
