### ISSUE TITLE
cask blocks BEGIN_SRC source block evaluation C-c C-c

### ISSUE THREAD

**Issue by HiroshiMatsumoto** [cask/cask#422]
When I have the following code in my .emacs.d/init.el

```
;; Emacs package system  
(require 'cask "~/.cask/cask.el")  
(cask-initialize)  
```

and try to evaluate the following source code block of a .org file by executing C-c C-c : org-ctrl-c-ctrl-c

```
#+BEGIN_SRC python
a = "test"
return a
#+END_SRC
```

it returns 

> Evaluation of this python code block is disabled

However if I comment out that init.el portion and restart emacs,
evaluation of source block in the .org file adds the following code block right below.
```
#+RESULTS:
: test
```

**Comment by sambrightman** [comment]
I don't use org mode. Is there any chance you are using an old version of org mode when this fails? There have been previous issues filed about inability to install org mode IIRC.

**Comment by conao3** [comment]
unconfirmed, and it's hard to imagine cask affecting org.
Close for now, but please reopen if you reproduce this issue.
