### ISSUE TITLE
cask unable to start : Given parent class package-recipe is not a class

### ISSUE THREAD

**Issue by robertpostill** [cask/cask#424]
Hi,
I'm having some trouble starting cask.  When I try to start it either from the command line or as part of my emacs startup process I get the following message:
Given parent class package-recipe is not a class
I'm guessing this isn't much to go on so:
I'm on OS X High Sierra (10.13.4)
I've installed cask via homebrew:
```
--- ~/.emacs.d ‹master› » brew info cask                                  255 ↵
cask: stable 0.8.4, HEAD
Emacs dependency management
https://cask.readthedocs.org/
/usr/local/Cellar/cask/0.8.1 (14 files, 166.6KB)
  Built from source on 2017-02-27 at 15:56:41
/usr/local/Cellar/cask/0.8.1_1 (14 files, 166.6KB)
  Built from source on 2018-02-02 at 01:05:05
/usr/local/Cellar/cask/0.8.2 (14 files, 167.0KB)
  Built from source on 2018-02-11 at 16:22:34
/usr/local/Cellar/cask/0.8.3 (14 files, 167.0KB)
  Built from source on 2018-03-23 at 14:55:52
/usr/local/Cellar/cask/0.8.4 (14 files, 168.7KB) *
  Built from source on 2018-05-13 at 13:33:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cask.rb
==> Dependencies
Required: emacs ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cask
--- ~/.emacs.d ‹master› »
```
My emacs config is found at [this github repo](https://github.com/robertpostill/emacs-config)

I'm running emacs 25.3 installed via homebrew too.

**Comment by sambrightman** [comment]
I believe you need to remove your cask bootstrap directory and let it bootstrap again, because Homebrew cask blocks self-upgrades. That is normally in `~/emacs.d/.cask` and then a version-named subdirectory.

Cask had to change due to a breaking change in a dependency, but probably more thought should have been given to backward compatibility.

**Comment by robertpostill** [comment]
Thanks, your advice and updating the cask invocation as per 
https://github.com/robertpostill/emacs-config/commit/3b22ff91296c813a2eb6d042055f8479ee9fdb64 has fixed it.

**Comment by sambrightman** [comment]
The hard-coded part should not be necessey I don’t think.
