### ISSUE TITLE
Use different `source` depending on environment variable

### ISSUE THREAD

**Issue by vermiculus** [cask/cask#425]
I'd like to make sure to test both MELPA and MELPA-stable to make sure those users aren't forgotten. Can this be done?

**Comment by vermiculus** [comment]
Rounding back on this, I created emake.el to have a tighter focus on continuous testing. Since it's based only on elisp and a makefile, this is trivial to do. 

Leaving this open in case someone wants to do the dev, though :smile:

**Comment by Fuco1** [comment]
Quite frankly I have no idea how to use emake.el given the instructions in the readme.  I looked into the emake.mk and it looks like a makefile :shivers:

I'm interested in this:

> In my own projects, switching from Cask to EMake reduced build time by 90 seconds

How exactly did this happen?  I have projects where the entire build including downloading emacs with evm and installing cask and running tests run in a minute, so this seems quite odd.  Do you perhaps mean the time on the whole matrix with 10+  subjobs?

If not, I'm sure there's place to improve cask's speed and I would like to do so!

**Comment by vermiculus** [comment]
I would've measured per-build since the container management of any automated CI is unpredictable from our point of view. I don't know where I was getting the 90s number from (perhaps it was a statistical oddity; I'll have to run more tests), but compare magithub's [build 899.3](https://travis-ci.org/vermiculus/magithub/jobs/381335598) with [build 901.3](https://travis-ci.org/vermiculus/magithub/jobs/381515426): there's a 8s (each) savings with both the `setup-CI` and `install` targets. I *believe* this comes simply from having less code and relying on Make to do some of the work; otherwise I would have to profile both cask and emake (comparing comparable steps) to determine any potential for performance improvements. (I don't have a clear source for the slowdown.)

There may also be an overhead with cask's use of python; I'm not sure.

---

Any feedback you can give on emake is of course greatly appreciated 😄 It is (as the name suggests) based on Make, though nothing but `emake.el` and a recent emacs is necessary to use it. `emake.mk` is an attempt at a generic makefile that can be used with Make's `include` to trim down a lot of the boilerplate necessary to drive `emake.el`. If you also have the time, I can make some time to talk about it over at [magithub's gitter channel](https://gitter.im/vermiculus/magithub). I've been basically absent from the internet for several months now (for which I apologize to everyone using my projects); perhaps my fresh eyes and your fresh perspective can produce a better README 😄

**Comment by Fuco1** [comment]
@vermiculus OK, I was super confused because from what it looked like to me you reinvented make syntax (in emake.mk) which seemed both totally unlispy and very ugly idea to me.  So it's just a regular make, that makes a lot more sense already! 

I also have this problem and I solved it by having [multiple `Cask` files](https://github.com/Fuco1/.emacs.d/blob/master/Makefile#L26) which I rename and copy around to run different scenarios.  Which is not great at all.  So a solution is definitely "needed".  I'm not sure what to do yet though.

**Comment by Fuco1** [comment]
As for speed, see #361 there are some quite ridiculous timesinks.

**Comment by vermiculus** [comment]
> it looked like to me you reinvented make syntax (in emake.mk) which seemed both totally unlispy and very ugly idea to me

Oh my goodness – that would be horrifying! I hope things make better sense now 😄 

---

One possibility is to re-introduce the special form `if` into Cask's DSL:

```elisp
(if sexp-1 sexp-2 sexp-3)
```
where `sexp-1` is passed through `eval` and `sexp-2`/`sexp-3` replace the entire sexp as appropriate – i.e., use the substitution model of evaluation. This is a crude solution, though, and may open the door to some pretty horrific-yet-somehow-awe-inspiring Cask files. You also could no longer reasonably guarantee the behavior of `cask install` with a given caskfile.

---

Another possibility – going along with the special-form idea – is something like this (similarly evaluated under substitution):
```elisp
(env-case "VARIABLE"
  ("VALUE-1" sexp-1)
  ("VALUE-2" sexp-2))
```

**Comment by Fuco1** [comment]
I think we should like to avoid any arbitrary evaluation because as soon as you give someone power to do an eval in `if`, they can actually run anything there and that would lead to, as you point out

> horrific-yet-somehow-awe-inspiring Cask files

The env-case is a better idea as that is very restricted to only string comparison, so there's no arbitrary computation and it's still very much total and analysable.

I was also thinking about adding a `-f` flag (for `--file`) to Cask that would simply take another cask file and either replace `Cask` or merge them together according to some rules we set up (i.e. dependencies sum, later overrides the version in case of conflict) etc.

That would be quite flexible and we wouldn't have to change the DSL at all.  If you ever worked with docker-compose this should be familiar.

**Comment by vermiculus** [comment]
An `-f` flag would certainly be flexible enough to handle this at the cost of some duplication (compared to the `env-case` stuff). It can probably be leveraged for other use-cases as well and would be more stable to implement.

I would caution against a merge, though, since that can introduce complexity that may be difficult for users to wrap their head around. (What happens with two `f` flags? What happens one two files have the same `(command ...)`? etc.)

**Comment by Fuco1** [comment]
My idea was that if you only specify one `-f` flag it will use that file literally, no magic.  If you specify more than one we would have a merge strategy in place and of course documented somewhere (for advanced users).  If you use none, it would look for `Cask` file as it does now.

**Comment by vermiculus** [comment]
What's your expected use-case for merging?

**Comment by Fuco1** [comment]
You can have one base `Cask` file and a bunch of overrides that would modify it.

So I can have `Cask` file like this

```
(source melpa)

(package "elsa" "0.1.0" "Emacs Lisp Static Analyser")

(depends-on "cl-lib" "0.3")
(depends-on "dash" "2.14")
```

and another one, called for example `Cask.stable` with this:

```
(source melpa-stable)
```

If I use `-f Cask -f Cask.stable` the `package` and `depends-on` would be kept but `source` would now be taken from the other (override) file.

Dependencies could be concatenated and highest versions could resolve conflicts, for example.  There are multiple ways to define the merge operation.

**Comment by vermiculus** [comment]
This project's own Caskfile has two `source` directives, so such a merge couldn't simply replace what's there; it's additive. In your example, you would have to remove `(source melpa)` from `Cask` and have a `Cask.head` that included `(source melpa)`. You would then need to merge in a copy of the caskfile each time.

Another option that would not require merging is some sort of `include` directive in the DSL.

**Comment by twlz0ne** [comment]
Any conclusion?

---

My current solotion is to create two Cask files:

``` sh
⋊> diff -u Cask-2{4,5}
--- Cask-24     2020-08-19 16:34:51.000000000 +0800
+++ Cask-25     2020-08-19 16:34:51.000000000 +0800
@@ -9,6 +9,4 @@
 (depends-on "edit-indirect")

 (development
- (depends-on "markdown-mode"
-             :git "https://github.com/jrblevin/markdown-mode"
-             :ref "365697302345f8b9dc10bc975477452a282f7ae0"))
+ (depends-on "markdown-mode"))
```

And then decide which one to use in [`.travis.xml`](https://github.com/twlz0ne/separedit.el/blob/a77ced2bfb18bd71be7f1a58fe9a75f31d9e96ee/.travis.yml#L24-L28):

``` yml
before_install:
  - if [[ $EMACS_VERSION = 24.* ]]; then
        ln -snf Cask-24 Cask;
    else
        ln -snf Cask-25 Cask;
    fi
```

**Comment by conao3** [comment]
It's reasonable to specify a caskfile to achieve this behavior, rather than putting a dependency on an environment variable in the cask.
I think it's fair to close this issue, but we welcome to comment.
