### ISSUE TITLE
cask install no longer prints anything

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#428]
I'm not sure if this is my configuration somewhere but on none of my machines `cask install` prints anything.  I have no idea if it hangs and/or what is the progress.

Is there anything I can do?

**Comment by sambrightman** [comment]
Have you tried `cask --help`? There are verbose and debug options.

**Comment by Fuco1** [comment]
Any reason why it is not verbose by default?  I have not yet seen any package manager that does not print anything.  I would expect an opt-out switch like `-q` to be quiet instead.  I think this is an odd UX choice.

**Comment by sambrightman** [comment]
It is common for Unix tools to be silent on success. You'd have to dig through the history to find any other reasoning for the change.

**Comment by Fuco1** [comment]
This still does not work for me.

I've tried all the following 

```
cask --verbose install
cask --debug install
cask --verbose --debug install
cask install --verbose --debug
cask install --debug
cask install --verbose
```

It prints no progress except

```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
```

Can we try to add something that would at least say "Installing package X of Y"?  Every other package manager out there does that and it seems like a very standard feature.  If the bundle has 50 dependencies it is extremly confusing to me what's going on.

You said 

> It is common for Unix tools to be silent on success

which is true, but this is also very *uncommon* for interactive commands.  Imagine `grep` was silent on success.
