### ISSUE TITLE
Is there a way to install dependencies but not development dependencies?

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#433]
There is the flag `--dev` but I don't see anything like `--no-dev`.

In which case I don't see much purpose in having the `development` section.

**Comment by dickmao** [comment]
The absence of `--dev` is the equivalent of `--no-dev`.  But that's besides the point.

No, there is no way to `cask install` without getting all the development dependencies.  As cask is a package development tool, it's unclear why you would want to exclude them.
