### ISSUE TITLE
Add `development` version of `files` which will be merged into the "production" set

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#439]
For example I might want to add test files to the load path (such as test helpers).

Currently I need to run `cask exec buttercup -L . -L tests`.  The `.` is now handled by #435.

Obviously I don't want to add tests to the packaged output, so this should only be active during development.

Alternatively we might add a directive `test` for specifying testing... maybe somehow mix into it the #84 mechanism.

**Comment by dickmao** [comment]
I am not in favor of adding a `files` manifest for development.  Ensuring its up-to-date'ness when one moves dev files around seems like an unnecessary bureaucratic gotcha.  `git add` and `git rm` is what you want to administer your dev files.
