### ISSUE TITLE
cask install should install dependencies of linked packages

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#444]
I have a project with

```
> cask link list                                                
elsa-0.1.0          /home/matus/.emacs.d/projects/Elsa/
```

but when I

```
cask emacs -nw -q
```

and `(require 'elsa)` in scratch I get `"package not found: dash"`

I think we should install dependencies of linked packages.  I would not try to add the linked package's elpa dir to the loadpath as that can get quite messy (plus you have no idea where the pacakges load from if multiple linked dependencies reference the same dependency).

**Comment by Fuco1** [comment]
There is a test which I think tests the above described behaviour: `cask-install-test/link` the problem is that the test is broken. It calls `cask-test/link` and then `cask-install` which pulls in the linked package from elpa not from the linked directory /shrug

**Comment by Fuco1** [comment]
Same issue happens if I install for example `smartparens` which depends on `dash` and then I delete `dash` directory.  Running `cask install` again will not pull in `dash`.

I think this is broken behaviour.

**Comment by Fuco1** [comment]
By the way, running flat vs deep dependecies isn't that slow

```
> cask install
time deps 0.025313324
time deps deep 0.309700513
```

This is on my .emacs.d which has 150 dependncies.  Yes it's 100 times slower but still under 1 second.

**Comment by dickmao** [comment]
Seems okay now.
