### ISSUE TITLE
GNU Emacs 26.1 COULD NOT BE BOOTSTRAPPED

### ISSUE THREAD

**Issue by signorinotang** [cask/cask#451]
![image](https://user-images.githubusercontent.com/8033759/48528779-64167a80-e8cb-11e8-9e99-4bbd9cb5e327.png)

**Comment by signorinotang** [comment]
How should I solve this problem?

**Comment by Fuco1** [comment]
You can see in the error messages that the package archives can not be accessed.  If you are using MacOS search through the issues there are some solutions.  It's most likely related to the tls implementation emacs uses

**Comment by conao3** [comment]
Yes, it's https access issue to (M)ELPA. please check the availability of gnutls from Emacs.
