### ISSUE TITLE
Cask for executing scripts

### ISSUE THREAD

**Issue by anquegi** [cask/cask#452]
I do not know if this is posible, but based on [this question](https://emacs.stackexchange.com/questions/46118/how-to-use-emacs-packages-in-emacs-lisp-scripting/46122#46122) in Emacs stack exchange, but I woul like this feature from [roswell](https://github.com/roswell/roswell), That can add package dependencies in the script:

```
#!/bin/sh
#|-*- mode:lisp -*-|#
#| <Put a one-line description here>
exec ros -Q -- $0 "$@"
|#
(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp (ql:quickload '(cl packages here) :silent t)
  )

.......
```

So I would like to do some thing similar in  Elisp scripts, and could load some libraries of emacs. 

```
#!/bin/sh
":"; exec emacs --quick --script "$0" "$@" # -*- mode: emacs-lisp; lexical-binding: t; -*-
;;; rcat --- cat
;;; Commentary:
;;; reverse lines cat function in elisp

;;; Code:

;;-*- mode: emacs-lisp;-*-
(require 's)

(condition-case nil
    (let (line)
      ;;commented out b/c not relevant for `cat`, but potentially useful
      (princ "argv is ")
      (princ argv)
      (princ "\n")
      (princ "command-line-args is" )
      (princ command-line-args)
      (princ "\n")

      (while (setq line (read-from-minibuffer ""))
        (princ (s-reverse line))
        (princ "\n")))
  (error nil))

(provide 'rcat)
;;; rcat ends here
```

**Comment by Fuco1** [comment]
I don't understand where cask comes into this.

**Comment by anquegi** [comment]
Well, I want that I can use the depedencies installed by cask, when launching an emacs script

**Comment by Fuco1** [comment]
So `cask exec <script here>`

**Comment by anquegi** [comment]
Ok thanks for clarifying this, It worked well
