### ISSUE TITLE
setx PATH "%PATH%;..." may be incorrect

### ISSUE THREAD

**Issue by bradyt** [cask/cask#457]
On Windows Server 2016.

The following block, is from 034db2613a1ae63545527ae3e615b06280931e00, and appears at https://cask.readthedocs.io/en/latest/guide/installation.html#windows-installation-and-setup. I believe this is replacing PATH with the string `%PATH%`, that is, the variable is not expanding.

```
   > setx PATH "%PATH%;c:\Python27\"
   > setx PATH "%PATH%;c:\bin\emacs\bin"
   > setx PATH "%PATH%;%userprofile%\.cask\bin"
```

Will take a closer look soon.

**Comment by dickmao** [comment]
Please reopen if this remains an issue.
