### ISSUE TITLE
Warning of load-path

### ISSUE THREAD

**Issue by kiimmm** [cask/cask#461]
Now I am using Emacs `27.0.50` in Ubuntu `16.04`.
When I try to execute Emacs with cask
`cask exec emacs`
There is warning like
```
Warning (initialization): Your ‘load-path’ seems to contain
your ‘.emacs.d’ directory: /home/kim/.emacs.d/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: /home/kim/.emacs.d/lisp
```
And I looked up `load-path` variable with `cask load-path`,
and `/home/kim/.emacs.d/:` appears in the first.

I think this one causes the warning, but I have no idea to solve it(like, how to delete this path from `load-path` in cask).

**Comment by Fuco1** [comment]
Cask automatically adds the project directory to the load path.  You can't fix it.  There is no reason to do `cask exec emacs` in the emacs directory, what is your goal?

**Comment by kiimmm** [comment]
My goal is to execute emacs with cask without warning.
When I configure cask at first, `(cask-initialize)` is in my `init.el`, 
and when I open emacs, there is warning 
```Warning (package): Unnecessary call to ‘package-initialize’ in init file```
So that I delete `(cask-initialize)` in `init.el`, and use `cask exec emacs`, and found it exec with cask and without "initialize error". (But with load-path error mentioned above).

**Comment by conao3** [comment]
The warning is just warning not an error. I don't think this warning can be fixed, so I'm closing it.
