### ISSUE TITLE
Obsolete macros in Emacs27

### ISSUE THREAD

**Issue by Ergus** [cask/cask#467]
Hi:
I am using cask in emacs 27 and I get a lot of warnings due to obsolete macros: `defmethod` and `defgeneric`. They must be (according to the same message) substituted by cl-* alternatives.

**Comment by conao3** [comment]
Thanks, But we support Emacs-24. (maybe relevant #491)

**Comment by condy0919** [comment]
`defmethod` is removed in Emacs 29, is it the time to reopen #523 ?
