### ISSUE TITLE
Fail initialize cask - Could not determine the version of Emacs at emacs

### ISSUE THREAD

**Issue by conao3** [cask/cask#471]
Hi! I interested in this project and use it in Travis CI.

I referenced your [.travis.yml](https://github.com/cask/cask/blob/master/.travis.yml) and your using [gist](https://gist.githubusercontent.com/rejeep/ebcd57c3af83b049833b/raw) but my build is failed with `ValueError: Could not determine the version of Emacs at emacs`.
Do you have any ideas and am I missing something?

```
language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=26.1-min
    - EMACS_VERSION=26.2-min
    - EMACS_VERSION=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS_VERSION=emacs-snapshot

# Ref: https://gist.github.com/rejeep/ebcd57c3af83b049833b
install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"

  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-26.3-travis --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

script:
  - make test
```
```
$ curl -fsSkL https://raw.github.com/cask/cask/master/go | python
Cloning into '/home/travis/.cask'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3668 (delta 0), reused 1 (delta 0), pack-reused 3664
Receiving objects: 100% (3668/3668), 1.19 MiB | 8.06 MiB/s, done.
Resolving deltas: 100% (2072/2072), done.
Traceback (most recent call last):
  File "/home/travis/.cask/bin/cask", line 425, in <module>
    main()
  File "/home/travis/.cask/bin/cask", line 405, in main
    exec_cask(sys.argv[1:])
  File "/home/travis/.cask/bin/cask", line 354, in exec_cask
    emacs = get_cask_emacs()
  File "/home/travis/.cask/bin/cask", line 298, in get_cask_emacs
    ensure_supported_emacs(emacs)
  File "/home/travis/.cask/bin/cask", line 230, in ensure_supported_emacs
    if not is_supported_emacs(emacs):
  File "/home/travis/.cask/bin/cask", line 215, in is_supported_emacs
    return get_emacs_version(emacs) >= MIN_EMACS_VERSION
  File "/home/travis/.cask/bin/cask", line 199, in get_emacs_version
    'Could not determine the version of Emacs at {0}'.format(emacs))
ValueError: Could not determine the version of Emacs at emacs
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues
The command "curl -fsSkL https://raw.github.com/cask/cask/master/go | python" failed and exited with 1 during .
```
Full CI log: https://travis-ci.com/flylint/flylint/jobs/247742286

**Comment by gregghz** [comment]
This happens in my project as well: https://travis-ci.org/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/builds/603296244?utm_medium=notification&utm_source=github_status

Ignore the emacs 24.x builds, those fail for a different reason (but you can see cask is getting past the above error). Emacs 25 works fine, but emacs 26+ fails as above.

**Comment by juergenhoetzel** [comment]
This is not an Cask issue: and [emacs-26.1-travis has runtime dependency on libgnutls.so.26](https://github.com/rejeep/evm/issues/125)

Quick fix update to trusty:
```
dist: trusty
```

**Comment by plandes** [comment]
The recommendation by @juergenhoetzel did not work for me.

Anyone else have any ideas on how to make this work?

**Comment by conao3** [comment]
Finally, I gave up to use prebuild Emacs on TravisCI.
I switched to GitHub Actions, use @purcell 's prebuild Emacs ([setup-emacs](https://github.com/purcell/setup-emacs)) and use my [setup-cask](https://github.com/conao3/setup-cask).
This approach aproved by many packages.
- [dash](https://github.com/magnars/dash.el)
- [php-mode](https://github.com/emacs-php/php-mode)
- [helm-swoop](https://github.com/emacsorphanage/helm-swoop)
- [leaf-keywords](https://github.com/conao3/leaf-keywords.el)

**Comment by plandes** [comment]
This worked for me:

```yml
dist: trusty

language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=26.2-min

matrix:
  allow_failures:
    - env: EMACS_VERSION=emacs-snapshot

# Ref: https://gist.github.com/rejeep/ebcd57c3af83b049833b
install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"

  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-26.2-travis --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

script:
  - cask --version
  - $(which emacs) --version
  - EMACS=$(which emacs) make test
```

**Comment by Fuco1** [comment]
@conao3 I agree that using github actions is now a better setup than the somewhat unmaintained evm&cask combo.  I'm going to close this but feel free to continue the discussion.
