### ISSUE TITLE
Unnecessary call to ‘package-initialize’ in init file in Emacs 27/28

### ISSUE THREAD

**Issue by anildigital** [cask/cask#476]
I use cask and I have installed Emacs 28. I see the following error due to cask. There is `package-initialize` in cask-bootstrap.el which is causing this.

```Warning (package): Unnecessary call to ‘package-initialize’ in init file```

Setting up following in `early-init.el` didnt' help either
```(setq package-enable-at-startup nil)```

**Comment by sergeyklay** [comment]
Refs: https://github.com/cask/cask/issues/463

**Comment by conao3** [comment]
Thanks. please move #463.
