### ISSUE TITLE
Cask doesn't update built-in packages

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#477]
In the following example, Cask fails to update `seq`:

```bash
$ cd /tmp/
$ mkdir cask
$ cd cask/
$ EMACS=emacs25
$ cat <<EOF > test.el 
;;; test.el --- A Cask test -*- lexical-binding: t; -*-

;; Author: …
;; Maintainer: …
;; Version: 1.0
;; URL: …
;; Package-Requires: ((seq "2.14"))
;;; test.el ends here
EOF
$ cask init --dev
$ cask install
Loading package information... done
Package operations: 5 installs, 0 removals
  - Installing [ 1/5] seq (2.14)... already present
  - Installing [ 2/5] el-mock (latest)... downloading
  - Installing [ 2/5] el-mock (latest)... done
  - Installing [ 3/5] ert-runner (latest)... downloading
  - Installing [ 3/5] ert-runner (latest)... done
  - Installing [ 4/5] ecukes (latest)... downloading
  - Installing [ 4/5] ecukes (latest)... done
  - Installing [ 5/5] f (latest)... already present
$ cask update
```

It says ` - Installing [ 1/5] seq (2.14)... already present`, but in fact seq 2.14 isn't present in emacs 25.2

**Comment by dickmao** [comment]
Thank you for the complete minimal working example.  tl;dr Avoid emacs-25.

In 2019, the elpa gpg key for emacs-25 expired.  It is discussed in various corners of emacsdom.  Here is one conversation https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00091.html

You will find `/tmp/cask/.cask/25.3/elpa/archives/gnu` empty whilst the melpa subdirectory nonempty.

Alas, the solution is very unwieldy.  One must copy a "good" keyring into /tmp/cask/.cask/25.3/elpa/gnupg.  This took me forever and a day to figure out in 2019.
