### ISSUE TITLE
Installing package from git reposotory doesn't appear to work

### ISSUE THREAD

**Issue by YorkZ** [cask/cask#478]
Here's the simplest Cask file:
```
(source gnu)
(source melpa)

(depends-on "org" :git "https://github.com/YorkZ/org-mode")
```
Emacs version: 26.3
Cask version: 0.8.4.
Command:
```
cd DIR-OF-CASK-FILE
cask
```
Result:

The package `org` wasn't installed in the sub directory `.cask/26.3/elpa`. The only thing created in this directory was a directory called `archives`.

**Comment by conao3** [comment]
This issue hard to solve. Please move to #169. This is a problem installing `org-mode` using cask.
I recommend specifying dependency as `org-plus-contrib`.
