### ISSUE TITLE
Silent failure for `files` directive

### ISSUE THREAD

**Issue by contrapunctus-1** [cask/cask#482]
Cask v0.8.4

In one of my projects, I renamed the sole .el file, but forgot to updated the `files` directive in the Cask file.

Now running `cask build` (which I mostly run for byte compiler warnings) silently did nothing, not even with `--verbose`, which caused me no end of frustration when someone else reported getting byte compiler warnings when trying to compile my project, which I (using `cask build`) simply could not reproduce.

Can Cask issue some kind of warning in such situations? e.g. when a file is specified in a `(files ...)` form, but it does not actually exist?

EDIT - a workaround for this particular project of mine is to just remove the files directive - the defaults seem to suffice. In other projects, it could be safer to specify a directory and a glob. Nevertheless, I would still very much like Cask to issue warnings in situations where a file is specified but does not exist.

**Comment by conao3** [comment]
I try to solve this issue via #528.
Now, `cask` doesn't catch any files (per files regexp specification) show warnings.

**Comment by dickmao** [comment]
#528 appears to solve this problem.
