### ISSUE TITLE
Cannot bootstrap on Emacs 24.5: fresh version of package-build requires emacs-25.1

### ISSUE THREAD

**Issue by immerrr** [cask/cask#491]
Hi,

I have been updating the CI tooling for my package, and there were some issues with earlier emacsen. I started debugging it locally, and found that I couldn't bootstrap cask for `emacs24` (debugging messages mine):
```
$ EMACS=emacs24 cask --help
cask-bootstrap  # meaning we are in cask-bootstrap file
<...snip...>
In end of data:
shut-up.el:152:1:Warning: the following functions are not known to be defined:
    shut-up-write-region-original, shut-up-load-original
Wrote /home/immerrr/.emacs.d/.cask/24.5/bootstrap/shut-up-20180628.1830/shut-up.elc
Done (Total of 2 files compiled, 1 skipped)
checking package cl-lib (installed=t)
checking package package-build (installed=nil)
Package `emacs-25.1' is unavailable
```

And indeed, looks like https://github.com/melpa/package-build/commit/6f262f9e5b683b93375cb6507a1964b077da7fbe commit introduces dependency on `cl-defmethod` and `emacs-25.1`.

Is there a way to continue using cask for emacs-24.*?

**Comment by conao3** [comment]
This may not be what you expected, but I think it's good news.
I think we need to drop Emacs-24.* and get this project more active.

**Comment by immerrr** [comment]
This may be good news for cask the project.

For me as maintainer of `lua-mode` it probably means more work. `lua-mode` still works on all Emacsen back to 24.3, and I intend to keep that for at least a year, until the end of life of Ubuntu 16.04 LTS that comes with Emacs 24.3. So to do that I need to figure out a way to make cask work or to ditch it and use something else.

**Comment by conao3** [comment]
Yes, we have another choice, it's [Keg](https://github.com/conao3/keg.el).
I develop it for the purpose of replacing cask before I become the maintainer of cask, as I fear that cask is not maintained.
It doesn't rely on package-build (I've bundled a function in keg that does the same output)
So it will also work on Emacs-24. It's still under development and unstable, but it's an interesting option.

**Comment by Silex** [comment]
I have the same problem. Does that mean I can effectively remove my `emacs:$VERSION-ci-cask` images when `$VERSION` is less than `25.1`?

**Comment by immerrr** [comment]
FWIW, it should not be _major_ work. I think it could be enough to vendor a `package-build` version prior to the commit I linked in the issue description and use it for older Emacsen. There should not be any licensing issues (both are GPL), I can put together a PR if it is welcome.

**Comment by Silex** [comment]
Yeah, forcing an old version would work... @conao3 your call.

**Comment by immerrr** [comment]
Here's a tentative PR to fix backward compat with Emacs24: https://github.com/cask/cask/pull/492

**Comment by conao3** [comment]
492 is correct, but we don't want to maintain `package-build` upstream and here...
(But I think it's also a natural way, cask is already a legacy, and to support Emacs-24, which is a legacy.)

@tarsius, please comment, why did you drop Emacs-24? Any statistics on which your decision was based?

**Comment by tarsius** [comment]
The only numbers this decision was based on is https://www.gnu.org/software/emacs/history.html. IMO it would be a good thing if package authors stopped supporting Emacs 24. Emacs 25, 26 and now 27 bring so many new goodies to the table. Holding of using "new" features for half a decade or more because they didn't make it into 24.* seems like a waste. Of course backward compatibility also has its benefits, so we have to compromise. The compromise I chose here is to wait eight years (or five if you count 24.5) and three subsequent major releases.

**Comment by tarsius** [comment]
The corresponding `package-build` pull-request is https://github.com/melpa/package-build/pull/41.

**Comment by tarsius** [comment]
> FWIW, it should not be _major_ work. I think it could be enough to vendor a `package-build` version prior to the commit I linked in the issue description and use it for older Emacsen, much like what is done with `package-legacy.el`.

Considering that you are already doing this for `package-legacy.el`, I think doing it like this is okay.

Sorry for the inconvenience.

**Comment by Silex** [comment]
Just out of curiosity, do you have a rough estimate on how many people use each version? I'd be surprised if many people still used Emacs 25, let alone Emacs 24.

**Comment by tarsius** [comment]
I am under the impression that only package authors who want to be considered of users that still use Emacs 24 still use Emacs 24!

**Comment by immerrr** [comment]
I have been on Emacs 24 more than I would be proud about, Emacs packages on Ubuntu used to be significantly behind the releases, and it didn't help that I am not a big fan of OS upgrades that break stuff on a regular basis, and still using Ubuntu 16.04 LTS. So, yes, although I am right now on Emacs master, I can relate to people who cannot update their Emacs for whatever reason. And yes, it could be my personal preference, that if I am using a software package, I would prefer to keep it in workable but suboptimal state, rather than having my workflows broken after a software update (2 steps forward, 1 step backward).

It is understandable that the development moves onward, and if a new version does not work with an older version of Emacs, you just use the old version. It is just that Emacs package tooling is not necessarily built to withstand the code rot: there are no repositories that I know of that would allow you to install a 5-year old version of magit using a 5-year old `package.el`. You either can run a new and shiny version with one click of a button, or you have to figure the installation on your own, just the way you did before Emacs 24 (in the stone age), going through git repos, downloading packages alonside their dependencies, and altering load paths manually.

**Comment by conao3** [comment]
Thanks, @tarsius. Overall, I think it's a good change.
> I am under the impression that only package authors who want to be considered of users that still use Emacs 24 still use Emacs 24!

I agree :) I think that where Emacs-24 is most often used may be in the CI environment to ensure excessive support.

Well, anyway, this project isn't mine, I'm just being asked to manage it.
I think I'm being asked to make conservative decisions, so I'll change it to use package-build-legacy. Thanks.

**Comment by conao3** [comment]
@Silex, your docker image build works well on Emacs-24?

**Comment by Silex** [comment]
@conao3: no. The image built prior this change works so that's the one people are getting.

**Comment by conao3** [comment]
I dive into it, some issues solved but some have remained.

Now, Emacs-24.5 can bootstrap cask but Emacs-24.4 cannot.
```
$ docker build -t cask-24.4 -f docker/Dockerfile-24.4 .
Sending build context to Docker daemon  3.822MB
Step 1/6 : FROM silex/emacs:24.4-dev
 ---> 9248cf07fddd
Step 2/6 : RUN apt update     && apt install -y python3     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f33526529b8d
Step 3/6 : RUN ln -sf /usr/bin/python3 /usr/bin/python
 ---> Using cache
 ---> 8cebda535b63
Step 4/6 : WORKDIR /cask
 ---> Using cache
 ---> 078f6dc1152d
Step 5/6 : ENV PATH /cask/bin:$PATH
 ---> Using cache
 ---> 8d367c5a523e
Step 6/6 : CMD ["bash"]
 ---> Using cache
 ---> 6cbf7c00f221
Successfully built 6cbf7c00f221
Successfully tagged cask-24.4:latest

$ docker run -it --rm -v $HOME/dev/forks/cask:/cask cask-24.4 bash
root@5e26252dbba6:/cask# cask
package-build-legacy.el: `object-class-fast' is an obsolete alias (as of 24.4); use `eieio--object-class' instead.
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: stable.melpa.org:443
gnutls.c: [0] (Emacs) fatal error: A TLS fatal alert has been received.
gnutls.c: [0] (Emacs) Received alert:  Handshake failed
gnutls.el: (err=[-12] A TLS fatal alert has been received.) boot: (:priority NORMAL :hostname stable.melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download `melpa' archive.
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Package `s-' is unavailable
```
Any ideas? Finaly we cannot :_( ?

Maybe relevant [Emacs-devel thread](http://emacs.1067599.n8.nabble.com/bug-20465-24-4-GnuTLS-integration-seems-faulty-td357111.html) and [the patch](https://github.com/emacs-mirror/emacs/commit/ccae04f205db7cffa0f247a463272f6c5af77122).

**Comment by immerrr** [comment]
I wonder if we could use something like
```
(require 'tls)
(setq tls-program "openssl s_client -connect %h:%p -no_ssl3 -no_ssl2 -ign_eof -CAfile %t")
```

and fall back to external `openssl` client for the older versions.

**Comment by immerrr** [comment]
Ok, this seems to work on `cask-24.4` image built by :
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(require 'tls)
(setq tls-program '("openssl s_client -connect %h:%p -no_ssl3 -no_ssl2 -ign_eof"))
(defun gnutls-available-p () nil)
(package-refresh-contents)
```

**Comment by immerrr** [comment]
Here, what about this? https://github.com/cask/cask/pull/512

**Comment by conao3** [comment]
Thanks, I'll check it.

**Comment by dickmao** [comment]
Seems okay now.
