### ISSUE TITLE
Bad request when cask install

### ISSUE THREAD

**Issue by jcs090218** [cask/cask#501]
I constantly getting the following error while using Cask.

```
Dependency spinner failed to install: https://elpa.gnu.org/packages/spinner-1.7.3.el: Bad Request
```

I think this occurs when package rely on ELPA's package and the operating system is on macOS. Linux doesn't seems to bother this issue.

**Comment by conao3** [comment]
How to install your Emacs, by homebrew, by build yourself... And please tell me Emacs, macOS version.

**Comment by jcs090218** [comment]
Hi @conao3,

I am building from CI; see [here](https://github.com/emacs-lsp/lsp-mode/pull/2593/checks?check_run_id=1848069531).

**Comment by conao3** [comment]
Oh, lsp-mode CI... OK, I will look into it.

**Comment by jcs090218** [comment]
I don't know if this is a cask issue, but this occurs in Emacs 26.2 macOS. The most annoying thing is that sometimes it passed and sometimes it didn't. If I installing it through by using a simple Elisp seems fine.

**Comment by jcs090218** [comment]
I think this is solved? Close this now! Thank you! :)
