### ISSUE TITLE
Drop Emacs-24.1~24.4 support?

### ISSUE THREAD

**Issue by conao3** [cask/cask#523]
Emacs-24.4 is not able to download packages from MELPA. https://github.com/Silex/docker-emacs/issues/72
[emacs-nix-ci](https://github.com/purcell/nix-emacs-ci) can be downloaded by purcel's patch, but I'm bit hesitated about testing it with patched Emacs.
(Even if CI can be forced to work, if it doesn't work in the user's environment, there is no reason to support it.)

However, cask is a widely used build tool, and raising the required version of cask requires a cautious attitude.
But even now, Emacs-24.1, 24.2, and 24.3 cannot resolve the cask dependency and CI is failing. https://github.com/cask/cask/actions/runs/566090457 (CI on Emacs-25 is failed randomly for other reason)

[Tarsius's point](https://github.com/cask/cask/issues/491#issuecomment-724840312) is also in a joking tone, but it seems to good point I think.

CC:
- cask author: @rejeep 
- MELPA maintainers: @milkypostman, @purcell, @tarsius, @riscy

---
Resources
- List of version (https://repology.org/project/emacs/versions)
  - Emacs-24.1
  - Emacs-24.2
  - Emacs-24.3: CentOS 7 (EOL at 2024), Ubuntu 14.04 (EOL at 2022)
  - Emacs-24.4
  - Emacs-24.5: Ubuntu 16.04 (EOL at 2024)
  - Emacs-25.1
  - Emacs-25.2: Ubuntu 18.04 (EOL at 2028)
  - Emacs-25.3

- EOL info
  - https://wiki.ubuntu.com/Releases
  - https://wiki.centos.org/About/Product

**Comment by dickmao** [comment]
I believe I've resolved the issue in commit 37052df, in which I determined 24.1 and 24.2, because they lack the function definition of `cl-flet`, would be a bridge too far for continued testing on those versions.  Currently `master` tests from 24.3 onwards.

I won't close this issue after you've inexplicably reopened it, except to say inexperienced devs erroneously consider issue proliferation as progress, when in fact adding labels and issues do nothing to advance the project (because no code was written).

**Comment by conao3** [comment]
Writing code isn't the only way forward.
As far as I can tell from the EOL information and the new release information in the distribution, I think it's fair to start supporting Emacs-24.5. However, we don't yet know how many packages this decision will affect. We don't have enough information.

This project was led by @rejeep and we just assumed his project. We need to be humble in our maintenance.

**Comment by dickmao** [comment]
Well, I am all for just supporting 24.5 or above but [you seemed to consider that premature](https://github.com/cask/cask/pull/536#discussion_r592149454).

If you want to kill off 24.3 and 24.4, I am all for less maintenance.  Minimally, it would better for carbon emissions to run fewer CI jobs.  :winky face emoji:

This is a debate you seem to be having with only yourself however.  I don't think anyone else particularly cares, or if they do,  they wouldn't know about this obscure issue on this obscure github repo.  Generally, the best way to elicit community reaction is to start brreaking things (that's certainly how I came to ask to become a maintainer).

**Comment by tarsius** [comment]
I support this as well.

**Comment by purcell** [comment]
Supporting only 24.5+ seems very reasonable to me. If someone _really_ wants to test their elisp tool against very old Emacs versions, there are ways to install packages in CI without using Cask. Most package developers shouldn't care too much, and will just disable CI for those older Emacsen if they know to do so. It's probably worth printing a clear message at runtime so that any affected developers don't have to scour the internet.

**Comment by dickmao** [comment]
> I won't close this issue after you've inexplicably reopened it

Changed my mind.  Feel free to remove any of the tested versions,

**Comment by conao3** [comment]
Wait, I'd like to determine a rational decision-making policy for changing the supported version of cask.
I agree with @purcell that support for Emacs24.5+ is reasonable based on EOL and the release status of the new version.
If we close this issue without finishing this discussion, we will have to support Emacs24.3+ semi-permanently.
I apologize for my recent inactivity. Personal life events have prevented me from taking the time to do so recently.

**Comment by dickmao** [comment]
> I apologize for my recent inactivity.

There is a saying in Western societies, "No news is good news."  So inactivity is to be celebrated, not apologized for.

> If we close this issue without finishing this discussion,

I just care about keeping the outstanding issues actually "outstanding" in nature.  I believe none of the parties @tagged in this discussion use Cask anymore, especially not for emacs24.  At this point it costs us nothing to continue supporting emacs24.3-24.5 except a few femtodegrees in the github server room.

There is another saying in Western societies, "Premature optimization is the root of all evil."  Adding deprecation notices willy-nilly, and starting discussions when no one asks for such discussion, are examples of this.

**Comment by conao3** [comment]
> I just care about keeping the outstanding issues actually "outstanding" in nature.

Yes, I thanks your issue management. As your activities, this issue board is much healthier.

Well,,, what do we do? Under what circumstances can we turn off support for the old Emacs?

**Comment by dickmao** [comment]
> Well,,, what do we do?

Hahaha.  Reach deep into your soul.  If your heart is pure, the answer will appear before you.  I can say with 100% certainty that the world will abide by your decision.

**Comment by conao3** [comment]
OK, I'll make a new release in June this year that removes the go script and makes Emacs-24.5+ support.

https://github.com/cask/cask/blob/b767e73717ba604e050027374c93b59cfd5ce7df/go#L96

What should I do? I think I should show a warning banner when the user runs cask on Emacs-24.4 or lower. What do you think?

**Comment by conao3** [comment]
Reopen issue. I will keep this issue open until June so that users can easily find it when they look at the issue board.
