### ISSUE TITLE
Cannot open load file

### ISSUE THREAD

**Issue by turboMaCk** [cask/cask#526]
I'm running into this issue when using HEAD https://github.com/cask/cask/commit/b81a3caa3fa3696fd385aa7072f8dc3a57408c4a

I'm using Linux and Emacs 27.1

## Stacktrace

This is the result of running `emacs --debug-init`

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "s")
  require(s)
  (condition-case nil (require pkg) (error (if package-archive-contents nil (package-refresh-contents)) (package-install pkg) (require pkg)))
  (let ((pkg (car --dolist-tail--))) (condition-case nil (require pkg) (error (if package-archive-contents nil (package-refresh-contents)) (package-install pkg) (require pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (condition-case nil (require pkg) (error (if package-archive-contents nil (package-refresh-contents)) (package-install pkg) (require pkg))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- deps)) (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (condition-case nil (require pkg) (error (if package-archive-contents nil (package-refresh-contents)) (package-install pkg) (require pkg))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let ((load-path load-path) (package-archives '(("gnu" . "https://elpa.gnu.org/packages/") ("melpa" . "https://stable.melpa.org/packages/"))) package-alist package-archive-contents (package-user-dir cask-bootstrap-dir) (deps '(s dash f commander git epl shut-up cl-lib cl-generic package-build eieio ansi))) (if (version<= emacs-version "24.4") (progn (require 'tls) (defvar tls-program) (setq tls-program '("openssl s_client -connect %h:%p -no_ssl3 -no_ssl2 ...")) (defalias 'gnutls-available-p #'(lambda nil nil)) (if package--initialized nil (package-initialize)) (if (require 'cl-lib nil 'no-error) nil (package-refresh-contents) (package-install 'cl-lib)))) (if (version< emacs-version "25.1") (progn (require 'package-recipe (expand-file-name "package-recipe-legacy" cask-directory)) (require 'package-build (expand-file-name "package-build-legacy" cask-directory)) (delq 'cl-lib deps) (delq 'package-build deps) (delq 'eieio deps))) (if package--initialized nil (package-initialize)) (let ((--dolist-tail-- deps)) (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (condition-case nil (require pkg) (error (if package-archive-contents nil (package-refresh-contents)) (package-install pkg) (require pkg))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  eval-buffer(#<buffer  *load*-317926> nil "/home/marek/.cask/cask-bootstrap.el" nil t)  ; Reading at buffer position 3120
  load-with-code-conversion("/home/marek/.cask/cask-bootstrap.el" "/home/marek/.cask/cask-bootstrap.el" nil t)
  require(cask-bootstrap "/home/marek/.cask/cask-bootstrap")
  eval-buffer(#<buffer  *load*-967670> nil "/home/marek/.cask/cask.el" nil t)  ; Reading at buffer position 1861
  load-with-code-conversion("/home/marek/.cask/cask.el" "/home/marek/.cask/cask.el" nil t)
  require(cask)
  eval-buffer(#<buffer  *load*> nil "/home/marek/.emacs.d/init.el" nil t)  ; Reading at buffer position 442
  load-with-code-conversion("/home/marek/.emacs.d/init.el" "/home/marek/.emacs.d/init.el" t t)
  load("/home/marek/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x75dfb9>) #f(compiled-function () #<bytecode 0x7ab1f1>) t)
  command-line()
  normal-top-level()
  ```

**Comment by conao3** [comment]
Thanks for report! But I cannot reproduce your issue...
Please try this and please tell me more concrete reproduce steps?
- `~/dev/tmp/elisp/cask-init`
```elisp
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(require 'cask "~/dev/forks/cask/cask.el")

(cask-initialize)

(leaf magit)

(provide 'init)
```
- `~/dev/tmp/elisp/cask-init/Cask`
```
(source gnu)
(source melpa)

(depends-on "leaf")
(depends-on "magit")
```
- shell
```shell
cd ~/dev/tmp/elisp/cask-init
cask install
emacs -Q -l init.el
```
... will works well.

**Comment by conao3** [comment]
Please your `cask` directory into `cask.old` and re-clone `cask`, please try again.

**Comment by turboMaCk** [comment]
I can't figure how to define small reproducible example but I'll try. In a meantime this is the error I get when running `emacs -Q -l init.el`:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443 [2 times]
Contacting host: stable.melpa.org:443
Package refresh done
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations [2 times]
‘s’ is already installed
condition-case: Cannot open load file: No such file or directory, s
```

**Comment by conao3** [comment]
Did you try my step? It doesn't work either?

**Comment by turboMaCk** [comment]
yes your steps works. I also tried the way I configure my setup (I use cask as a manager for my emacs dependecies for my configuration) with just some minimal config and that worked as well. In my setup I have `.emacs.d` and `.cask` in $HOME. `Cask` file is part of `.emacs.d` and I install dependecies using `$HOME/.cask/bin/cask install`. In `init.el` I include `cask.el` as `(require 'cask "~/.cask/cask.el")`. I also use [pallet](https://github.com/rdallasgray/pallet) and org-mode in a way that most of my setup is in org file I compile and load from `init.el`. So far I have 2 theories:

a) it's some weird interaction with something in my setup and cask
b) The problem is that my `.emacs.d` is actually a symlink to other directory `~/Dotfiles/emacs.d`.

I'll try to do more testing in order to be able to provide more info. All I need for now is that this revision https://github.com/turboMaCk/cask of cask works just fine with my setup but I did not really bisect the history to find exact commit either. I will try few things and look into the history to determine what is the easiest way to debug this and either I'll try to come up with some reproducible example or do the bisecting and find an exact commit with caused the problem.

**Comment by conao3** [comment]
OK, bisect Cask give more information to us to debug this issue.
But I recommend to you to debug your init.el (and near environment such as symbolic links? (But I think it should works too.)).
You have two init.el, the one which I suggested, and your one.  Compare the differences between the two and please debug them.

**Comment by conao3** [comment]
Close for now. Feel free to reopen this if you find new information.
