### ISSUE TITLE
[help wanted] Cask maintainer on Windows

### ISSUE THREAD

**Issue by conao3** [cask/cask#532]
I bit maintain this project, but Windows support is clearly lacking...
I'm looking for someone to help us to maintain cask on Windows!

**Comment by jcs090218** [comment]
I can help. I would like more packages work on Windows and not just Unix-like system. :)

**Comment by conao3** [comment]
Thanks! I'm just `Collaborator`, I cannot give you push permission. Maybe only @rejeep can do it.
Anyway, if you are able to take a time and can contribute, could you start with a review of PR for windows?

**Comment by jcs090218** [comment]
> Thanks! I'm just Collaborator, I cannot give you push permission. Maybe only @rejeep can do it.

I have read the thread #376. Since @conao3 has made most commits recently, I think @rejeep should add @conao3 to the organization and give him the permission to take over cask? @conao3 has response issues and PRs very fast and apply quick fix if something goes wrong. I think he is the most qualify maintainer at this moment! :D 

> Anyway, if you are able to take a time and can contribute, could you start with a review of PR for windows?

Sure, I would do it in my spare time! :)

**Comment by rejeep** [comment]
@conao3 You're now an admin, hack away!

**Comment by conao3** [comment]
Thanks!
Plus, may I participate in `cask` org?

The member of cask org is public and currently only you have it set to open.
There is no way for the general way to list who has push rights for this repository by just read permission user. (There isn't, is there?).
Sometimes, such as when adopting cask, we want to see how many members belong to the org to make sure there are active maintainers.

If you don't mind, could you please invite me to `cask` org? I'm also interested in maintaining other `cask/*` packages.

**Comment by rejeep** [comment]
Right, didn't think of that. I sent an invite now.

**Comment by conao3** [comment]
Accepted! cask is great and a complement to Emacs' missing features. Again, thanks for all!

**Comment by conao3** [comment]
I invite @jcs090218 as a Collaborator. I will invite him to cask org once I see him some activity on Cask.
I'd like to have him take the lead on Windows issues.

Of course, other contributors are welcome, Cask is still an integral part of our workflow!

**Comment by jcs090218** [comment]
Accepted! Thank you! :)

**Comment by jcs090218** [comment]
@conao3 Actually, can you add me to org? I am also interested maintain some of cask packages too, e.g. `epl` and `shut-up` (maybe you can create a team and assign me to those repos). And of course, I will start working and review some of Windows PRs from this repo. :)

**Comment by conao3** [comment]
As I'm now org owner, I can. Well, I've been following your activities, so I think you'll be fine.
Let's make cask exciting again!

**Comment by jcs090218** [comment]
Joined! Thank you! :)

**Comment by conao3** [comment]
We have now three active maintainers, closing for now.
However, we are still looking for contributors and maintainers. Feel free to comment on this!
