### ISSUE TITLE
Cask slow comes from lack of screen output

### ISSUE THREAD

**Issue by conao3** [cask/cask#534]
cask is not slow, the python part is only a little bit, and 90% or more of the processing is done by Elisp.
But the lack of output is a problem.
The problem is compounded by the fact that the output is not printed to the terminal at the moment of output buffering.
The use of stderr should solve this problem.

**Comment by dickmao** [comment]
> cask is not slow

Well, we already disagree.

> But the lack of output is a problem.

Please specify a minimum reproducible example.  Reopen issue as appropriate.

**Comment by conao3** [comment]
[This](https://github.com/cask/cask/blob/663a2dfe4b202835b02dca009da15d27cbb7506b/cask.el#L730) `Loading package information...` doesn't show until [this](https://github.com/cask/cask/blob/663a2dfe4b202835b02dca009da15d27cbb7506b/cask.el#L742) `done` and `\n` output.
This is output buffering. If we use stderr, this issue will be disapear.

**Comment by conao3** [comment]
Can't you confirm it?

**Comment by dickmao** [comment]
Aight, you have a point.

**Comment by conao3** [comment]
a976bb70cab7fef00bfd2154eb9e51f58d7b3437 is perfect, thanks!
