### ISSUE TITLE
Maintainership request

### ISSUE THREAD

**Issue by dickmao** [cask/cask#535]
@rejeep @conao3 ,

I am humbly requesting push privileges to this repo.  I am maintaining my own fork of cask, and I think it would be easier for all if I were given the latitude to merge some fixes.  For example, `cask link list` is broken in master.

I believe you will find my stewardship of various repos including https://github.com/ecukes/ecukes to be responsive and tasteful.

Thanks for your kind consideration.

@dickmao

**Comment by conao3** [comment]
@dickmao! Thanks for your offer!
To be honest, I don't have much experience with ecakes and I was wondering.
If you are going to join, does that mean we should move all tests to ecakes?
Anyway, welcome aboard and let's make cask exciting again!

**Comment by dickmao** [comment]
Thanks.
