### ISSUE TITLE
GHA badge is not updated?

### ISSUE THREAD

**Issue by conao3** [cask/cask#539]
This is not important thing, but our CI is [green](https://github.com/cask/cask/actions) but badge on README is red which I see.
Do anyone know why?

**Comment by jcs090218** [comment]
Interesting... by seeing the image https://github.com/cask/cask/actions/workflows/test.yml/badge.svg. It's still failing even though the action has passed.

**Comment by akirak** [comment]
This is because you actually didn't run CI on master since 24 days ago: https://github.com/cask/cask/actions

You now ignore pushes to master: https://github.com/cask/cask/blob/master/.github/workflows/test.yml#L12

**Comment by jcs090218** [comment]
Yeah, that was what I was thinking. Should we add CI test on the master branch?

**Comment by akirak** [comment]
You may ensure CI on all branch or only on master, as in the following [example](https://github.com/alphapapa/org-ql/blob/master/.github/workflows/test.yml):

```yaml
on:
  pull_request:
  push:
    # Comment out this section to enable testing of all branches.
    # branches:
    #   - master
```

I don't know why @dickmao made [this change](https://github.com/cask/cask/commit/f01444bcad3d6b05eaf7f5fce5637a24a32c8b35) to exclude CI on master. A typical configuration would be the opposite, i.e. not `branches-ignore` on master but `branches` on master. Maybe it was an accident.

I would suggest enforcing PR reviews in this repository. You may feel uncomfortable, but it will prevent accidental commits like this. Considering the impact of this project, I think you will need to be more careful in pushing a new commit to master.
