### ISSUE TITLE
Cask failing on old certificate with elpa

### ISSUE THREAD

**Issue by theothornhill** [cask/cask#542]
Hi there! 

Over at csharp-mode, we are having some issues with emacs 26.1 and 26.2. They cant seem to connect to elpa, thus are not able to resolve dependencies. 

I dont understand how I can fix this, but maybe it is possible to disable package-check-signature for cask on 26.1 and 26.2?

If it is, can you please point me in the right direction?

Thanks in advance! :-)

**Comment by dickmao** [comment]
The signature stuff confuses me.  I'm sure there's a deft way to circumvent it, but such a solution would be just as temporal as the one you've chosen (disabling 26.1 and 26.2 for the time being).

I submitted https://github.com/emacs-csharp/csharp-mode/pull/236 as persisting with the evm images can only end in tears.
