### ISSUE TITLE
realpath not readily available on some systems

### ISSUE THREAD

**Issue by amake** [cask/cask#546]
In https://github.com/cask/cask/commit/d1ee01ba3c06a62e784c3982ad6f50dbabf5c00f `bin/cask` was changed from a Python script to a Bash script; in the process it introduced a dependency on the `realpath` command.

This command is not available by default on macOS. You can get it by installing coreutils with Homebrew or MacPorts, but by default with MacPorts (not sure about Homebrew) it will be installed as `grealpath`.

This is a fairly large annoyance, especially since it was working well enough before.

(Note that `readlink -f` is also not available on macOS, so canonicalizing a path really isn't a trivially portable thing. I imagine that's why the script was Python before.)

**Comment by dickmao** [comment]
my bad, mitigative commit 1c329de

**Comment by dickmao** [comment]
thanks for reporting, also.

**Comment by amake** [comment]
Thank you!
