### ISSUE TITLE
Failure to install newer version of package that is part of Emacs

### ISSUE THREAD

**Issue by tarsius** [cask/cask#550]
Cask fails to install a newer version of a package, if an older version of that package is part of Emacs. At the same time it reports that the requested version is already installed. It explicitly echoes the requested version, regardless of what that might be.

```
$ cat Cask 
(source gnu)
(depends-on "project" "0.5.4")
(depends-on "python" "0.27.1")
$ EMACS=emacs-27.2 cask install
Loading package information... done
Package operations: 2 installs, 0 removals
  - Installing [ 1/2] python (0.27.1)... already present
  - Installing [ 2/2] project (0.5.4)... already present
$ tree .cask/
.cask/
└── 27.2
    └── elpa
        └── archives
            └── gnu
                ├── archive-contents
                └── archive-contents.signed

4 directories, 2 files
$ grep "(project" /usr/local/share/emacs/27.2/lisp/finder-inf.el 
  (project . [nil nil "Operations on the current project"])
$ grep "(python" /usr/local/share/emacs/27.2/lisp/finder-inf.el 
  (python . [(0 26 1) nil "Python's flying circus support for Emacs"])
```

As you can see, it does not matter whether the version was specified in the Emacs release (as for `python`) or was left undefined (as for `project`).

**Comment by dickmao** [comment]
This basic failure mode is further evidence Cask is not really used for anything that needs to work.

Thanks for reporting.

**Comment by tarsius** [comment]
Thanks!
