### ISSUE TITLE
Fetchers (e.g., :git) seem to be broken

### ISSUE THREAD

**Issue by GuiltyDolphin** [cask/cask#552]
Some time after version `0.8.6` the fetchers seem to have become broken - example:

```
(depends-on "evil-remap"
    :git "git://github.com/GuiltyDolphin/evil-remap"
    :files ("*.el"))
```

If you check out the tag `v0.8.6` then this appears to work (as it was before I updated), but with `v0.8.7` and onwards this fails, with the message `Some dependencies were not available: evil-remap`.

**Comment by dickmao** [comment]
Sorry about this.  I inadvertently dropped the fetcher functionality for the last month or so.

A better test to prevent such egregious omissions has been added.  Thanks for reporting this bug.
