### ISSUE TITLE
ansi package issue

### ISSUE THREAD

**Issue by MiyamotoAkira** [cask/cask#554]
Hi, installing today cask I got this issue:
```
Contacting host: stable.melpa.org:443
https://stable.melpa.org/packages/ansi-20200611.944.el: Not found
```
The package name is clearly the convention used for melpa, not melpa-stable.

On my copy of the repo I changed the line on cask-bootstrap.el relating to the melpa package archive from 
```
("melpa" . "https://stable.melpa.org/packages/")
```
to
```
("melpa" . "https://melpa.org/packages/")
```
and that seems to have fixed my issue.

**Comment by conao3** [comment]
`cask` uses MELPA-stable from this commit ( https://github.com/cask/cask/commit/88a89d9d4bb6e17f6ab470c348bd5698a3c2a3b8 )

Hi, @immerrr, why are you change to MELPA-stable from MELPA? Can we restore the URL?

**Comment by immerrr** [comment]
I don't quite remember why, but it should be fine

**Comment by LewisCollum** [comment]
I ran into this issue when downgrading emacs from 27.2 to 26.3 (due to a TRAMP issue). I removed the `.cask` directory, then ran `cask install` and the issue went away.
