### ISSUE TITLE
`error "package.el is not yet initialized!"` when turn on debug output

### ISSUE THREAD

**Issue by twlz0ne** [cask/cask#557]
![Add_--debug_to_cask_install_·_twlz0ne_test-cask_a25e99d](https://user-images.githubusercontent.com/2653486/140098861-3968f6bb-2b9c-4912-a6c4-d9a953fe2f5d.png)

Reproduce:

```elisp
$ trash .cask/26.3/elpa/dash-20210826.1149
$ cask install --debug
Loading package information...
Contacting host: melpa.org:443
Debugger entered--Lisp error: (error "package.el is not yet initialized!")
  signal(error ("package.el is not yet initialized!"))
  error("package.el is not yet initialized!")
  package-installed-p(zzz-to-char (20210321 1707))
  package--mapc(package--add-to-compatibility-table)
  package--build-compatibility-table()
  package--update-downloads-in-progress(("melpa" . "https://melpa.org/packages/"))
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  epl-refresh()
  (progn (epl-refresh))
  (if refresh (progn (epl-refresh)))
```

Removing the following line (added in https://github.com/cask/cask/commit/7b637efa35148dca5e6de10d0beba72168762f1c) will solve the problem:

https://github.com/cask/cask/blob/fe66b65944be8e03359ffe6f06618ecab8232f6b/cask-bootstrap.el#L43

- macOS 10.13.6 & ubuntu-latest
- Emacs 25.1 ~ 26.3
- Cask https://github.com/cask/cask/commit/fe66b65944be8e03359ffe6f06618ecab8232f6b (2021-10-01)

**Comment by dickmao** [comment]
Thanks for reporting.
