### ISSUE TITLE
Cask install fails with error about being unable to install package "s-"

### ISSUE THREAD

**Issue by davidshepherd7** [cask/cask#559]
Hi, I've had trouble getting cask working on my laptop for a while now. The symptom was that it would print a message saying that it was unable to find the package `s-` (sorry, I've lost the exact error message now). This happened first during the `make install` command step but it also happened when I tried to run cask directly from its location in `bin/` inside the git repo.

I eventually found that the problem was a bad cache of `package-refresh-contents` in `~/.emacs.d/.cask/`. I fixed it by forcing the bootstrap script to ignore the cache but other people can probably fix it by deleting that directory.

Anyway, just wanted to share this solution in case it helps anyone else. Thanks for maintaining cask!

**Comment by dickmao** [comment]
Thanks, commit 026de18b attempts a fix for this longstanding bug.

#573 same.
