### ISSUE TITLE
Symbol’s value as variable is void: package-recipe--working-tree

### ISSUE THREAD

**Issue by hyc3573** [cask/cask#565]
I'm using emacs 29.0.50.

nothing have been worked. aur, directly running bin/cask after cloning the repo, make install than running cask... etc.
am I missing something? or is emacs 29 just too recent?
also, It seems like it should've been solved by #423 

full log (got this by just cloning the repo, then running bin/cask. release 0.8 branch emits slightly diffrent message with contacting host: melpa something added at the top.)
`Symbol’s value as variable is void: package-recipe--working-tree

Error: void-variable (package-recipe--working-tree)
  debug-early-backtrace()
  debug-early(error (void-variable package-recipe--working-tree))
  byte-code(    \"
\"!#
        \"$     \"      \"\"#!\"!\"\"##$" [package-recipe--working-tree rcp package-build-working-dir package-recipe--upstream-url defmethod (rcp package-recipe) file-name-as-directory expand-file-name eieio-oref name (rcp package-recipe) url format url-format repo defalias package-git-recipe-p eieio-make-class-predicate package-git-recipe package-git-recipe--eieio-childp eieio-make-child-predicate package-git-recipe-child-p make-obsolete "use (cl-typep ... 'package-git-recipe) instead" "25.1" define-symbol-prop cl-deftype-satisfies eieio-defclass-internal (package-recipe) ((tag-regexp :initform "\\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\( [+-][0-9]\\{4\\}\\)?\\)")) nil] 8)
  require(package-recipe)
  load-with-code-conversion("/home/user/.emacs.d/.cask/29.0/bootstrap/package-build-2.4/package-build.el" "/home/user/.emacs.d/.cask/29.0/bootstrap/package-build-2.4/package-build.el" nil t)
  require(package-build)
  (if (featurep pkg) nil (if (package-installed-p pkg) nil (if package-archive-contents nil (package-refresh-contents)) (package-install pkg)) (require pkg))
  (let ((pkg (car --dolist-tail--))) (if (featurep pkg) nil (if (package-installed-p pkg) nil (if package-archive-contents nil (package-refresh-contents)) (package-install pkg)) (require pkg)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (if (featurep pkg) nil (if (package-installed-p pkg) nil (if package-archive-contents nil (package-refresh-contents)) (package-install pkg)) (require pkg)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- deps)) (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (if (featurep pkg) nil (if (package-installed-p pkg) nil (if package-archive-contents nil (package-refresh-contents)) (package-install pkg)) (require pkg)) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let (package-alist package-archive-contents package--initialized (load-path load-path) (package-archives '(("gnu" . "https://elpa.gnu.org/packages/") ("melpa" . "https://melpa.org/packages/"))) (package-user-dir cask-bootstrap-dir) (deps '(s f commander git epl shut-up cl-lib cl-generic package-build eieio ansi))) (package-initialize) (if (version< emacs-version "25.1") (progn (if (package-installed-p 'cl-lib) nil (if package-archive-contents nil (package-refresh-contents)) (package-install 'cl-lib)) (require 'package-recipe (expand-file-name "package-recipe-legacy" cask-directory)) (require 'package-build (expand-file-name "package-build-legacy" cask-directory)))) (let ((--dolist-tail-- deps)) (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (if (featurep pkg) nil (if (package-installed-p pkg) nil (if package-archive-contents nil (package-refresh-contents)) (package-install pkg)) (require pkg)) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  load-with-code-conversion("/home/user/Git/cask/cask-bootstrap.el" "/home/user/Git/cask/cask-bootstrap.el" nil t)
  require(cask-bootstrap "/home/user/Git/cask/cask-bootstrap")
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_100>(#<buffer  *load*> "/home/user/Git/cask/cask-cli.el")
  load-with-code-conversion("/home/user/Git/cask/cask-cli.el" "/home/user/Git/cask/cask-cli.el" nil t #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_100>)
  command-line--load-script("/home/user/Git/cask/cask-cli.el")
  command-line-1(("-scriptload" "/home/user/Git/cask/cask-cli.el" "--" "install"))
  command-line()
  normal-top-level()`

**Comment by dickmao** [comment]
Verify `which cask` is a symlink to the latest.
Then `rm -rf /home/user/.emacs.d/.cask/29.0/bootstrap/` and try again.
