### ISSUE TITLE
Test in graphical display

### ISSUE THREAD

**Issue by trevorpogue** [cask/cask#566]
Is it possible to run tests in a graphical Emacs instance, one where `display-graphic-p` would return t as opposed to a terminal instance  like when running `emacs -nw`?

The reason is I cannot get to 100% coverage in my tests because my package executes some functions differently when the user is in a graphical Emacs versus in a terminal Emacs (like when running `emacs -nw`).

**Comment by dickmao** [comment]
```
cask emacs --batch --eval "(require (quote ert))" \
--eval "(ert-deftest mytest () (should-not (display-graphic-p)))" -f ert-run-tests-batch
```
```
cask emacs --eval "(require (quote ert))" \
--eval "(ert-deftest mytest () (should (display-graphic-p)))" -f ert-run-tests-batch
```
