### ISSUE TITLE
user-emacs-directory is changed silently.

### ISSUE THREAD

**Issue by gongzhitaao** [cask/cask#567]
https://github.com/cask/cask/blob/8e56e92762e76a0a98d565528250e37ba239fd79/cask.el#L709

In this new release, the `user-emacs-directory` is silently changed which might cause problems for users depending on the canonical `user-emacs-directory`, because, for example, some libraries depend upon `user-emacs-directory`.

My questions:
- what is the rationale to change the `user-emacs-directory`?
- Would it be better to have a workaround without changing `user-emacs-directory`?

Thanks!

**Comment by jcs090218** [comment]
I think that's the whole of sandboxing, so anything you do would **NOT** pollute your Emacs configuration (`~/.emacs.d/`), etc.

**Comment by gongzhitaao** [comment]
I agree that this is good for sandboxing.  However, this affects user who invoke emacs with `emacs` command as well.

**Comment by dickmao** [comment]
If either (1) or (2) is false, please produce a minimally reproducible example.

**Comment by gongzhitaao** [comment]
1. Save the following to `~/.emacs.d/tmp.el`

   ```
   (require 'cask "~/.cask/cask.el")
   (cask-initialize)
   ```
2. Invoke emacs with `emacs -Q -l ~/.emacs.d/tmp.el`.
3. Check the value of `user-emacs-directory`, for me. it points to `~/.emacs.d/.cask`.

**Comment by dickmao** [comment]
Note to self, no one reads the README.

I can tell more [draconian measures](https://github.com/cask/cask/commit/2eb520e64c2e1047319761df0bcc6fa5149f8cd6) are required to suppress public dissent.

**Comment by gongzhitaao** [comment]
I see.

IMHO, this breaking change should be made with caution.  I guess most user's workflow is `cask update` in the command line and then fire up emacs, when they find that suddenly everything breaks.

And what's worse, this is still the recommended way to use cask in emacs, see https://cask.readthedocs.io/en/latest/guide/usage.html#quickstart.

Question: what is the recommended way to use cask with emacs?

Thanks!

**Comment by dickmao** [comment]
The goal of cask is clean-room sandboxing.

To that end, anything that references or worse, modifies, the user's
personal emacs installation could be considered an error.

If your use of cask goes back to rejeep's time when `cask-initialize`
was expressly intended to manage your personal packages, then I
apologize for having abolished that usage pattern wholesale.
