### ISSUE TITLE
Make fails with package-build 3.2 (package-build-expand-file-specs obsolete)

### ISSUE THREAD

**Issue by furkanusta** [cask/cask#569]
> cask-cli.el:254:37: Error: ‘package-build-expand-file-specs’ is an obsolete function (as of Package-Build 3.2); use ‘package-build-expand-files-spec’ instead.

Replacing [(source)](https://github.com/cask/cask/blob/2eb520e64c2e1047319761df0bcc6fa5149f8cd6/cask-cli.el#L252=)
> (package-build-expand-file-specs path (list pattern))

with

> (package-build-expand-files-spec nil t path (list pattern))

Seems to fix the issue but I don't know how to do version check so that it doesn't break with earlier versions of package-build. Hence the lack of PR.

**Comment by dickmao** [comment]
True that.
