### ISSUE TITLE
install cask in macOS

### ISSUE THREAD

**Issue by zhumingpassional** [cask/cask#572]
in terminal, I input the foloowing
curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

Then the terminal shows the following, Is there any good method to install cask in macOS? 

Thanks.

!!!
!!! DEPRECATION NOTICE
!!!
!!!
!!! The cask go script will be removed on 2021/06/01.
!!!
!!! This is due to security concerns about the way python is
!!! invoked from curl, and to remove the python dependency from cask.
!!!
!!! The way to install cask without depending on the go script
!!! is very simple. Just clone Cask and pass the PATH.
!!!
!!! git clone https://github.com/cask/cask ~/.cask
!!! PATH=$HOME/.cask/bin:$PATH
!!!
!!! # If you want to make it permanent
!!! echo 'PATH=$HOME/.cask/bin:$PATH' >> .bashrc
!!!

Directory /Users/mingzhu/.cask exists. Is Cask already installed?

**Comment by dickmao** [comment]
```
git clone https://github.com/cask/cask
make -C cask install
```

**Comment by zhumingpassional** [comment]
Thanks for your response.

I tried the method as you said. But failed. After "make -C cask install", the following shows

bin/cask: line 56: emacs: command not found
rm -rf dist
expr: syntax error
bin/cask: line 56: emacs: command not found
make: *** [dist] Error 127

**Comment by jcs090218** [comment]
It seems like you need emacs installed to install cask?

**Comment by zhumingpassional** [comment]
@jcs090218 
 
Do you mean M-x package-install cask? 
I tried it, but also failed. It can not find cask.

**Comment by jcs090218** [comment]
No, I mean emacs should be in your environment PATH. The error shown, ` emacs command not found`.

**Comment by zhumingpassional** [comment]
Add the following to ~/.bashrc? 
export PATH=${PATH}:~/.emacs.d

If it's wrong, could you please provide the commands of adding emacs as env PATH?

**Comment by jcs090218** [comment]
Maybe something like:

```
export PATH="$HOME/emacs/bin:$PATH"
```

Are you able to call emacs from the terminal? Like `emacs --version`, etc.

---

I remember you can just do:

```
brew install cask
```

since cask is in brew.

**Comment by zhumingpassional** [comment]
I succeeded in set the env variables, and "emacs --version" is successful.

However, after executing brew install cask, it raises an error:
Error: cask: wrong number of arguments (given 1, expected 0)

After "make -C cask install", the following shows
bin/cask: line 56: emacs: command not found
rm -rf dist
expr: syntax error
bin/cask: line 56: emacs: command not found
make: *** [dist] Error 127

Thank you for your valuable response.
