### ISSUE TITLE
Is document about usage outdated?

### ISSUE THREAD

**Issue by hanasuke** [cask/cask#578]
Hi, all.

When trying to use cask with Emacs 27.1, Emacs got an error and could not load the plugin with error message `Symbol's function definition is void: cask-initialize`.
Below is my init.el.
```init.el
(require 'cask "~/.cask/cask.el")
(cask-initialize)
```

In cask.el, `cask-initialize` is obsoleted, and current function is not defined.
https://github.com/cask/cask/blob/master/cask.el#L702-L708
I think, the immediately following `cask--initialize` function is an alternative function.
https://github.com/cask/cask/blob/master/cask.el#L710

However, in ["Usage" part in Cask's doc](https://cask.readthedocs.io/en/latest/guide/usage.html#quickstart), it is described as below: 
> If you are using Cask for your Emacs configuration, add this to your ~/.emacs.d/init.el file:
>(require 'cask "~/.cask/cask.el")
> (cask-initialize)

**Comment by dickmao** [comment]
https://github.com/cask/cask/blob/2fd12b3aef435bcbdd31e64fbdfbbe69e7bcc65f/README.org?plain=1#L111
