### ISSUE TITLE
Please hide bundled package-build

### ISSUE THREAD

**Issue by tarsius** [cask/cask#580]
Occasionally package authors bundle third-party libraries, which the Emacsmirror tooling detects. I then open issues such as this to rectify the situation because it is a problematic practice. For users of Melpa (and Cask I presume) it is not an issue, but for people who install packages by cloning repositories and putting them on the `load-path`, it is. The bundled copies are never in sync and a user might end up with the outdated version earlier on their `load-path`, which leads to very confusing issues.

I don't know why you decided to lock down `package-build`. I guess there were too many breaking changes. (There are some upcoming breaking changes and some exciting new features, but after that I plan to stop.)

As far as I know Cask isn't a package that is being loaded into interactive Emacs sessions, so it *probably* isn't an issue to bundle an outdated version. (But if I am wrong about that, then this is a problem.)

Please hide the bundled `package-build` from tools that search for libraries in a directory and its subdirectories, by adding the file `package-build/.nosearch`. Thanks!

**Comment by dickmao** [comment]
Remove cask from melpa [like I asked](https://github.com/melpa/melpa/pull/8021#issuecomment-1125223221) and this problem goes away.
