### ISSUE TITLE
Install cask with cask?

### ISSUE THREAD

**Issue by cfclrk** [cask/cask#582]
I have a stanza like this in a `Cask` file (which used to work):

```emacs-lisp
(development
 (depends-on "cask"))
```

Specifically, I was using the `cask-setup` and `cask-files` functions in order to get a list of files in the package.

Installing cask in this manner recently stopped working for me. I get:

```
Debugger entered--Lisp error: (error "Some dependencies were not available: cask")
```

Is this installation method no longer supported?

**Comment by jcs090218** [comment]
Cask has been removed from MELPA (see https://github.com/melpa/melpa/pull/8021), so you will need to install by specifying full keys.

```elisp
(depends-on "cask" :git ...)
```

**Comment by dickmao** [comment]
As described in the README, one can no longer require `'cask` for the purpose of calling cask functions in user elisp.

Cask is exclusively a command-line tool, e.g., `cask files`.

I know... people who unilaterally obsolesce long-time functionality suck.
