### ISSUE TITLE
Guidance for how to integrate in a dev-container

### ISSUE THREAD

**Issue by mohkale** [cask/cask#587]
Hi,

I'd like to be able to create a self contained container image that can be used for development. Sadly it looks like cask always installs dependencies relative to the project root so you need a separate cask install stage and have to persist the dependencies outside of the container image. Is there a way to set `cask package-directory` to a custom location in my container builds?

This was what I had going while testing.

```dockerfile
# Install all Emacs package dependencies.
RUN mkdir -p /tmp/projection-build
COPY Cask /tmp/projection-build
COPY src /tmp/projection-build/src
RUN cd /tmp/projection-build \
 && cask install \
 && rm -rvf /tmp/projection-build
```

I'd basically like something to the affect of pythons pip behavior where it can install to some location for the user but by default will install to a global shared location.

**Comment by jcs090218** [comment]
No Cask wasn't design for this, unfortunately! :( 

You can try out Eask:

#### 1. Use -g option

```sh
eask install -g <package-name>
```

#### 2. Config Eask-file

In your Eask-file:

```elisp
(setq user-emacs-directory "/path/to/.emacs.d/")
(setq package-user-dir "/path/to/.emacs.d/elpa/")
```

Then:

```sh
eask install-deps
```

#### Use global Eask-file

In homedir Eask-file:

```elisp
(depends-on "package-name")
```

Then:

```sh
eask install-deps -g
```

**Comment by dickmao** [comment]
```
( docker build --build-arg VERSION=28.2 -t projection_dev -f - . <<'EOF'
ARG VERSION
FROM silex/emacs:$VERSION-ci

ARG UNAME=projection

ENV PATH="/root/bin:$PATH"

RUN git config --global user.email "$UNAME@docker.com" \
 && git config --global user.name "$UNAME" \
 && mkdir -p "/root/bin"  \
 && git clone https://github.com/cask/cask  \
 && make -C cask install
WORKDIR /workarea
RUN git clone https://github.com/mohkale/projection
WORKDIR /workarea/projection
RUN cask

CMD bash
EOF
    ) ; docker run --rm projection_dev make test
```

**Comment by mohkale** [comment]
@dickmao 

I don't think the snippet you've shared really addresses the problem here. It's not me wanting to install cask in a container, it's me wanting to install the elisp dependencies of my project alongside the docker image build (so I don't need a separate docker build and then within the container run cask install the first time I bring it up).

Also for future reference so other's don't end up doing this, there are variants of image tags under silex/emacs and some of them automatically come bundled with cask. This is documented in the README but unless you're building something very strange you should just use the tag that ships with cask builtin rather than installing yourself after the fact.

Thanks for eask suggestion @jcs090218. I'll try switching to it and create an issue on the eask repo if I run into any issues.

**Comment by dickmao** [comment]
90% of your initial question discussed containers when your question had nothing to do with them.

```
cask eval "(progn \
(add-function :override (symbol-function (quote cask-elpa-path)) \
  (lambda (bundle) \"/var/tmp/baz\")) \
(cask-cli/install))"
```

**Comment by mohkale** [comment]
The containers talking point was for context. Thanks for the advice suggestion.
