### ISSUE TITLE
Cask fails to initialize - Cannot open load file" "No such file or directory" "package-build"

### ISSUE THREAD

**Issue by priyatam** [cask/cask#589]
I've been using Cask for 8+ years and recent updates (< 1 year) has broken my emacs config. I've tried to recreate a minimal config for use with [Cider](https://github.com/clojure-emacs/cider) and Emacs fails to load 

Cask

```
(source melpa-stable)
(depends-on "cider")
...
(depends-on "package-build")

;; 1+ year ago this worked, but this package has moved
;; (depends-on "package-build" :git "https://github.com/melpa/package-build" :ref "master")

```

init.el

```
(require 'package)
(require 'cask "/usr/local/share/emacs/site-lisp/cask/cask.el") ;; fails

```

`"Cannot open load file" "No such file or directory" "package-build"`

What am I missing? Why is Cask failing on the current Emacs initialization?

--
OS - Mac OS X Monterey - 12.6.6
Emacs Version - 28.2
Cask Version - 0.9.0

**Comment by dickmao** [comment]
> What am I missing?

You're not reading the README.  It says:

> In particular, I would not require cask in your dot.emacs since cask is now largely a command-line tool independent of whatever you do within emacs.

I would restore the 8-year-old `cask.el` to `/usr/local/share/emacs/site-lisp/cask`, or better yet, spend a day figuring out how  to get rid of cask.  You will bristle at this makework I've imposed upon you, but cleaning house once every eight years a'int so bad.

**Comment by priyatam** [comment]
Just to be clear—I've updated Cask/Emacs multiple times a year since 8 years and it's always worked eventually. It hasn't worked this year so far.

You comment doesn't answer my question: I have a Cask file with all dependencies.  `cask install` is successful, however init.el fails with the cask-initialize as described in [docs(https://cask.readthedocs.io/en/latest/guide/usage.html#quickstart).

Why is package-build dependency not resolved when you `(require 'cask "/usr/local/share/emacs/site-lisp/cask/cask.el")`

**Comment by dickmao** [comment]
> You comment doesn't answer my question

You've asked several questions, all of them answered by the README:

> I would disregard nearly everything at cask.readthedocs.io, especially the [Quickstart page](https://cask.readthedocs.io/en/latest/guide/usage.html#quickstart).

**Comment by priyatam** [comment]
Emacs doesn't load cask dependencies without the initialization file. Your response leaves an impression that Cask is no longer maintained and Dead on Arrival. I will stop using Cask. Thank you.
