### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by fleimgruber** [cask/cask#594]
Trying https://github.com/cask/cask#installation on Windows, the command

```
make -C cask install
```

fails with:

```
make: *** cask: Not a directory.  Stop.
```

**Comment by dickmao** [comment]
Before your report, I gave cask a 0.05% chance of just working on
Windows.  Now I give it 0.00%.

Expect a reply in the next hour from another cask maintainer
harping on his Windows-capable cask clone.

**Comment by fleimgruber** [comment]
I know 2.5 years is a lot of time in Open Source, but I hoped that https://github.com/cask/cask/issues/532 would have increased the prior chances for this to something more than 0.05% chance.

Could we at least put a one liner into the README saying that Windows is not supported?

**Comment by dickmao** [comment]
[You got it](https://github.com/cask/cask/commit/580a37872b005204ea598b823f4bd34b87b32c38)

**Comment by fleimgruber** [comment]
Thanks. From the README:

> If you use emacs on Windows, you're not doing it right

I would suggest to keep READMEs free of personal opinion. FWIW just for other Windows users reading this: Emacs is officially supported on Windows for decades already and even if it sometimes is indeed frustrating, it is worth it in the end - Emacs is worth it.

> But for a sufficiently motivated Powershell bro, it would not be hard to finesse the =Makefile= for a typical Windows environment.

I am definitely not this bro. Luckily and maybe interesting for others: the Emacs [package](https://github.com/emacs-jupyter/jupyter) I wanted to test with Cask has support for the Cask alternative [eldev](https://github.com/emacs-eldev/eldev) which supports Windows. So I will silently walk away.

**Comment by dickmao** [comment]
> I would suggest to keep READMEs free of personal opinion.

Emacs's words, not mine:

> It is not our goal to “help Windows users” by making text editing on Windows more convenient. We aim to replace proprietary software, not to enhance it. We hope that the experience of using GNU Emacs on Windows will give programmers a taste of freedom, and that this will later inspire them to move to a free operating system such as GNU/Linux.
