### ISSUE TITLE
Archives

### ISSUE THREAD

**Issue by rejeep** [cask/cask#78]
Ideally we would be able to create a `Cask.lock` file with exact versions, but ELPA does not support multiple versions (madness I say). It's obviously really annoying that a bug in some other project can break my project when I install or update. So many times have I done an update to break my Emacs configuration without being able to go back and the only solution is to disable some plugin until the bug is fixed.

Here are a few solutions that makes things a little bit better.
1. For each install and update, cask archives the current build with a date.
2. As above, but only when the `--archive` option (a message could be used instead of a date)
3. We add a command `archive/stash/...` that saves the current build with a message.

For all solutions, we would add a command `apply/checkout/...` that replaces the current build with the saved one.

Thoughts?

**Comment by seanfisk** [comment]
> It's not the end of the world, but extremely annoying when you have something important to do at work and you cant get Emacs going.

+1 I can't tell you how many times this has happened to me. Does Cask currently offer a way to mitigate this problem (lack of locked/frozen packages)?

I like Cask and I think it's a step in the right direction for Emacs packaging. I'm not the best ELisp hacker, but I'd be willing to contribute some time to help implement `cask bundle` and `cask unbundle` if pointed in the right direction.

Thanks for creating Cask!

**Comment by rejeep** [comment]
@seanfisk It could probably be done by keeping older versions as @lunaryorn suggests above and using `package-alist` for initialisation, specifying versions from `Cask.lock`.

**Comment by seanfisk** [comment]
@rejeep Thanks for the quick reply! I am going to get my configuration migrated over to Cask; once I learn it a little better I may be able to contribute. Thanks :)

**Comment by Fuco1** [comment]
This is related to #137

**Comment by conao3** [comment]
Cask.lock is excessive (so I closed #137 to make this project issue board health), but I think it's reasonable to leave the old `.cask` directory in place for updates.

**Comment by dickmao** [comment]
> Wrong!

Breakage-upon-update is a time-honored emacs albatross.  But cask can't possibly be the answer.  In fact, I cannot recommend cask as anything but a package dev tool.  Using it as a package maintenance tool, i.e., calling `cask-initialize` in your `.emacs`, is fraught, especially as cask development has until recently been subdued.
